In [1]:
import numpy as np
import pandas as pd
import timeit

# Merging DataFrames

In [2]:
# Merging DataFrames with merge() function
staff_df = pd.DataFrame([{"Name": "Tien", "Role": "Data Analyst"},
                        {"Name": "Di", "Role": "Mathematician"},
                        {"Name": "Bang", "Role": "Communicator"}])
staff_df.set_index("Name", inplace=True)

student_df = pd.DataFrame([{"Name": "Tien", "School": "Stylist"},
                          {"Name": "Tram", "School": "Flourist"},
                          {"Name": "Di", "School": "Artist"}])
student_df.set_index("Name", inplace=True)

In [57]:
staff_df

               Role
Name
Tien   Data Analyst
Di    Mathematician
Bang   Communicator

In [58]:
student_df

        School
Name
Tien   Stylist
Tram  Flourist
Di      Artist

In [59]:
# applying outer join (union) to databases with merge() method
pd.merge(staff_df, student_df, how="outer", left_index=True, right_index=True)

               Role    School
Name
Bang   Communicator       NaN
Di    Mathematician    Artist
Tien   Data Analyst   Stylist
Tram            NaN  Flourist

In [60]:
# applying inner join (intersection) to databases with merge() method
pd.merge(staff_df, student_df, how="inner", left_index=True, right_index=True)

               Role   School
Name
Tien   Data Analyst  Stylist
Di    Mathematician   Artist

In [61]:
pd.merge(staff_df, student_df, how="left", left_index=True, right_index=True)

               Role   School
Name
Tien   Data Analyst  Stylist
Di    Mathematician   Artist
Bang   Communicator      NaN

In [62]:
pd.merge(staff_df, student_df, how="right", left_index=True, right_index=True)

               Role    School
Name
Tien   Data Analyst   Stylist
Tram            NaN  Flourist
Di    Mathematician    Artist

In [63]:
# Remove index of the 2 dataframes
staff_df = staff_df.reset_index()
student_df = student_df.reset_index()

# We can use the keyword "on" to specify a column that both dataframe has as the joining column.
pd.merge(staff_df, student_df, how="right", on="Name")

   Name           Role    School
0  Tien   Data Analyst   Stylist
1  Tram            NaN  Flourist
2    Di  Mathematician    Artist

In [64]:
staff_location = ["company", "business", "factory"]
staff_df["Location"] = staff_location

student_address = ["house1", "house22", "house333"]
student_df["Location"] = student_address

In [65]:
# We can use left and right joining to prioritize the data that we need.
# => the _x is data from the left Dataframe, the _y is data from the right Dataframe
pd.merge(staff_df, student_df, how="left", on="Name")

   Name           Role Location_x   School Location_y
0  Tien   Data Analyst    company  Stylist     house1
1    Di  Mathematician   business   Artist   house333
2  Bang   Communicator    factory      NaN        NaN

In [66]:
# We can also use the multi-indexing method which allows us to use multiple columns from dfs to be the joining columns
staff_df.insert(1, "Last Name", ["Phan", "Trinh", "Tran"], True)
student_df.insert(1, "Last Name", ["Phan", "Dao", "Pham"], True)

In [67]:
staff_df.rename(columns={"Name":"First Name"}, inplace=True)
student_df.rename(columns={"Name":"First Name"}, inplace=True)

In [68]:
# Multi-joining
pd.merge(staff_df, student_df, how="inner", on=["First Name", "Last Name"])

  First Name Last Name          Role Location_x   School Location_y
0       Tien      Phan  Data Analyst    company  Stylist     house1

In [75]:
# Besides joing horizontally with merge() function, we can also
# join dfs vertically by concatenating data from different dfs
# together => piling
df1 = pd.DataFrame([{"Number": 1}, {"Number": 2}, {"Number": 3}])
df2 = pd.DataFrame([{"Number": 4}, {"Number": 5}, {"Number": 6}])
frames = [df1, df2]
pd.concat(frames, keys=["number1", "number2"])
# W can also use the keys keyword to clarify the concatenation.

           Number
number1 0       1
        1       2
        2       3
number2 0       4
        1       5
        2       6

# Pandas Idioms

In [3]:
# The logic behind when trying to import a csv file into analysis
# is to use these line of code as it will print the current working
# directory along with all the files in it.
import os

cwd = os.getcwd()  # Get the current working directory (cwd)
files = os.listdir(cwd)  # Get all the files in that directory
print("Files in %r: %s" % (cwd, files))

Files in 'C:\\Users\\AD\\Desktop\\Introduction to Data Science in Python': ['.ipynb_checkpoints', 'census.csv', 'Week 1 - Python and Numpy.ipynb', 'Week 2 - Pandas.ipynb', 'Week 3 - More Data Processing with Pandas.ipynb']

In [4]:
# Then based on the provided cwd, access and read the csv file easily
df = pd.read_csv("C:\\Users\\AD\\Desktop\\Introduction to Data Science in Python/census.csv")

In [5]:
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [6]:
# Method chaining: every method on an object returns a reference to that object
# => u can condense many different operations on a df.

# The task here is to pull out the city name and state name as multiple index with summary level == 50
# 1ST Way: do this step by step normally
df_task1 = df[df["SUMLEV"] == 50]
df_task1.rename(columns={"STNAME": "State Name", "CTYNAME": "City Name"}, inplace=True)

C:\Users\AD\AppData\Local\Temp\ipykernel_10860\1424655656.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_task1.rename(columns={"STNAME": "State Name", "CTYNAME": "City Name"}, inplace=True)

In [7]:
df_task1.set_index(["State Name", "City Name"], inplace=True)
df_task1

                              SUMLEV  REGION  DIVISION  STATE  COUNTY  \
State Name City Name
Alabama    Autauga County         50       3         6      1       1
           Baldwin County         50       3         6      1       3
           Barbour County         50       3         6      1       5
           Bibb County            50       3         6      1       7
           Blount County          50       3         6      1       9
...                              ...     ...       ...    ...     ...
Wyoming    Sweetwater County      50       4         8     56      37
           Teton County           50       4         8     56      39
           Uinta County           50       4         8     56      41
           Washakie County        50       4         8     56      43
           Weston County          50       4         8     56      45

                              CENSUS2010POP  ESTIMATESBASE2010  \
State Name City Name
Alabama    Autauga County             54571              54571
           Baldwin County            182265             182265
           Barbour County             27457              27457
           Bibb County                22915              22919
           Blount County              57322              57322
...                                     ...                ...
Wyoming    Sweetwater County          43806              43806
           Teton County               21294              21294
           Uinta County               21118              21118
           Washakie County             8533               8533
           Weston County               7208               7208

                              POPESTIMATE2010  POPESTIMATE2011  \
State Name City Name
Alabama    Autauga County               54660            55253
           Baldwin County              183193           186659
           Barbour County               27341            27226
           Bibb County                  22861            22733
           Blount County                57373            57711
...                                       ...              ...
Wyoming    Sweetwater County            43593            44041
           Teton County                 21297            21482
           Uinta County                 21102            20912
           Washakie County               8545             8469
           Weston County                 7181             7114

                              POPESTIMATE2012  ...  RDOMESTICMIG2011  \
State Name City Name                           ...
Alabama    Autauga County               55175  ...          7.242091
           Baldwin County              190396  ...         14.832960
           Barbour County               27159  ...         -4.728132
           Bibb County                  22642  ...         -5.527043
           Blount County                57776  ...          1.807375
...                                       ...  ...               ...
Wyoming    Sweetwater County            45104  ...          1.072643
           Teton County                 21697  ...         -1.589565
           Uinta County                 20989  ...        -17.755986
           Washakie County               8443  ...        -11.637475
           Weston County                 7065  ...        -11.752361

                              RDOMESTICMIG2012  RDOMESTICMIG2013  \
State Name City Name
Alabama    Autauga County            -2.915927         -3.012349
           Baldwin County            17.647293         21.845705
           Barbour County            -2.500690         -7.056824
           Bibb County               -5.068871         -6.201001
           Blount County             -1.177622         -1.748766
...                                        ...               ...
Wyoming    Sweetwater County         16.243199         -5.339774
           Teton County               0.972695         19.525929
           Uinta County              -4.916350         -6.902954
           Washakie County           -0.827815         -2.013502
           Weston County             -8.040059         12.372583

                              RDOMESTICMIG2014  RDOMESTICMIG2015  RNETMIG2011  \
State Name City Name
Alabama    Autauga County             2.265971         -2.530799     7.606016
           Baldwin County            19.243287         17.197872    15.844176
           Barbour County            -3.904217        -10.543299    -4.874741
           Bibb County               -0.177537          0.177258    -5.088389
           Blount County             -2.062535         -1.369970     1.859511
...                                        ...               ...          ...
Wyoming    Sweetwater County        -14.252889        -14.248864     1.255221
           Teton County              14.143021         -0.564849     0.654527
           Uinta County             -14.215862        -12.127022   -18.136812
           Washakie County          -17.781491          1.682288   -11.990126
           Weston County              1.533635          6.935294   -12.032179

                              RNETMIG2012  RNETMIG2013  RNETMIG2014  \
State Name City Name
Alabama    Autauga County       -2.626146    -2.722002     2.592270
           Baldwin County       18.559627    22.727626    20.317142
           Barbour County       -2.758113    -7.167664    -3.978583
           Bibb County          -4.363636    -5.403729     0.754533
           Blount County        -0.848580    -1.402476    -1.577232
...                                   ...          ...          ...
Wyoming    Sweetwater County    16.243199    -5.295460   -14.075283
           Teton County          2.408578    21.160658    16.308671
           Uinta County         -5.536861    -7.521840   -14.740608
           Washakie County      -1.182592    -2.250385   -18.020168
           Weston County        -8.040059    12.372583     1.533635

                              RNETMIG2015
State Name City Name
Alabama    Autauga County       -2.187333
           Baldwin County       18.293499
           Barbour County      -10.543299
           Bibb County           1.107861
           Blount County        -0.884411
...                                   ...
Wyoming    Sweetwater County   -14.070195
           Teton County          1.520747
           Uinta County        -12.606351
           Washakie County       1.441961
           Weston County         6.935294

[3142 rows x 98 columns]

In [8]:
# 2ND way: use the chaining method
(df.where(df["SUMLEV"]==50)
    .dropna()
    .set_index(["STNAME", "CTYNAME"])
    .rename(columns={"ESTIMATESBASED2010": "Estimates Base 2010"}))

                           SUMLEV  REGION  DIVISION  STATE  COUNTY  \
STNAME  CTYNAME
Alabama Autauga County       50.0     3.0       6.0    1.0     1.0
        Baldwin County       50.0     3.0       6.0    1.0     3.0
        Barbour County       50.0     3.0       6.0    1.0     5.0
        Bibb County          50.0     3.0       6.0    1.0     7.0
        Blount County        50.0     3.0       6.0    1.0     9.0
...                           ...     ...       ...    ...     ...
Wyoming Sweetwater County    50.0     4.0       8.0   56.0    37.0
        Teton County         50.0     4.0       8.0   56.0    39.0
        Uinta County         50.0     4.0       8.0   56.0    41.0
        Washakie County      50.0     4.0       8.0   56.0    43.0
        Weston County        50.0     4.0       8.0   56.0    45.0

                           CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  \
STNAME  CTYNAME
Alabama Autauga County           54571.0            54571.0          54660.0
        Baldwin County          182265.0           182265.0         183193.0
        Barbour County           27457.0            27457.0          27341.0
        Bibb County              22915.0            22919.0          22861.0
        Blount County            57322.0            57322.0          57373.0
...                                  ...                ...              ...
Wyoming Sweetwater County        43806.0            43806.0          43593.0
        Teton County             21294.0            21294.0          21297.0
        Uinta County             21118.0            21118.0          21102.0
        Washakie County           8533.0             8533.0           8545.0
        Weston County             7208.0             7208.0           7181.0

                           POPESTIMATE2011  POPESTIMATE2012  ...  \
STNAME  CTYNAME                                              ...
Alabama Autauga County             55253.0          55175.0  ...
        Baldwin County            186659.0         190396.0  ...
        Barbour County             27226.0          27159.0  ...
        Bibb County                22733.0          22642.0  ...
        Blount County              57711.0          57776.0  ...
...                                    ...              ...  ...
Wyoming Sweetwater County          44041.0          45104.0  ...
        Teton County               21482.0          21697.0  ...
        Uinta County               20912.0          20989.0  ...
        Washakie County             8469.0           8443.0  ...
        Weston County               7114.0           7065.0  ...

                           RDOMESTICMIG2011  RDOMESTICMIG2012  \
STNAME  CTYNAME
Alabama Autauga County             7.242091         -2.915927
        Baldwin County            14.832960         17.647293
        Barbour County            -4.728132         -2.500690
        Bibb County               -5.527043         -5.068871
        Blount County              1.807375         -1.177622
...                                     ...               ...
Wyoming Sweetwater County          1.072643         16.243199
        Teton County              -1.589565          0.972695
        Uinta County             -17.755986         -4.916350
        Washakie County          -11.637475         -0.827815
        Weston County            -11.752361         -8.040059

                           RDOMESTICMIG2013  RDOMESTICMIG2014  \
STNAME  CTYNAME
Alabama Autauga County            -3.012349          2.265971
        Baldwin County            21.845705         19.243287
        Barbour County            -7.056824         -3.904217
        Bibb County               -6.201001         -0.177537
        Blount County             -1.748766         -2.062535
...                                     ...               ...
Wyoming Sweetwater County         -5.339774        -14.252889
        Teton County              19.525929         14.143021
        Uinta County              -6.902954        -14.215862
        Washakie County           -2.013502        -17.781491
        Weston County             12.372583          1.533635

                           RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  \
STNAME  CTYNAME
Alabama Autauga County            -2.530799     7.606016    -2.626146
        Baldwin County            17.197872    15.844176    18.559627
        Barbour County           -10.543299    -4.874741    -2.758113
        Bibb County                0.177258    -5.088389    -4.363636
        Blount County             -1.369970     1.859511    -0.848580
...                                     ...          ...          ...
Wyoming Sweetwater County        -14.248864     1.255221    16.243199
        Teton County              -0.564849     0.654527     2.408578
        Uinta County             -12.127022   -18.136812    -5.536861
        Washakie County            1.682288   -11.990126    -1.182592
        Weston County              6.935294   -12.032179    -8.040059

                           RNETMIG2013  RNETMIG2014  RNETMIG2015
STNAME  CTYNAME
Alabama Autauga County       -2.722002     2.592270    -2.187333
        Baldwin County       22.727626    20.317142    18.293499
        Barbour County       -7.167664    -3.978583   -10.543299
        Bibb County          -5.403729     0.754533     1.107861
        Blount County        -1.402476    -1.577232    -0.884411
...                                ...          ...          ...
Wyoming Sweetwater County    -5.295460   -14.075283   -14.070195
        Teton County         21.160658    16.308671     1.520747
        Uinta County         -7.521840   -14.740608   -12.606351
        Washakie County      -2.250385   -18.020168     1.441961
        Weston County        12.372583     1.533635     6.935294

[3142 rows x 98 columns]

In the 2 path of processing data, the 1st way of taking step by step is much faster and easy to understand. The 2nd way would be cleaner and succinct but it has a time trade-off compared with the 1st method.

In [9]:
# If in Python, we have the map() function to apply a specific function passed into map() to each iterative of the whole list
# In Pandas, we also have the applymap() function: provide function that acts on each cell of the df => return a set with cells of df

# The task here is to create a maximum and a minimum of population estimate column in the df through many years
# we will use the pandas built-in function which is min_max()
import re
mylist = df.columns
pattern = re.compile('^POPESTIMATE[0-9]{4}')
newlist = list(filter(pattern.match, mylist))
newlist

['POPESTIMATE2010',
 'POPESTIMATE2011',
 'POPESTIMATE2012',
 'POPESTIMATE2013',
 'POPESTIMATE2014',
 'POPESTIMATE2015']

In [10]:
# Create the function
def min_max(row):
    data = row[['POPESTIMATE2010',
                 'POPESTIMATE2011',
                 'POPESTIMATE2012',
                 'POPESTIMATE2013',
                 'POPESTIMATE2014',
                 'POPESTIMATE2015']]
#   return pd.Series({"min": np.min(data), "max": np.max(data)})
    row['max'] = np.max(data)
    row["min"] = np.min(data)
    return row

In [11]:
# Use the applymap which takes the function and the axis on which to operate as parameter
df.apply(min_max, axis="columns").head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,max,min
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594,4858979,4785161
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333,55347,54660
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499,203709,183193
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299,27341,26489
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861,22861,22512

In [16]:
# An easier approach with the use of lambda
rows=['POPESTIMATE2010',
 'POPESTIMATE2011',
 'POPESTIMATE2012',
 'POPESTIMATE2013',
 'POPESTIMATE2014',
 'POPESTIMATE2015']
df.apply(lambda x: np.max(x[rows]), axis=1)

0       4858979
1         55347
2        203709
3         27341
4         22861
         ...
3188      45162
3189      23125
3190      21102
3191       8545
3192       7234
Length: 3193, dtype: int64

In [13]:
df.apply(lambda y: np.min(y[rows]), axis=1).head()

0    4785161
1      54660
2     183193
3      26489
4      22512
dtype: int64

A lambda is just a function with no name, it can take a single parameter x and return a single value y.

Use apply() function when you wanted to update every row in pandas DataFrame by calling a custom function. In order to apply a function to every row, you should use axis=1 param to apply().

# Group by

A groupby operation involves some combination of splitting the object, applying a function, and combining the results. This can be used to group large amounts of data and compute operations on these groups. In pandas, this is referred to as the split-apply-combine pattern

## Splitting

In [26]:
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [27]:
# first way: use the traditional extracting data and doing calculations based on conditionl check
for state in df['STNAME'].unique():
    avg = np.average(df.where(df['STNAME']==state).dropna()['CENSUS2010POP'])
    print("Counties in state", state, "have an average population of",avg)

Counties in state Alabama have an average population of 140580.4705882353
Counties in state Alaska have an average population of 47348.73333333333
Counties in state Arizona have an average population of 799002.125
Counties in state Arkansas have an average population of 76734.68421052632
Counties in state California have an average population of 1262845.9661016949
Counties in state Colorado have an average population of 154744.4923076923
Counties in state Connecticut have an average population of 794243.7777777778
Counties in state Delaware have an average population of 448967.0
Counties in state District of Columbia have an average population of 601723.0
Counties in state Florida have an average population of 552979.7058823529
Counties in state Georgia have an average population of 121095.6625
Counties in state Hawaii have an average population of 453433.6666666667
Counties in state Idaho have an average population of 69670.3111111111
Counties in state Illinois have an average population of 249138.4854368932
Counties in state Indiana have an average population of 139436.60215053763
Counties in state Iowa have an average population of 60927.1
Counties in state Kansas have an average population of 53832.41509433962
Counties in state Kentucky have an average population of 71725.07438016529
Counties in state Louisiana have an average population of 139488.36923076923
Counties in state Maine have an average population of 156277.76470588235
Counties in state Maryland have an average population of 461884.16
Counties in state Massachusetts have an average population of 873017.2
Counties in state Michigan have an average population of 235324.7619047619
Counties in state Minnesota have an average population of 120543.75
Counties in state Mississippi have an average population of 71501.13253012048
Counties in state Missouri have an average population of 103257.36206896552
Counties in state Montana have an average population of 34716.31578947369
Counties in state Nebraska have an average population of 38858.31914893617
Counties in state Nevada have an average population of 300061.22222222225
Counties in state New Hampshire have an average population of 239358.18181818182
Counties in state New Jersey have an average population of 799263.0909090909
Counties in state New Mexico have an average population of 121128.17647058824
Counties in state New York have an average population of 615177.8412698413
Counties in state North Carolina have an average population of 188821.44554455444
Counties in state North Dakota have an average population of 24910.777777777777
Counties in state Ohio have an average population of 259247.2808988764
Counties in state Oklahoma have an average population of 96188.48717948717
Counties in state Oregon have an average population of 207085.0810810811
Counties in state Pennsylvania have an average population of 373599.3823529412
Counties in state Rhode Island have an average population of 350855.6666666667
Counties in state South Carolina have an average population of 196824.0
Counties in state South Dakota have an average population of 24303.880597014926
Counties in state Tennessee have an average population of 132210.52083333334
Counties in state Texas have an average population of 197220.0862745098
Counties in state Utah have an average population of 184259.0
Counties in state Vermont have an average population of 83432.13333333333
Counties in state Virginia have an average population of 119371.83582089552
Counties in state Washington have an average population of 336227.0
Counties in state West Virginia have an average population of 66178.35714285714
Counties in state Wisconsin have an average population of 155807.83561643836
Counties in state Wyoming have an average population of 46968.833333333336

In [29]:
# the second way: using groupby() function
for group, frame in df.groupby('STNAME'):
    print("The average concensus estimate of", group, "is",
         np.average(frame['CENSUS2010POP']))

The average concensus estimate of Alabama is 140580.4705882353
The average concensus estimate of Alaska is 47348.73333333333
The average concensus estimate of Arizona is 799002.125
The average concensus estimate of Arkansas is 76734.68421052632
The average concensus estimate of California is 1262845.9661016949
The average concensus estimate of Colorado is 154744.4923076923
The average concensus estimate of Connecticut is 794243.7777777778
The average concensus estimate of Delaware is 448967.0
The average concensus estimate of District of Columbia is 601723.0
The average concensus estimate of Florida is 552979.7058823529
The average concensus estimate of Georgia is 121095.6625
The average concensus estimate of Hawaii is 453433.6666666667
The average concensus estimate of Idaho is 69670.3111111111
The average concensus estimate of Illinois is 249138.4854368932
The average concensus estimate of Indiana is 139436.60215053763
The average concensus estimate of Iowa is 60927.1
The average concensus estimate of Kansas is 53832.41509433962
The average concensus estimate of Kentucky is 71725.07438016529
The average concensus estimate of Louisiana is 139488.36923076923
The average concensus estimate of Maine is 156277.76470588235
The average concensus estimate of Maryland is 461884.16
The average concensus estimate of Massachusetts is 873017.2
The average concensus estimate of Michigan is 235324.7619047619
The average concensus estimate of Minnesota is 120543.75
The average concensus estimate of Mississippi is 71501.13253012048
The average concensus estimate of Missouri is 103257.36206896552
The average concensus estimate of Montana is 34716.31578947369
The average concensus estimate of Nebraska is 38858.31914893617
The average concensus estimate of Nevada is 300061.22222222225
The average concensus estimate of New Hampshire is 239358.18181818182
The average concensus estimate of New Jersey is 799263.0909090909
The average concensus estimate of New Mexico is 121128.17647058824
The average concensus estimate of New York is 615177.8412698413
The average concensus estimate of North Carolina is 188821.44554455444
The average concensus estimate of North Dakota is 24910.777777777777
The average concensus estimate of Ohio is 259247.2808988764
The average concensus estimate of Oklahoma is 96188.48717948717
The average concensus estimate of Oregon is 207085.0810810811
The average concensus estimate of Pennsylvania is 373599.3823529412
The average concensus estimate of Rhode Island is 350855.6666666667
The average concensus estimate of South Carolina is 196824.0
The average concensus estimate of South Dakota is 24303.880597014926
The average concensus estimate of Tennessee is 132210.52083333334
The average concensus estimate of Texas is 197220.0862745098
The average concensus estimate of Utah is 184259.0
The average concensus estimate of Vermont is 83432.13333333333
The average concensus estimate of Virginia is 119371.83582089552
The average concensus estimate of Washington is 336227.0
The average concensus estimate of West Virginia is 66178.35714285714
The average concensus estimate of Wisconsin is 155807.83561643836
The average concensus estimate of Wyoming is 46968.833333333336

In [54]:
# Playing with groupby() function by doing some fabricated splitting and data calculations
df.set_index('STNAME', inplace=True)

KeyError: "None of ['STNAME'] are in the columns"

In [52]:
def set_batch_number(state):
    if state[0]<"M":
        return 0
    elif state[0]<"Q":
        return 1
    else:
        return 2

for group, frame in df.groupby(set_batch_number):
    print("There are", str(len(frame)), "records in group", str(group), "for processing.")

There are 1196 records in group 0 for processing.
There are 1154 records in group 1 for processing.
There are 843 records in group 2 for processing.

In the above case, we don't have to pass in the groupby function any column name, so this function will automatically use the index of the dataframe to group

In [ ]:
# What if we want to group a dataframe by 2 or more columns.
# The best practice is to promote the df into multi-index df
# , then use the groupby() function

In [7]:
df2 = df.copy()

In [8]:
df2.set_index(["CTYNAME","CENSUS2010POP"], inplace=True)
# When we have a multi-index, we need to pass in the levels we want to group by
for group, frame in df2.groupby(level=(0,1)):
    print(group)

('Abbeville County', 25417)
('Acadia Parish', 61773)
('Accomack County', 33164)
('Ada County', 392365)
('Adair County', 7682)
('Adair County', 18656)
('Adair County', 22683)
('Adair County', 25607)
('Adams County', 2343)
('Adams County', 3976)
('Adams County', 4029)
('Adams County', 18728)
('Adams County', 20875)
('Adams County', 28550)
('Adams County', 31364)
('Adams County', 32297)
('Adams County', 34387)
('Adams County', 67103)
('Adams County', 101407)
('Adams County', 441603)
('Addison County', 36821)
('Aiken County', 160099)
('Aitkin County', 16202)
('Alabama', 4779736)
('Alachua County', 247336)
('Alamance County', 151131)
('Alameda County', 1510271)
('Alamosa County', 15445)
('Alaska', 710231)
('Albany County', 36299)
('Albany County', 304204)
('Albemarle County', 98970)
('Alcona County', 10942)
('Alcorn County', 37057)
('Aleutians East Borough', 3141)
('Aleutians West Census Area', 5561)
('Alexander County', 8238)
('Alexander County', 37198)
('Alexandria city', 139966)
('Alfalfa County', 5642)
('Alger County', 9601)
('Allamakee County', 14330)
('Allegan County', 111408)
('Allegany County', 48946)
('Allegany County', 75087)
('Alleghany County', 11155)
('Alleghany County', 16250)
('Allegheny County', 1223348)
('Allen County', 13371)
('Allen County', 19956)
('Allen County', 106331)
('Allen County', 355329)
('Allen Parish', 25764)
('Allendale County', 10419)
('Alpena County', 29598)
('Alpine County', 1175)
('Amador County', 38091)
('Amelia County', 12690)
('Amherst County', 32353)
('Amite County', 13131)
('Anchorage Municipality', 291826)
('Anderson County', 8102)
('Anderson County', 21421)
('Anderson County', 58458)
('Anderson County', 75129)
('Anderson County', 187126)
('Andrew County', 17291)
('Andrews County', 14786)
('Androscoggin County', 107702)
('Angelina County', 86771)
('Anne Arundel County', 537656)
('Anoka County', 330844)
('Anson County', 26948)
('Antelope County', 6685)
('Antrim County', 23580)
('Apache County', 71518)
('Appanoose County', 12887)
('Appling County', 18236)
('Appomattox County', 14973)
('Aransas County', 23158)
('Arapahoe County', 572003)
('Archer County', 9054)
('Archuleta County', 12084)
('Arenac County', 15899)
('Arizona', 6392017)
('Arkansas', 2915918)
('Arkansas County', 19019)
('Arlington County', 207627)
('Armstrong County', 1901)
('Armstrong County', 68941)
('Aroostook County', 71870)
('Arthur County', 460)
('Ascension Parish', 107215)
('Ashe County', 27281)
('Ashland County', 16157)
('Ashland County', 53139)
('Ashley County', 21853)
('Ashtabula County', 101497)
('Asotin County', 21623)
('Assumption Parish', 23421)
('Atascosa County', 44911)
('Atchison County', 5685)
('Atchison County', 16924)
('Athens County', 64757)
('Atkinson County', 8375)
('Atlantic County', 274549)
('Atoka County', 14182)
('Attala County', 19564)
('Audrain County', 25529)
('Audubon County', 6119)
('Auglaize County', 45949)
('Augusta County', 73750)
('Aurora County', 2710)
('Austin County', 28417)
('Autauga County', 54571)
('Avery County', 17797)
('Avoyelles Parish', 42073)
('Baca County', 3788)
('Bacon County', 11096)
('Bailey County', 7165)
('Baker County', 3451)
('Baker County', 16134)
('Baker County', 27115)
('Baldwin County', 45720)
('Baldwin County', 182265)
('Ballard County', 8249)
('Baltimore County', 805029)
('Baltimore city', 620961)
('Bamberg County', 15987)
('Bandera County', 20485)
('Banks County', 18395)
('Banner County', 690)
('Bannock County', 82839)
('Baraga County', 8860)
('Barber County', 4861)
('Barbour County', 16589)
('Barbour County', 27457)
('Barnes County', 11066)
('Barnstable County', 215888)
('Barnwell County', 22621)
('Barren County', 42173)
('Barron County', 45870)
('Barrow County', 69367)
('Barry County', 35597)
('Barry County', 59173)
('Bartholomew County', 76794)
('Barton County', 12402)
('Barton County', 27674)
('Bartow County', 100157)
('Bastrop County', 74171)
('Bates County', 17049)
('Bath County', 4731)
('Bath County', 11591)
('Baxter County', 41513)
('Bay County', 107771)
('Bay County', 168852)
('Bayfield County', 15014)
('Baylor County', 3726)
('Beadle County', 17398)
('Bear Lake County', 5986)
('Beaufort County', 47759)
('Beaufort County', 162233)
('Beauregard Parish', 35654)
('Beaver County', 5636)
('Beaver County', 6629)
('Beaver County', 170539)
('Beaverhead County', 9246)
('Becker County', 32504)
('Beckham County', 22119)
('Bedford County', 45058)
('Bedford County', 49762)
('Bedford County', 68676)
('Bee County', 31861)
('Belknap County', 60088)
('Bell County', 28691)
('Bell County', 310235)
('Belmont County', 70400)
('Beltrami County', 44442)
('Ben Hill County', 17634)
('Benewah County', 9285)
('Bennett County', 3431)
('Bennington County', 37125)
('Benson County', 6660)
('Bent County', 6499)
('Benton County', 8729)
('Benton County', 8854)
('Benton County', 16489)
('Benton County', 19056)
('Benton County', 26076)
('Benton County', 38451)
('Benton County', 85579)
('Benton County', 175177)
('Benton County', 221339)
('Benzie County', 17525)
('Bergen County', 905116)
('Berkeley County', 104169)
('Berkeley County', 177843)
('Berks County', 411442)
('Berkshire County', 131219)
('Bernalillo County', 662564)
('Berrien County', 19286)
('Berrien County', 156813)
('Bertie County', 21282)
('Bethel Census Area', 17013)
('Bexar County', 1714773)
('Bibb County', 22915)
('Bibb County', 155547)
('Bienville Parish', 14353)
('Big Horn County', 11668)
('Big Horn County', 12865)
('Big Stone County', 5269)
('Billings County', 783)
('Bingham County', 45607)
('Black Hawk County', 131090)
('Blackford County', 12766)
('Bladen County', 35190)
('Blaine County', 478)
('Blaine County', 6491)
('Blaine County', 11943)
('Blaine County', 21376)
('Blair County', 127089)
('Blanco County', 10497)
('Bland County', 6824)
('Bleckley County', 13063)
('Bledsoe County', 12876)
('Blount County', 57322)
('Blount County', 123010)
('Blue Earth County', 64013)
('Boise County', 7028)
('Bolivar County', 34145)
('Bollinger County', 12363)
('Bon Homme County', 7070)
('Bond County', 17768)
('Bonner County', 40877)
('Bonneville County', 104234)
('Boone County', 5505)
('Boone County', 24629)
('Boone County', 26306)
('Boone County', 36903)
('Boone County', 54165)
('Boone County', 56640)
('Boone County', 118811)
('Boone County', 162642)
('Borden County', 641)
('Bosque County', 18212)
('Bossier Parish', 116979)
('Botetourt County', 33148)
('Bottineau County', 6429)
('Boulder County', 294567)
('Boundary County', 10972)
('Bourbon County', 15173)
('Bourbon County', 19985)
('Bowie County', 92565)
('Bowman County', 3151)
('Box Butte County', 11308)
('Box Elder County', 49975)
('Boyd County', 2099)
('Boyd County', 49542)
('Boyle County', 28432)
('Bracken County', 8488)
('Bradford County', 28520)
('Bradford County', 62622)
('Bradley County', 11508)
('Bradley County', 98963)
('Branch County', 45248)
('Brantley County', 18411)
('Braxton County', 14523)
('Brazoria County', 313166)
('Brazos County', 194851)
('Breathitt County', 13878)
('Breckinridge County', 20059)
('Bremer County', 24276)
('Brevard County', 543376)
('Brewster County', 9232)
('Briscoe County', 1637)
('Bristol Bay Borough', 997)
('Bristol County', 49875)
('Bristol County', 548285)
('Bristol city', 17835)
('Broadwater County', 5612)
('Bronx County', 1385108)
('Brooke County', 24069)
('Brookings County', 31965)
('Brooks County', 7223)
('Brooks County', 16243)
('Broome County', 200600)
('Broomfield County', 55889)
('Broward County', 1748066)
('Brown County', 3145)
('Brown County', 6937)
('Brown County', 9984)
('Brown County', 15242)
('Brown County', 25893)
('Brown County', 36531)
('Brown County', 38106)
('Brown County', 44846)
('Brown County', 248007)
('Brule County', 5255)
('Brunswick County', 17434)
('Brunswick County', 107431)
('Bryan County', 30233)
('Bryan County', 42416)
('Buchanan County', 20958)
('Buchanan County', 24098)
('Buchanan County', 89201)
('Buckingham County', 17146)
('Bucks County', 625249)
('Buena Vista County', 20260)
('Buena Vista city', 6650)
('Buffalo County', 1912)
('Buffalo County', 13587)
('Buffalo County', 46102)
('Bullitt County', 74319)
('Bulloch County', 70217)
('Bullock County', 10914)
('Buncombe County', 238318)
('Bureau County', 34978)
('Burke County', 1968)
('Burke County', 23316)
('Burke County', 90912)
('Burleigh County', 81308)
('Burleson County', 17187)
('Burlington County', 448734)
('Burnet County', 42750)
('Burnett County', 15457)
('Burt County', 6858)
('Butler County', 8395)
('Butler County', 12690)
('Butler County', 14867)
('Butler County', 20947)
('Butler County', 42794)
('Butler County', 65880)
('Butler County', 183862)
('Butler County', 368130)
('Butte County', 2891)
('Butte County', 10110)
('Butte County', 220000)
('Butts County', 23655)
('Cabarrus County', 178011)
('Cabell County', 96319)
('Cache County', 112656)
('Caddo County', 29600)
('Caddo Parish', 254969)
('Calaveras County', 45578)
('Calcasieu Parish', 192768)
('Caldwell County', 9424)
('Caldwell County', 12984)
('Caldwell County', 38066)
('Caldwell County', 83029)
('Caldwell Parish', 10132)
('Caledonia County', 31227)
('Calhoun County', 5089)
('Calhoun County', 5368)
('Calhoun County', 6694)
('Calhoun County', 7627)
('Calhoun County', 9670)
('Calhoun County', 14625)
('Calhoun County', 14962)
('Calhoun County', 15175)
('Calhoun County', 21381)
('Calhoun County', 118572)
('Calhoun County', 136146)
('California', 37253956)
('Callahan County', 13544)
('Callaway County', 44332)
('Calloway County', 37191)
('Calumet County', 48971)
('Calvert County', 88737)
('Camas County', 1117)
('Cambria County', 143679)
('Camden County', 9980)
('Camden County', 44002)
('Camden County', 50513)
('Camden County', 513657)
('Cameron County', 5085)
('Cameron County', 406220)
('Cameron Parish', 6839)
('Camp County', 12401)
('Campbell County', 1466)
('Campbell County', 40716)
('Campbell County', 46133)
('Campbell County', 54842)
('Campbell County', 90336)
('Canadian County', 115541)
('Candler County', 10998)
('Cannon County', 13801)
('Canyon County', 188923)
('Cape Girardeau County', 75674)
('Cape May County', 97265)
('Carbon County', 10078)
('Carbon County', 15885)
('Carbon County', 21403)
('Carbon County', 65249)
('Caribou County', 6963)
('Carlisle County', 5104)
('Carlton County', 35386)
('Caroline County', 28545)
('Caroline County', 33066)
('Carroll County', 9295)
('Carroll County', 10597)
('Carroll County', 10811)
('Carroll County', 15387)
('Carroll County', 20155)
('Carroll County', 20816)
('Carroll County', 27446)
('Carroll County', 28522)
('Carroll County', 28836)
('Carroll County', 30042)
('Carroll County', 47818)
('Carroll County', 110527)
('Carroll County', 167134)
('Carson City', 55274)
('Carson County', 6182)
('Carter County', 1160)
('Carter County', 6265)
('Carter County', 27720)
('Carter County', 47557)
('Carter County', 57424)
('Carteret County', 66469)
('Carver County', 91042)
('Cascade County', 81327)
('Casey County', 15955)
('Cass County', 13642)
('Cass County', 13956)
('Cass County', 25241)
('Cass County', 28567)
('Cass County', 30464)
('Cass County', 38966)
('Cass County', 52293)
('Cass County', 99478)
('Cass County', 149778)
('Cassia County', 22952)
('Castro County', 8062)
('Caswell County', 23719)
('Catahoula Parish', 10407)
('Catawba County', 154358)
('Catoosa County', 63942)
('Catron County', 3725)
('Cattaraugus County', 80317)
('Cavalier County', 3993)
('Cayuga County', 80026)
('Cecil County', 101108)
('Cedar County', 8852)
('Cedar County', 13982)
('Cedar County', 18499)
('Centre County', 153990)
('Cerro Gordo County', 44151)
('Chaffee County', 17809)
('Chambers County', 34215)
('Chambers County', 35096)
('Champaign County', 40097)
('Champaign County', 201081)
('Chariton County', 7831)
('Charles City County', 7256)
('Charles County', 146551)
('Charles Mix County', 9129)
('Charleston County', 350209)
('Charlevoix County', 25949)
('Charlotte County', 12586)
('Charlotte County', 159978)
('Charlottesville city', 43475)
('Charlton County', 12171)
('Chase County', 2790)
('Chase County', 3966)
('Chatham County', 63505)
('Chatham County', 265128)
('Chattahoochee County', 11267)
('Chattooga County', 26015)
('Chautauqua County', 3669)
('Chautauqua County', 134905)
('Chaves County', 65645)
('Cheatham County', 39105)
('Cheboygan County', 26152)
('Chelan County', 72453)
('Chemung County', 88830)
('Chenango County', 50477)
('Cherokee County', 12072)
('Cherokee County', 21603)
('Cherokee County', 25989)
('Cherokee County', 27444)
('Cherokee County', 46987)
('Cherokee County', 50845)
('Cherokee County', 55342)
('Cherokee County', 214346)
('Cherry County', 5713)
('Chesapeake city', 222209)
('Cheshire County', 77117)
('Chester County', 17131)
('Chester County', 33140)
('Chester County', 498886)
('Chesterfield County', 46734)
('Chesterfield County', 316236)
('Cheyenne County', 1836)
('Cheyenne County', 2726)
('Cheyenne County', 9998)
('Chickasaw County', 12439)
('Chickasaw County', 17392)
('Chicot County', 11800)
('Childress County', 7041)
('Chilton County', 43643)
('Chippewa County', 12441)
('Chippewa County', 38520)
('Chippewa County', 62415)
('Chisago County', 53887)
('Chittenden County', 156545)
('Choctaw County', 8547)
('Choctaw County', 13859)
('Choctaw County', 15205)
('Chouteau County', 5813)
('Chowan County', 14793)
('Christian County', 34800)
('Christian County', 73955)
('Christian County', 77422)
('Churchill County', 24877)
('Cibola County', 27213)
('Cimarron County', 2475)
('Citrus County', 141236)
('Clackamas County', 375992)
('Claiborne County', 9604)
('Claiborne County', 32213)
('Claiborne Parish', 17195)
('Clallam County', 71404)
('Clare County', 30926)
('Clarendon County', 34971)
('Clarion County', 39988)
('Clark County', 982)
('Clark County', 2215)
('Clark County', 3691)
('Clark County', 7139)
('Clark County', 16335)
('Clark County', 22995)
('Clark County', 34690)
('Clark County', 35613)
('Clark County', 110232)
('Clark County', 138333)
('Clark County', 425363)
('Clark County', 1951269)
('Clarke County', 9286)
('Clarke County', 14034)
('Clarke County', 16732)
('Clarke County', 25833)
('Clarke County', 116714)
('Clatsop County', 37039)
('Clay County', 3183)
('Clay County', 6542)
('Clay County', 7861)
('Clay County', 8535)
('Clay County', 9386)
('Clay County', 10587)
('Clay County', 10752)
('Clay County', 13815)
('Clay County', 13864)
('Clay County', 13932)
('Clay County', 16083)
('Clay County', 16667)
('Clay County', 20634)
('Clay County', 21730)
('Clay County', 26890)
('Clay County', 58999)
('Clay County', 190865)
('Clay County', 221939)
('Clayton County', 18129)
('Clayton County', 259424)
('Clear Creek County', 9088)
('Clearfield County', 81642)
('Clearwater County', 8695)
('Clearwater County', 8761)
('Cleburne County', 14972)
('Cleburne County', 25970)
('Clermont County', 197363)
('Cleveland County', 8689)
('Cleveland County', 98078)
('Cleveland County', 255755)
('Clinch County', 6798)
('Clinton County', 10272)
('Clinton County', 20743)
('Clinton County', 33224)
('Clinton County', 37762)
('Clinton County', 39238)
('Clinton County', 42040)
('Clinton County', 49116)
('Clinton County', 75382)
('Clinton County', 82128)
('Cloud County', 9533)
('Coahoma County', 26151)
('Coal County', 5925)
('Cobb County', 688078)
('Cochise County', 131346)
('Cochran County', 3127)
('Cocke County', 35662)
('Coconino County', 134421)
('Codington County', 27227)
('Coffee County', 42356)
('Coffee County', 49948)
('Coffee County', 52796)
('Coffey County', 8601)
('Coke County', 3320)
('Colbert County', 54428)
('Cole County', 75990)
('Coleman County', 8895)
('Coles County', 53873)
('Colfax County', 10515)
('Colfax County', 13750)
('Colleton County', 38892)
('Collier County', 321520)
('Collin County', 782341)
('Collingsworth County', 3057)
('Colonial Heights city', 17411)
('Colorado', 5029196)
('Colorado County', 20874)
('Colquitt County', 45498)
('Columbia County', 4078)
('Columbia County', 24552)
('Columbia County', 49351)
('Columbia County', 56833)
('Columbia County', 63096)
('Columbia County', 67295)
('Columbia County', 67531)
('Columbia County', 124053)
('Columbiana County', 107841)
('Columbus County', 58098)
('Colusa County', 21419)
('Comal County', 108472)
('Comanche County', 1891)
('Comanche County', 13974)
('Comanche County', 124098)
('Concho County', 4087)
('Concordia Parish', 20822)
('Conecuh County', 13228)
('Conejos County', 8256)
('Connecticut', 3574097)
('Contra Costa County', 1049025)
('Converse County', 13833)
('Conway County', 21273)
('Cook County', 5176)
('Cook County', 17212)
('Cook County', 5194675)
('Cooke County', 38437)
('Cooper County', 17601)
('Coos County', 33055)
('Coos County', 63043)
('Coosa County', 11539)
('Copiah County', 29449)
('Corson County', 4050)
('Cortland County', 49336)
('Coryell County', 75388)
('Coshocton County', 36901)
('Costilla County', 3524)
('Cottle County', 1505)
('Cotton County', 6193)
('Cottonwood County', 11687)
('Covington County', 19568)
('Covington County', 37765)
('Covington city', 5961)
('Coweta County', 127317)
('Cowley County', 36311)
('Cowlitz County', 102410)
('Craig County', 5190)
('Craig County', 15029)
('Craighead County', 96443)
('Crane County', 4375)
('Craven County', 103505)
('Crawford County', 10713)
('Crawford County', 12630)
('Crawford County', 14074)
('Crawford County', 16644)
('Crawford County', 17096)
('Crawford County', 19817)
('Crawford County', 24696)
('Crawford County', 39134)
('Crawford County', 43784)
('Crawford County', 61948)
('Crawford County', 88765)
('Creek County', 69967)
('Crenshaw County', 13906)
('Crisp County', 23439)
('Crittenden County', 9315)
('Crittenden County', 50902)
('Crockett County', 3719)
('Crockett County', 14586)
('Crook County', 7083)
('Crook County', 20978)
('Crosby County', 6059)
('Cross County', 17870)
('Crow Wing County', 62500)
('Crowley County', 5823)
('Culberson County', 2398)
('Cullman County', 80406)
('Culpeper County', 46689)
('Cumberland County', 6856)
('Cumberland County', 10052)
('Cumberland County', 11048)
('Cumberland County', 56053)
('Cumberland County', 156898)
('Cumberland County', 235406)
('Cumberland County', 281674)
('Cumberland County', 319431)
('Cuming County', 9139)
('Currituck County', 23547)
('Curry County', 22364)
('Curry County', 48376)
('Custer County', 4255)
('Custer County', 4368)
('Custer County', 8216)
('Custer County', 10939)
('Custer County', 11699)
('Custer County', 27469)
('Cuyahoga County', 1280122)
('Dade County', 7883)
('Dade County', 16633)
('Daggett County', 1059)
('Dakota County', 21006)
('Dakota County', 398552)
('Dale County', 50251)
('Dallam County', 6703)
('Dallas County', 8116)
('Dallas County', 16777)
('Dallas County', 43820)
('Dallas County', 66135)
('Dallas County', 2368139)
('Dane County', 488073)
('Daniels County', 1751)
('Danville city', 43055)
('Dare County', 33920)
('Darke County', 52959)
('Darlington County', 68681)
('Dauphin County', 268100)
('Davidson County', 162878)
('Davidson County', 626681)
('Davie County', 41240)
('Daviess County', 8433)
('Daviess County', 31648)
('Daviess County', 96656)
('Davis County', 8753)
('Davis County', 306479)
('Davison County', 19504)
('Dawes County', 9182)
('Dawson County', 8966)
('Dawson County', 13833)
('Dawson County', 22330)
('Dawson County', 24326)
('Day County', 5710)
('De Baca County', 2022)
('De Soto Parish', 26656)
('De Witt County', 16561)
('DeKalb County', 12892)
('DeKalb County', 18723)
('DeKalb County', 42223)
('DeKalb County', 71109)
('DeKalb County', 105160)
('DeKalb County', 691893)
('DeSoto County', 34862)
('DeSoto County', 161252)
('DeWitt County', 20097)
('Deaf Smith County', 19372)
('Dearborn County', 50047)
('Decatur County', 2961)
('Decatur County', 8457)
('Decatur County', 11757)
('Decatur County', 25740)
('Decatur County', 27842)
('Deer Lodge County', 9298)
('Defiance County', 39037)
('Del Norte County', 28610)
('Delaware', 897934)
('Delaware County', 17764)
('Delaware County', 41487)
('Delaware County', 47980)
('Delaware County', 117671)
('Delaware County', 174214)
('Delaware County', 558979)
('Delta County', 5231)
('Delta County', 30952)
('Delta County', 37069)

('Love County', 9423)
('Loving County', 82)
('Lowndes County', 11299)
('Lowndes County', 59779)
('Lowndes County', 109233)
('Lubbock County', 278831)
('Lucas County', 8898)
('Lucas County', 441815)
('Luce County', 6631)
('Lumpkin County', 29966)
('Luna County', 25095)
('Lunenburg County', 12914)
('Luzerne County', 320918)
('Lycoming County', 116111)
('Lyman County', 3755)
('Lynchburg city', 75568)
('Lynn County', 5915)
('Lyon County', 8314)
('Lyon County', 11581)
('Lyon County', 25857)
('Lyon County', 33690)
('Lyon County', 51980)
('Mackinac County', 11113)
('Macomb County', 840978)
('Macon County', 14740)
('Macon County', 15566)
('Macon County', 21452)
('Macon County', 22248)
('Macon County', 33922)
('Macon County', 110768)
('Macoupin County', 47765)
('Madera County', 150865)
('Madison County', 7691)
('Madison County', 12226)
('Madison County', 13308)
('Madison County', 13664)
('Madison County', 15679)
('Madison County', 15717)
('Madison County', 19224)
('Madison County', 20764)
('Madison County', 28120)
('Madison County', 34876)
('Madison County', 37536)
('Madison County', 43435)
('Madison County', 73442)
('Madison County', 82916)
('Madison County', 95203)
('Madison County', 98294)
('Madison County', 131636)
('Madison County', 269282)
('Madison County', 334811)
('Madison Parish', 12093)
('Magoffin County', 13333)
('Mahaska County', 22381)
('Mahnomen County', 5413)
('Mahoning County', 238823)
('Maine', 1328361)
('Major County', 7527)
('Malheur County', 31313)
('Manassas Park city', 14273)
('Manassas city', 37821)
('Manatee County', 322833)
('Manistee County', 24733)
('Manitowoc County', 81442)
('Marathon County', 134063)
('Marengo County', 21027)
('Maricopa County', 3817117)
('Maries County', 9176)
('Marin County', 252409)
('Marinette County', 41749)
('Marion County', 8742)
('Marion County', 10546)
('Marion County', 12660)
('Marion County', 16653)
('Marion County', 19820)
('Marion County', 27088)
('Marion County', 28237)
('Marion County', 28781)
('Marion County', 30776)
('Marion County', 33062)
('Marion County', 33309)
('Marion County', 39437)
('Marion County', 56418)
('Marion County', 66501)
('Marion County', 315335)
('Marion County', 331298)
('Marion County', 903393)
('Mariposa County', 18251)
('Marlboro County', 28933)
('Marquette County', 15404)
('Marquette County', 67077)
('Marshall County', 4656)
('Marshall County', 9439)
('Marshall County', 10117)
('Marshall County', 12640)
('Marshall County', 15840)
('Marshall County', 30617)
('Marshall County', 31448)
('Marshall County', 33107)
('Marshall County', 37144)
('Marshall County', 40648)
('Marshall County', 47051)
('Marshall County', 93019)
('Martin County', 4799)
('Martin County', 10334)
('Martin County', 12929)
('Martin County', 20840)
('Martin County', 24505)
('Martin County', 146318)
('Martinsville city', 13821)
('Maryland', 5773552)
('Mason County', 4012)
('Mason County', 14666)
('Mason County', 17490)
('Mason County', 27324)
('Mason County', 28705)
('Mason County', 60699)
('Massac County', 15429)
('Massachusetts', 6547629)
('Matagorda County', 36702)
('Matanuska-Susitna Borough', 88995)
('Mathews County', 8978)
('Maui County', 154834)
('Maury County', 80956)
('Maverick County', 54258)
('Mayes County', 41259)
('McClain County', 34506)
('McCone County', 1734)
('McCook County', 5618)
('McCormick County', 10233)
('McCracken County', 65565)
('McCreary County', 18306)
('McCulloch County', 8283)
('McCurtain County', 33151)
('McDonald County', 23083)
('McDonough County', 32612)
('McDowell County', 22113)
('McDowell County', 44996)
('McDuffie County', 21875)
('McHenry County', 5395)
('McHenry County', 308760)
('McIntosh County', 2809)
('McIntosh County', 14333)
('McIntosh County', 20252)
('McKean County', 43450)
('McKenzie County', 6360)
('McKinley County', 71492)
('McLean County', 8962)
('McLean County', 9531)
('McLean County', 169572)
('McLennan County', 234906)
('McLeod County', 36651)
('McMinn County', 52266)
('McMullen County', 707)
('McNairy County', 26075)
('McPherson County', 539)
('McPherson County', 2459)
('McPherson County', 29180)
('Meade County', 4575)
('Meade County', 25434)
('Meade County', 28602)
('Meagher County', 1891)
('Mecklenburg County', 32727)
('Mecklenburg County', 919628)
('Mecosta County', 42798)
('Medina County', 46006)
('Medina County', 172332)
('Meeker County', 23300)
('Meigs County', 11753)
('Meigs County', 23770)
('Mellette County', 2048)
('Menard County', 2242)
('Menard County', 12705)
('Mendocino County', 87841)
('Menifee County', 6306)
('Menominee County', 4232)
('Menominee County', 24029)
('Merced County', 255793)
('Mercer County', 3785)
('Mercer County', 8424)
('Mercer County', 16434)
('Mercer County', 21331)
('Mercer County', 40814)
('Mercer County', 62264)
('Mercer County', 116638)
('Mercer County', 366513)
('Meriwether County', 21992)
('Merrick County', 7845)
('Merrimack County', 146445)
('Mesa County', 146723)
('Metcalfe County', 10099)
('Miami County', 32787)
('Miami County', 36903)
('Miami County', 102506)
('Miami-Dade County', 2496435)
('Michigan', 9883640)
('Middlesex County', 10959)
('Middlesex County', 165676)
('Middlesex County', 809858)
('Middlesex County', 1503085)
('Midland County', 83629)
('Midland County', 136872)
('Mifflin County', 46682)
('Milam County', 24757)
('Millard County', 12503)
('Mille Lacs County', 26097)
('Miller County', 6125)
('Miller County', 24748)
('Miller County', 43462)
('Mills County', 4936)
('Mills County', 15059)
('Milwaukee County', 947735)
('Miner County', 2389)
('Mineral County', 712)
('Mineral County', 4223)
('Mineral County', 4772)
('Mineral County', 28212)
('Mingo County', 26839)
('Minidoka County', 20069)
('Minnehaha County', 169468)
('Minnesota', 5303925)
('Missaukee County', 14849)
('Mississippi', 2967297)
('Mississippi County', 14358)
('Mississippi County', 46480)
('Missoula County', 109299)
('Missouri', 5988927)
('Mitchell County', 6373)
('Mitchell County', 9403)
('Mitchell County', 10776)
('Mitchell County', 15579)
('Mitchell County', 23498)
('Mobile County', 412992)
('Modoc County', 9686)
('Moffat County', 13795)
('Mohave County', 200186)
('Moniteau County', 15607)
('Monmouth County', 630380)
('Mono County', 14202)
('Monona County', 9243)
('Monongalia County', 96189)
('Monroe County', 7970)
('Monroe County', 8149)
('Monroe County', 8840)
('Monroe County', 10963)
('Monroe County', 13502)
('Monroe County', 14642)
('Monroe County', 23068)
('Monroe County', 26424)
('Monroe County', 32957)
('Monroe County', 36989)
('Monroe County', 44519)
('Monroe County', 44673)
('Monroe County', 73090)
('Monroe County', 137974)
('Monroe County', 152021)
('Monroe County', 169842)
('Monroe County', 744344)
('Montague County', 19719)
('Montana', 989415)
('Montcalm County', 63342)
('Monterey County', 415057)
('Montezuma County', 25535)
('Montgomery County', 9123)
('Montgomery County', 9487)
('Montgomery County', 10740)
('Montgomery County', 10925)
('Montgomery County', 12236)
('Montgomery County', 26499)
('Montgomery County', 27798)
('Montgomery County', 30104)
('Montgomery County', 35471)
('Montgomery County', 38124)
('Montgomery County', 50219)
('Montgomery County', 94392)
('Montgomery County', 172331)
('Montgomery County', 229363)
('Montgomery County', 455746)
('Montgomery County', 535153)
('Montgomery County', 799874)
('Montgomery County', 971777)
('Montmorency County', 9765)
('Montour County', 18267)
('Montrose County', 41276)
('Moody County', 6486)
('Moore County', 6362)
('Moore County', 21904)
('Moore County', 88247)
('Mora County', 4881)
('Morehouse Parish', 27979)
('Morgan County', 9469)
('Morgan County', 13923)
('Morgan County', 15054)
('Morgan County', 17541)
('Morgan County', 17868)
('Morgan County', 20565)
('Morgan County', 21987)
('Morgan County', 28159)
('Morgan County', 35547)
('Morgan County', 68894)
('Morgan County', 119490)
('Morrill County', 5042)
('Morris County', 5923)
('Morris County', 12934)
('Morris County', 492276)
('Morrison County', 33198)
('Morrow County', 11173)
('Morrow County', 34827)
('Morton County', 3233)
('Morton County', 27471)
('Motley County', 1210)
('Moultrie County', 14846)
('Mountrail County', 7673)
('Mower County', 39163)
('Muhlenberg County', 31499)
('Multnomah County', 735334)
('Murray County', 8725)
('Murray County', 13488)
('Murray County', 39628)
('Muscatine County', 42745)
('Muscogee County', 189885)
('Muskegon County', 172188)
('Muskingum County', 86074)
('Muskogee County', 70990)
('Musselshell County', 4538)
('Nacogdoches County', 64524)
('Nance County', 3735)
('Nantucket County', 10172)
('Napa County', 136484)
('Nash County', 95840)
('Nassau County', 73314)
('Nassau County', 1339532)
('Natchitoches Parish', 39566)
('Natrona County', 75450)
('Navajo County', 107449)
('Navarro County', 47735)
('Nebraska', 1826341)
('Nelson County', 3126)
('Nelson County', 15020)
('Nelson County', 43437)
('Nemaha County', 7248)
('Nemaha County', 10178)
('Neosho County', 16512)
('Neshoba County', 29676)
('Ness County', 3107)
('Nevada', 2700551)
('Nevada County', 8997)
('Nevada County', 98764)
('New Castle County', 538479)
('New Hampshire', 1316470)
('New Hanover County', 202667)
('New Haven County', 862477)
('New Jersey', 8791894)
('New Kent County', 18429)
('New London County', 274055)
('New Madrid County', 18956)
('New Mexico', 2059179)
('New York', 19378102)
('New York County', 1585873)
('Newaygo County', 48460)
('Newberry County', 37508)
('Newport County', 82888)
('Newport News city', 180719)
('Newton County', 8330)
('Newton County', 14244)
('Newton County', 14445)
('Newton County', 21720)
('Newton County', 58114)
('Newton County', 99958)
('Nez Perce County', 39265)
('Niagara County', 216469)
('Nicholas County', 7135)
('Nicholas County', 26233)
('Nicollet County', 32727)
('Niobrara County', 2484)
('Noble County', 11561)
('Noble County', 14645)
('Noble County', 47536)
('Nobles County', 21378)
('Nodaway County', 23370)
('Nolan County', 15216)
('Nome Census Area', 9492)
('Norfolk County', 670850)
('Norfolk city', 242803)
('Norman County', 6852)
('North Carolina', 9535483)
('North Dakota', 672591)
('North Slope Borough', 9430)
('Northampton County', 12389)
('Northampton County', 22099)
('Northampton County', 297735)
('Northumberland County', 12330)
('Northumberland County', 94528)
('Northwest Arctic Borough', 7523)
('Norton County', 5671)
('Norton city', 3958)
('Nottoway County', 15853)
('Nowata County', 10536)
('Noxubee County', 11545)
('Nuckolls County', 4500)
('Nueces County', 340223)
('Nye County', 43946)
("O'Brien County", 14398)
('Oakland County', 1202362)
('Obion County', 31807)
('Ocean County', 576567)
('Oceana County', 26570)
('Ochiltree County', 10223)
('Oconee County', 32808)
('Oconee County', 74273)
('Oconto County', 37660)
('Ogemaw County', 21699)
('Oglala Lakota County', 13586)
('Ogle County', 53497)
('Oglethorpe County', 14899)
('Ohio', 11536504)
('Ohio County', 6128)
('Ohio County', 23842)
('Ohio County', 44443)
('Okaloosa County', 180822)
('Okanogan County', 41120)
('Okeechobee County', 39996)
('Okfuskee County', 12191)
('Oklahoma', 3751351)
('Oklahoma County', 718633)
('Okmulgee County', 40069)
('Oktibbeha County', 47671)
('Oldham County', 2052)
('Oldham County', 60316)
('Oliver County', 1846)
('Olmsted County', 144248)
('Oneida County', 4286)
('Oneida County', 35998)
('Oneida County', 234878)
('Onondaga County', 467026)
('Onslow County', 177772)
('Ontario County', 107931)
('Ontonagon County', 6780)
('Orange County', 19840)
('Orange County', 28936)
('Orange County', 33481)
('Orange County', 81837)
('Orange County', 133801)
('Orange County', 372813)
('Orange County', 1145956)
('Orange County', 3010232)
('Orangeburg County', 92501)
('Oregon', 3831074)
('Oregon County', 10881)
('Orleans County', 27231)
('Orleans County', 42883)
('Orleans Parish', 343829)
('Osage County', 13878)
('Osage County', 16295)
('Osage County', 47472)
('Osborne County', 3858)
('Osceola County', 6462)
('Osceola County', 23528)
('Osceola County', 268685)
('Oscoda County', 8640)
('Oswego County', 122109)
('Otero County', 18831)
('Otero County', 63797)
('Otoe County', 15740)
('Otsego County', 24164)
('Otsego County', 62259)
('Ottawa County', 6091)
('Ottawa County', 31848)
('Ottawa County', 41428)
('Ottawa County', 263801)
('Otter Tail County', 57303)
('Ouachita County', 26120)
('Ouachita Parish', 153720)
('Ouray County', 4436)
('Outagamie County', 176695)
('Overton County', 22083)
('Owen County', 10841)
('Owen County', 21575)
('Owsley County', 4755)
('Owyhee County', 11526)
('Oxford County', 57833)
('Ozark County', 9723)
('Ozaukee County', 86395)
('Pacific County', 20920)
('Page County', 15932)
('Page County', 24042)
('Palm Beach County', 1320134)
('Palo Alto County', 9421)
('Palo Pinto County', 28111)
('Pamlico County', 13144)
('Panola County', 23796)
('Panola County', 34707)
('Park County', 15636)
('Park County', 16206)
('Park County', 28205)
('Parke County', 17339)
('Parker County', 116927)
('Parmer County', 10269)
('Pasco County', 464697)
('Pasquotank County', 40661)
('Passaic County', 501226)
('Patrick County', 18490)
('Paulding County', 19614)
('Paulding County', 142324)
('Pawnee County', 2773)
('Pawnee County', 6973)
('Pawnee County', 16577)
('Payette County', 22623)
('Payne County', 77350)
('Peach County', 27695)
('Pearl River County', 55834)
('Pecos County', 15507)
('Pembina County', 7413)
('Pemiscot County', 18296)
('Pend Oreille County', 13001)
('Pender County', 52217)
('Pendleton County', 7695)
('Pendleton County', 14877)
('Pennington County', 13930)
('Pennington County', 100948)
('Pennsylvania', 12702379)
('Penobscot County', 153923)
('Peoria County', 186494)
('Pepin County', 7469)
('Perkins County', 2970)
('Perkins County', 2982)
('Perquimans County', 13453)
('Perry County', 7915)
('Perry County', 10445)
('Perry County', 10591)
('Perry County', 12250)
('Perry County', 18971)
('Perry County', 19338)
('Perry County', 22350)
('Perry County', 28712)
('Perry County', 36058)
('Perry County', 45969)
('Pershing County', 6753)
('Person County', 39464)
('Petersburg Borough', 3815)
('Petersburg city', 32420)
('Petroleum County', 494)
('Pettis County', 42201)
('Phelps County', 9188)
('Phelps County', 45156)
('Philadelphia County', 1526006)
('Phillips County', 4253)
('Phillips County', 4442)
('Phillips County', 5642)
('Phillips County', 21757)
('Piatt County', 16729)
('Pickaway County', 55698)
('Pickens County', 19746)
('Pickens County', 29431)
('Pickens County', 119224)
('Pickett County', 5077)
('Pierce County', 4357)
('Pierce County', 7266)
('Pierce County', 18758)
('Pierce County', 41019)
('Pierce County', 795225)
('Pike County', 11291)
('Pike County', 12845)
('Pike County', 16430)
('Pike County', 17869)
('Pike County', 18516)
('Pike County', 28709)
('Pike County', 32899)
('Pike County', 40404)
('Pike County', 57369)
('Pike County', 65024)
('Pima County', 980263)
('Pinal County', 375770)
('Pine County', 29750)
('Pinellas County', 916542)
('Pipestone County', 9596)
('Piscataquis County', 17535)
('Pitkin County', 17148)
('Pitt County', 168148)
('Pittsburg County', 45837)
('Pittsylvania County', 63506)
('Piute County', 1556)
('Placer County', 348432)
('Plaquemines Parish', 23042)
('Platte County', 8667)
('Platte County', 32237)
('Platte County', 89322)
('Pleasants County', 7605)
('Plumas County', 20007)
('Plymouth County', 24986)
('Plymouth County', 494919)
('Pocahontas County', 7310)
('Pocahontas County', 8719)
('Poinsett County', 24583)
('Pointe Coupee Parish', 22802)
('Polk County', 5406)
('Polk County', 16825)
('Polk County', 20510)
('Polk County', 20662)
('Polk County', 31137)
('Polk County', 31600)
('Polk County', 41475)
('Polk County', 44205)
('Polk County', 45413)
('Polk County', 75403)
('Polk County', 430640)
('Polk County', 602095)
('Pondera County', 6153)
('Pontotoc County', 29957)
('Pontotoc County', 37492)
('Pope County', 4470)
('Pope County', 10995)
('Pope County', 61754)
('Poquoson city', 12150)
('Portage County', 70019)
('Portage County', 161419)
('Porter County', 164343)
('Portsmouth city', 95535)
('Posey County', 25910)
('Pottawatomie County', 21604)
('Pottawatomie County', 69442)
('Pottawattamie County', 93158)
('Potter County', 2329)
('Potter County', 17457)
('Potter County', 121073)
('Powder River County', 1743)
('Powell County', 7027)
('Powell County', 12613)
('Power County', 7817)
('Poweshiek County', 18914)
('Powhatan County', 28046)
('Prairie County', 1179)
('Prairie County', 8715)
('Pratt County', 9656)
('Preble County', 42270)
('Prentiss County', 25276)
('Presidio County', 7818)
('Presque Isle County', 13376)
('Preston County', 33520)
('Price County', 14159)
('Prince Edward County', 23368)
('Prince George County', 35725)
("Prince George's County", 863420)
('Prince William County', 402002)
('Prince of Wales-Hyder Census Area', 5559)
('Providence County', 626667)
('Prowers County', 12551)
('Pueblo County', 159063)
('Pulaski County', 6161)
('Pulaski County', 12010)
('Pulaski County', 13402)
('Pulaski County', 34872)
('Pulaski County', 52274)
('Pulaski County', 63063)
('Pulaski County', 382748)
('Pushmataha County', 11572)
('Putnam County', 4979)
('Putnam County', 6006)
('Putnam County', 21218)
('Putnam County', 34499)
('Putnam County', 37963)
('Putnam County', 55486)
('Putnam County', 72321)
('Putnam County', 74364)
('Putnam County', 99710)
('Quay County', 9041)
("Queen Anne's County", 47798)
('Queens County', 2230722)
('Quitman County', 2513)
('Quitman County', 8223)
('Rabun County', 16276)
('Racine County', 195408)
('Radford city', 16408)
('Rains County', 10914)
('Raleigh County', 78859)
('Ralls County', 10167)
('Ramsey County', 11451)
('Ramsey County', 508640)
('Randall County', 120725)
('Randolph County', 7719)
('Randolph County', 17969)
('Randolph County', 22913)
('Randolph County', 25414)
('Randolph County', 26171)
('Randolph County', 29405)
('Randolph County', 33476)
('Randolph County', 141752)
('Rankin County', 141617)
('Ransom County', 5457)
('Rapides Parish', 131613)
('Rappahannock County', 7373)
('Ravalli County', 40212)
('Rawlins County', 2519)
('Ray County', 23494)
('Reagan County', 3367)
('Real County', 3309)
('Red Lake County', 4089)
('Red River County', 12860)
('Red River Parish', 9091)
('Red Willow County', 11055)
('Redwood County', 16059)
('Reeves County', 13783)
('Refugio County', 7383)
('Reno County', 64511)
('Rensselaer County', 159429)
('Renville County', 2470)
('Renville County', 15730)
('Republic County', 4980)
('Reynolds County', 6696)
('Rhea County', 31809)
('Rhode Island', 1052567)
('Rice County', 10083)
('Rice County', 64142)
('Rich County', 2264)
('Richardson County', 8363)
('Richland County', 9746)
('Richland County', 16233)
('Richland County', 16321)
('Richland County', 18021)
('Richland County', 124475)
('Richland County', 384504)
('Richland Parish', 20725)
('Richmond County', 9254)
('Richmond County', 46639)
('Richmond County', 200549)
('Richmond County', 468730)
('Richmond city', 204214)
('Riley County', 71115)
('Ringgold County', 5131)
('Rio Arriba County', 40246)
('Rio Blanco County', 6666)
('Rio Grande County', 11982)
('Ripley County', 14100)
('Ripley County', 28818)
('Ritchie County', 10449)
('Riverside County', 2189641)
('Roane County', 14926)
('Roane County', 54181)
('Roanoke County', 92376)
('Roanoke city', 97032)
('Roberts County', 929)
('Roberts County', 10149)
('Robertson County', 2282)
('Robertson County', 16622)
('Robertson County', 66283)
('Robeson County', 134168)
('Rock County', 1526)
('Rock County', 9687)
('Rock County', 160331)
('Rock Island County', 147546)
('Rockbridge County', 22307)
('Rockcastle County', 17056)
('Rockdale County', 85215)
('Rockingham County', 76314)
('Rockingham County', 93643)
('Rockingham County', 295223)
('Rockland County', 311687)
('Rockwall County', 78337)
('Roger Mills County', 3647)
('Rogers County', 86905)
('Rolette County', 13937)
('Rooks County', 5181)
('Roosevelt County', 10425)
('Roosevelt County', 19846)
('Roscommon County', 24449)
('Roseau County', 15629)
('Rosebud County', 9233)
('Ross County', 78064)
('Routt County', 23509)
('Rowan County', 23333)
('Rowan County', 138428)

In [9]:
# What if we want to make a better seperation in the census population column
def grouping_func(item):
    if item[1] > 30000:
        return (item[0], "Densed")
    elif item[1] > 10000 and item[1] < 30000:
        return (item[0], "Medium")
    else: 
        return (item[0], "Low")
for group, frame in df2.groupby(by=grouping_func):
    print(group)

('Abbeville County', 'Medium')
('Acadia Parish', 'Densed')
('Accomack County', 'Densed')
('Ada County', 'Densed')
('Adair County', 'Low')
('Adair County', 'Medium')
('Adams County', 'Densed')
('Adams County', 'Low')
('Adams County', 'Medium')
('Addison County', 'Densed')
('Aiken County', 'Densed')
('Aitkin County', 'Medium')
('Alabama', 'Densed')
('Alachua County', 'Densed')
('Alamance County', 'Densed')
('Alameda County', 'Densed')
('Alamosa County', 'Medium')
('Alaska', 'Densed')
('Albany County', 'Densed')
('Albemarle County', 'Densed')
('Alcona County', 'Medium')
('Alcorn County', 'Densed')
('Aleutians East Borough', 'Low')
('Aleutians West Census Area', 'Low')
('Alexander County', 'Densed')
('Alexander County', 'Low')
('Alexandria city', 'Densed')
('Alfalfa County', 'Low')
('Alger County', 'Low')
('Allamakee County', 'Medium')
('Allegan County', 'Densed')
('Allegany County', 'Densed')
('Alleghany County', 'Medium')
('Allegheny County', 'Densed')
('Allen County', 'Densed')
('Allen County', 'Medium')
('Allen Parish', 'Medium')
('Allendale County', 'Medium')
('Alpena County', 'Medium')
('Alpine County', 'Low')
('Amador County', 'Densed')
('Amelia County', 'Medium')
('Amherst County', 'Densed')
('Amite County', 'Medium')
('Anchorage Municipality', 'Densed')
('Anderson County', 'Densed')
('Anderson County', 'Low')
('Anderson County', 'Medium')
('Andrew County', 'Medium')
('Andrews County', 'Medium')
('Androscoggin County', 'Densed')
('Angelina County', 'Densed')
('Anne Arundel County', 'Densed')
('Anoka County', 'Densed')
('Anson County', 'Medium')
('Antelope County', 'Low')
('Antrim County', 'Medium')
('Apache County', 'Densed')
('Appanoose County', 'Medium')
('Appling County', 'Medium')
('Appomattox County', 'Medium')
('Aransas County', 'Medium')
('Arapahoe County', 'Densed')
('Archer County', 'Low')
('Archuleta County', 'Medium')
('Arenac County', 'Medium')
('Arizona', 'Densed')
('Arkansas', 'Densed')
('Arkansas County', 'Medium')
('Arlington County', 'Densed')
('Armstrong County', 'Densed')
('Armstrong County', 'Low')
('Aroostook County', 'Densed')
('Arthur County', 'Low')
('Ascension Parish', 'Densed')
('Ashe County', 'Medium')
('Ashland County', 'Densed')
('Ashland County', 'Medium')
('Ashley County', 'Medium')
('Ashtabula County', 'Densed')
('Asotin County', 'Medium')
('Assumption Parish', 'Medium')
('Atascosa County', 'Densed')
('Atchison County', 'Low')
('Atchison County', 'Medium')
('Athens County', 'Densed')
('Atkinson County', 'Low')
('Atlantic County', 'Densed')
('Atoka County', 'Medium')
('Attala County', 'Medium')
('Audrain County', 'Medium')
('Audubon County', 'Low')
('Auglaize County', 'Densed')
('Augusta County', 'Densed')
('Aurora County', 'Low')
('Austin County', 'Medium')
('Autauga County', 'Densed')
('Avery County', 'Medium')
('Avoyelles Parish', 'Densed')
('Baca County', 'Low')
('Bacon County', 'Medium')
('Bailey County', 'Low')
('Baker County', 'Low')
('Baker County', 'Medium')
('Baldwin County', 'Densed')
('Ballard County', 'Low')
('Baltimore County', 'Densed')
('Baltimore city', 'Densed')
('Bamberg County', 'Medium')
('Bandera County', 'Medium')
('Banks County', 'Medium')
('Banner County', 'Low')
('Bannock County', 'Densed')
('Baraga County', 'Low')
('Barber County', 'Low')
('Barbour County', 'Medium')
('Barnes County', 'Medium')
('Barnstable County', 'Densed')
('Barnwell County', 'Medium')
('Barren County', 'Densed')
('Barron County', 'Densed')
('Barrow County', 'Densed')
('Barry County', 'Densed')
('Bartholomew County', 'Densed')
('Barton County', 'Medium')
('Bartow County', 'Densed')
('Bastrop County', 'Densed')
('Bates County', 'Medium')
('Bath County', 'Low')
('Bath County', 'Medium')
('Baxter County', 'Densed')
('Bay County', 'Densed')
('Bayfield County', 'Medium')
('Baylor County', 'Low')
('Beadle County', 'Medium')
('Bear Lake County', 'Low')
('Beaufort County', 'Densed')
('Beauregard Parish', 'Densed')
('Beaver County', 'Densed')
('Beaver County', 'Low')
('Beaverhead County', 'Low')
('Becker County', 'Densed')
('Beckham County', 'Medium')
('Bedford County', 'Densed')
('Bee County', 'Densed')
('Belknap County', 'Densed')
('Bell County', 'Densed')
('Bell County', 'Medium')
('Belmont County', 'Densed')
('Beltrami County', 'Densed')
('Ben Hill County', 'Medium')
('Benewah County', 'Low')
('Bennett County', 'Low')
('Bennington County', 'Densed')
('Benson County', 'Low')
('Bent County', 'Low')
('Benton County', 'Densed')
('Benton County', 'Low')
('Benton County', 'Medium')
('Benzie County', 'Medium')
('Bergen County', 'Densed')
('Berkeley County', 'Densed')
('Berks County', 'Densed')
('Berkshire County', 'Densed')
('Bernalillo County', 'Densed')
('Berrien County', 'Densed')
('Berrien County', 'Medium')
('Bertie County', 'Medium')
('Bethel Census Area', 'Medium')
('Bexar County', 'Densed')
('Bibb County', 'Densed')
('Bibb County', 'Medium')
('Bienville Parish', 'Medium')
('Big Horn County', 'Medium')
('Big Stone County', 'Low')
('Billings County', 'Low')
('Bingham County', 'Densed')
('Black Hawk County', 'Densed')
('Blackford County', 'Medium')
('Bladen County', 'Densed')
('Blaine County', 'Low')
('Blaine County', 'Medium')
('Blair County', 'Densed')
('Blanco County', 'Medium')
('Bland County', 'Low')
('Bleckley County', 'Medium')
('Bledsoe County', 'Medium')
('Blount County', 'Densed')
('Blue Earth County', 'Densed')
('Boise County', 'Low')
('Bolivar County', 'Densed')
('Bollinger County', 'Medium')
('Bon Homme County', 'Low')
('Bond County', 'Medium')
('Bonner County', 'Densed')
('Bonneville County', 'Densed')
('Boone County', 'Densed')
('Boone County', 'Low')
('Boone County', 'Medium')
('Borden County', 'Low')
('Bosque County', 'Medium')
('Bossier Parish', 'Densed')
('Botetourt County', 'Densed')
('Bottineau County', 'Low')
('Boulder County', 'Densed')
('Boundary County', 'Medium')
('Bourbon County', 'Medium')
('Bowie County', 'Densed')
('Bowman County', 'Low')
('Box Butte County', 'Medium')
('Box Elder County', 'Densed')
('Boyd County', 'Densed')
('Boyd County', 'Low')
('Boyle County', 'Medium')
('Bracken County', 'Low')
('Bradford County', 'Densed')
('Bradford County', 'Medium')
('Bradley County', 'Densed')
('Bradley County', 'Medium')
('Branch County', 'Densed')
('Brantley County', 'Medium')
('Braxton County', 'Medium')
('Brazoria County', 'Densed')
('Brazos County', 'Densed')
('Breathitt County', 'Medium')
('Breckinridge County', 'Medium')
('Bremer County', 'Medium')
('Brevard County', 'Densed')
('Brewster County', 'Low')
('Briscoe County', 'Low')
('Bristol Bay Borough', 'Low')
('Bristol County', 'Densed')
('Bristol city', 'Medium')
('Broadwater County', 'Low')
('Bronx County', 'Densed')
('Brooke County', 'Medium')
('Brookings County', 'Densed')
('Brooks County', 'Low')
('Brooks County', 'Medium')
('Broome County', 'Densed')
('Broomfield County', 'Densed')
('Broward County', 'Densed')
('Brown County', 'Densed')
('Brown County', 'Low')
('Brown County', 'Medium')
('Brule County', 'Low')
('Brunswick County', 'Densed')
('Brunswick County', 'Medium')
('Bryan County', 'Densed')
('Buchanan County', 'Densed')
('Buchanan County', 'Medium')
('Buckingham County', 'Medium')
('Bucks County', 'Densed')
('Buena Vista County', 'Medium')
('Buena Vista city', 'Low')
('Buffalo County', 'Densed')
('Buffalo County', 'Low')
('Buffalo County', 'Medium')
('Bullitt County', 'Densed')
('Bulloch County', 'Densed')
('Bullock County', 'Medium')
('Buncombe County', 'Densed')
('Bureau County', 'Densed')
('Burke County', 'Densed')
('Burke County', 'Low')
('Burke County', 'Medium')
('Burleigh County', 'Densed')
('Burleson County', 'Medium')
('Burlington County', 'Densed')
('Burnet County', 'Densed')
('Burnett County', 'Medium')
('Burt County', 'Low')
('Butler County', 'Densed')
('Butler County', 'Low')
('Butler County', 'Medium')
('Butte County', 'Densed')
('Butte County', 'Low')
('Butte County', 'Medium')
('Butts County', 'Medium')
('Cabarrus County', 'Densed')
('Cabell County', 'Densed')
('Cache County', 'Densed')
('Caddo County', 'Medium')
('Caddo Parish', 'Densed')
('Calaveras County', 'Densed')
('Calcasieu Parish', 'Densed')
('Caldwell County', 'Densed')
('Caldwell County', 'Low')
('Caldwell County', 'Medium')
('Caldwell Parish', 'Medium')
('Caledonia County', 'Densed')
('Calhoun County', 'Densed')
('Calhoun County', 'Low')
('Calhoun County', 'Medium')
('California', 'Densed')
('Callahan County', 'Medium')
('Callaway County', 'Densed')
('Calloway County', 'Densed')
('Calumet County', 'Densed')
('Calvert County', 'Densed')
('Camas County', 'Low')
('Cambria County', 'Densed')
('Camden County', 'Densed')
('Camden County', 'Low')
('Cameron County', 'Densed')
('Cameron County', 'Low')
('Cameron Parish', 'Low')
('Camp County', 'Medium')
('Campbell County', 'Densed')
('Campbell County', 'Low')
('Canadian County', 'Densed')
('Candler County', 'Medium')
('Cannon County', 'Medium')
('Canyon County', 'Densed')
('Cape Girardeau County', 'Densed')
('Cape May County', 'Densed')
('Carbon County', 'Densed')
('Carbon County', 'Medium')
('Caribou County', 'Low')
('Carlisle County', 'Low')
('Carlton County', 'Densed')
('Caroline County', 'Densed')
('Caroline County', 'Medium')
('Carroll County', 'Densed')
('Carroll County', 'Low')
('Carroll County', 'Medium')
('Carson City', 'Densed')
('Carson County', 'Low')
('Carter County', 'Densed')
('Carter County', 'Low')
('Carter County', 'Medium')
('Carteret County', 'Densed')
('Carver County', 'Densed')
('Cascade County', 'Densed')
('Casey County', 'Medium')
('Cass County', 'Densed')
('Cass County', 'Medium')
('Cassia County', 'Medium')
('Castro County', 'Low')
('Caswell County', 'Medium')
('Catahoula Parish', 'Medium')
('Catawba County', 'Densed')
('Catoosa County', 'Densed')
('Catron County', 'Low')
('Cattaraugus County', 'Densed')
('Cavalier County', 'Low')
('Cayuga County', 'Densed')
('Cecil County', 'Densed')
('Cedar County', 'Low')
('Cedar County', 'Medium')
('Centre County', 'Densed')
('Cerro Gordo County', 'Densed')
('Chaffee County', 'Medium')
('Chambers County', 'Densed')
('Champaign County', 'Densed')
('Chariton County', 'Low')
('Charles City County', 'Low')
('Charles County', 'Densed')
('Charles Mix County', 'Low')
('Charleston County', 'Densed')
('Charlevoix County', 'Medium')
('Charlotte County', 'Densed')
('Charlotte County', 'Medium')
('Charlottesville city', 'Densed')
('Charlton County', 'Medium')
('Chase County', 'Low')
('Chatham County', 'Densed')
('Chattahoochee County', 'Medium')
('Chattooga County', 'Medium')
('Chautauqua County', 'Densed')
('Chautauqua County', 'Low')
('Chaves County', 'Densed')
('Cheatham County', 'Densed')
('Cheboygan County', 'Medium')
('Chelan County', 'Densed')
('Chemung County', 'Densed')
('Chenango County', 'Densed')
('Cherokee County', 'Densed')
('Cherokee County', 'Medium')
('Cherry County', 'Low')
('Chesapeake city', 'Densed')
('Cheshire County', 'Densed')
('Chester County', 'Densed')
('Chester County', 'Medium')
('Chesterfield County', 'Densed')
('Cheyenne County', 'Low')
('Chickasaw County', 'Medium')
('Chicot County', 'Medium')
('Childress County', 'Low')
('Chilton County', 'Densed')
('Chippewa County', 'Densed')
('Chippewa County', 'Medium')
('Chisago County', 'Densed')
('Chittenden County', 'Densed')
('Choctaw County', 'Low')
('Choctaw County', 'Medium')
('Chouteau County', 'Low')
('Chowan County', 'Medium')
('Christian County', 'Densed')
('Churchill County', 'Medium')
('Cibola County', 'Medium')
('Cimarron County', 'Low')
('Citrus County', 'Densed')
('Clackamas County', 'Densed')
('Claiborne County', 'Densed')
('Claiborne County', 'Low')
('Claiborne Parish', 'Medium')
('Clallam County', 'Densed')
('Clare County', 'Densed')
('Clarendon County', 'Densed')
('Clarion County', 'Densed')
('Clark County', 'Densed')
('Clark County', 'Low')
('Clark County', 'Medium')
('Clarke County', 'Densed')
('Clarke County', 'Low')
('Clarke County', 'Medium')
('Clatsop County', 'Densed')
('Clay County', 'Densed')
('Clay County', 'Low')
('Clay County', 'Medium')
('Clayton County', 'Densed')
('Clayton County', 'Medium')
('Clear Creek County', 'Low')
('Clearfield County', 'Densed')
('Clearwater County', 'Low')
('Cleburne County', 'Medium')
('Clermont County', 'Densed')
('Cleveland County', 'Densed')
('Cleveland County', 'Low')
('Clinch County', 'Low')
('Clinton County', 'Densed')
('Clinton County', 'Medium')
('Cloud County', 'Low')
('Coahoma County', 'Medium')
('Coal County', 'Low')
('Cobb County', 'Densed')
('Cochise County', 'Densed')
('Cochran County', 'Low')
('Cocke County', 'Densed')
('Coconino County', 'Densed')
('Codington County', 'Medium')
('Coffee County', 'Densed')
('Coffey County', 'Low')
('Coke County', 'Low')
('Colbert County', 'Densed')
('Cole County', 'Densed')
('Coleman County', 'Low')
('Coles County', 'Densed')
('Colfax County', 'Medium')
('Colleton County', 'Densed')
('Collier County', 'Densed')
('Collin County', 'Densed')
('Collingsworth County', 'Low')
('Colonial Heights city', 'Medium')
('Colorado', 'Densed')
('Colorado County', 'Medium')
('Colquitt County', 'Densed')
('Columbia County', 'Densed')
('Columbia County', 'Low')
('Columbia County', 'Medium')
('Columbiana County', 'Densed')
('Columbus County', 'Densed')
('Colusa County', 'Medium')
('Comal County', 'Densed')
('Comanche County', 'Densed')
('Comanche County', 'Low')
('Comanche County', 'Medium')
('Concho County', 'Low')
('Concordia Parish', 'Medium')
('Conecuh County', 'Medium')
('Conejos County', 'Low')
('Connecticut', 'Densed')
('Contra Costa County', 'Densed')
('Converse County', 'Medium')
('Conway County', 'Medium')
('Cook County', 'Densed')
('Cook County', 'Low')
('Cook County', 'Medium')
('Cooke County', 'Densed')
('Cooper County', 'Medium')
('Coos County', 'Densed')
('Coosa County', 'Medium')
('Copiah County', 'Medium')
('Corson County', 'Low')
('Cortland County', 'Densed')
('Coryell County', 'Densed')
('Coshocton County', 'Densed')
('Costilla County', 'Low')
('Cottle County', 'Low')
('Cotton County', 'Low')
('Cottonwood County', 'Medium')
('Covington County', 'Densed')
('Covington County', 'Medium')
('Covington city', 'Low')
('Coweta County', 'Densed')
('Cowley County', 'Densed')
('Cowlitz County', 'Densed')
('Craig County', 'Low')
('Craig County', 'Medium')
('Craighead County', 'Densed')
('Crane County', 'Low')
('Craven County', 'Densed')
('Crawford County', 'Densed')
('Crawford County', 'Medium')
('Creek County', 'Densed')
('Crenshaw County', 'Medium')
('Crisp County', 'Medium')
('Crittenden County', 'Densed')
('Crittenden County', 'Low')
('Crockett County', 'Low')
('Crockett County', 'Medium')
('Crook County', 'Low')
('Crook County', 'Medium')
('Crosby County', 'Low')
('Cross County', 'Medium')
('Crow Wing County', 'Densed')
('Crowley County', 'Low')
('Culberson County', 'Low')
('Cullman County', 'Densed')
('Culpeper County', 'Densed')
('Cumberland County', 'Densed')
('Cumberland County', 'Low')
('Cumberland County', 'Medium')
('Cuming County', 'Low')
('Currituck County', 'Medium')
('Curry County', 'Densed')
('Curry County', 'Medium')
('Custer County', 'Low')
('Custer County', 'Medium')
('Cuyahoga County', 'Densed')
('Dade County', 'Low')
('Dade County', 'Medium')
('Daggett County', 'Low')
('Dakota County', 'Densed')
('Dakota County', 'Medium')
('Dale County', 'Densed')
('Dallam County', 'Low')
('Dallas County', 'Densed')
('Dallas County', 'Low')
('Dallas County', 'Medium')
('Dane County', 'Densed')
('Daniels County', 'Low')
('Danville city', 'Densed')
('Dare County', 'Densed')
('Darke County', 'Densed')
('Darlington County', 'Densed')
('Dauphin County', 'Densed')
('Davidson County', 'Densed')
('Davie County', 'Densed')
('Daviess County', 'Densed')
('Daviess County', 'Low')
('Davis County', 'Densed')
('Davis County', 'Low')
('Davison County', 'Medium')
('Dawes County', 'Low')
('Dawson County', 'Low')
('Dawson County', 'Medium')
('Day County', 'Low')
('De Baca County', 'Low')
('De Soto Parish', 'Medium')
('De Witt County', 'Medium')
('DeKalb County', 'Densed')
('DeKalb County', 'Medium')
('DeSoto County', 'Densed')
('DeWitt County', 'Medium')
('Deaf Smith County', 'Medium')
('Dearborn County', 'Densed')
('Decatur County', 'Low')
('Decatur County', 'Medium')
('Deer Lodge County', 'Low')
('Defiance County', 'Densed')
('Del Norte County', 'Medium')
('Delaware', 'Densed')
('Delaware County', 'Densed')
('Delaware County', 'Medium')
('Delta County', 'Densed')
('Delta County', 'Low')
('Denali Borough', 'Low')
('Dent County', 'Medium')
('Denton County', 'Densed')
('Denver County', 'Densed')
('Des Moines County', 'Densed')
('Deschutes County', 'Densed')
('Desha County', 'Medium')
('Deuel County', 'Low')
('Dewey County', 'Low')
('Dickens County', 'Low')
('Dickenson County', 'Medium')
('Dickey County', 'Low')
('Dickinson County', 'Medium')
('Dickson County', 'Densed')
('Dillingham Census Area', 'Low')
('Dillon County', 'Densed')
('Dimmit County', 'Low')
('Dinwiddie County', 'Medium')
('District of Columbia', 'Densed')
('Divide County', 'Low')
('Dixie County', 'Medium')
('Dixon County', 'Low')
('Doddridge County', 'Low')
('Dodge County', 'Densed')
('Dodge County', 'Medium')
('Dolores County', 'Low')
('Doniphan County', 'Low')
('Donley County', 'Low')
('Dooly County', 'Medium')
('Door County', 'Medium')
('Dorchester County', 'Densed')
('Dougherty County', 'Densed')
('Douglas County', 'Densed')
('Douglas County', 'Low')
('Douglas County', 'Medium')
('Doña Ana County', 'Densed')
('Drew County', 'Medium')
('DuPage County', 'Densed')
('Dubois County', 'Densed')
('Dubuque County', 'Densed')
('Duchesne County', 'Medium')
('Dukes County', 'Medium')
('Dundy County', 'Low')
('Dunklin County', 'Densed')
('Dunn County', 'Densed')
('Dunn County', 'Low')
('Duplin County', 'Densed')
('Durham County', 'Densed')
('Dutchess County', 'Densed')
('Duval County', 'Densed')
('Duval County', 'Medium')
('Dyer County', 'Densed')
('Eagle County', 'Densed')
('Early County', 'Medium')
('East Baton Rouge Parish', 'Densed')
('East Carroll Parish', 'Low')
('East Feliciana Parish', 'Medium')
('Eastland County', 'Medium')
('Eaton County', 'Densed')
('Eau Claire County', 'Densed')
('Echols County', 'Low')
('Ector County', 'Densed')
('Eddy County', 'Densed')
('Eddy County', 'Low')
('Edgar County', 'Medium')
('Edgecombe County', 'Densed')
('Edgefield County', 'Medium')
('Edmonson County', 'Medium')
('Edmunds County', 'Low')
('Edwards County', 'Low')
('Effingham County', 'Densed')
('El Dorado County', 'Densed')
('El Paso County', 'Densed')
('Elbert County', 'Medium')
('Elk County', 'Densed')
('Elk County', 'Low')
('Elkhart County', 'Densed')
('Elko County', 'Densed')
('Elliott County', 'Low')
('Ellis County', 'Densed')
('Ellis County', 'Low')
('Ellis County', 'Medium')
('Ellsworth County', 'Low')
('Elmore County', 'Densed')
('Elmore County', 'Medium')
('Emanuel County', 'Medium')
('Emery County', 'Medium')
('Emmet County', 'Densed')
('Emmet County', 'Medium')
('Emmons County', 'Low')
('Emporia city', 'Low')
('Erath County', 'Densed')
('Erie County', 'Densed')
('Escambia County', 'Densed')
('Esmeralda County', 'Low')
('Essex County', 'Densed')
('Essex County', 'Low')
('Essex County', 'Medium')
('Estill County', 'Medium')
('Etowah County', 'Densed')
('Eureka County', 'Low')
('Evangeline Parish', 'Densed')
('Evans County', 'Medium')
('Fairbanks North Star Borough', 'Densed')
('Fairfax County', 'Densed')
('Fairfax city', 'Medium')
('Fairfield County', 'Densed')
('Fairfield County', 'Medium')
('Fall River County', 'Low')
('Fallon County', 'Low')
('Falls Church city', 'Medium')
('Falls County', 'Medium')
('Fannin County', 'Densed')
('Fannin County', 'Medium')
('Faribault County', 'Medium')
('Faulk County', 'Low')
('Faulkner County', 'Densed')
('Fauquier County', 'Densed')
('Fayette County', 'Densed')
('Fayette County', 'Medium')
('Fentress County', 'Medium')
('Fergus County', 'Medium')
('Ferry County', 'Low')
('Fillmore County', 'Low')
('Fillmore County', 'Medium')
('Finney County', 'Densed')
('Fisher County', 'Low')
('Flagler County', 'Densed')
('Flathead County', 'Densed')
('Fleming County', 'Medium')

('Wilson County', 'Densed')
('Wilson County', 'Low')
('Winchester city', 'Medium')
('Windham County', 'Densed')
('Windsor County', 'Densed')
('Winkler County', 'Low')
('Winn Parish', 'Medium')
('Winnebago County', 'Densed')
('Winnebago County', 'Medium')
('Winneshiek County', 'Medium')
('Winona County', 'Densed')
('Winston County', 'Medium')
('Wirt County', 'Low')
('Wisconsin', 'Densed')
('Wise County', 'Densed')
('Wolfe County', 'Low')
('Wood County', 'Densed')
('Woodbury County', 'Densed')
('Woodford County', 'Densed')
('Woodford County', 'Medium')
('Woodruff County', 'Low')
('Woods County', 'Low')
('Woodson County', 'Low')
('Woodward County', 'Medium')
('Worcester County', 'Densed')
('Worth County', 'Low')
('Worth County', 'Medium')
('Wrangell City and Borough', 'Low')
('Wright County', 'Densed')
('Wright County', 'Medium')
('Wyandot County', 'Medium')
('Wyandotte County', 'Densed')
('Wyoming', 'Densed')
('Wyoming County', 'Densed')
('Wyoming County', 'Medium')
('Wythe County', 'Medium')
('Yadkin County', 'Densed')
('Yakima County', 'Densed')
('Yakutat City and Borough', 'Low')
('Yalobusha County', 'Medium')
('Yamhill County', 'Densed')
('Yancey County', 'Medium')
('Yankton County', 'Medium')
('Yates County', 'Medium')
('Yavapai County', 'Densed')
('Yazoo County', 'Medium')
('Yell County', 'Medium')
('Yellow Medicine County', 'Medium')
('Yellowstone County', 'Densed')
('Yoakum County', 'Low')
('Yolo County', 'Densed')
('York County', 'Densed')
('York County', 'Medium')
('Young County', 'Medium')
('Yuba County', 'Densed')
('Yukon-Koyukuk Census Area', 'Low')
('Yuma County', 'Densed')
('Yuma County', 'Medium')
('Zapata County', 'Medium')
('Zavala County', 'Medium')
('Ziebach County', 'Low')

In [10]:
# There are 3 broad Data Processing to happen during the apply step
# Aggregation of group data, Transformation of group data and
# Filtration of group data.

## Aggregation

The agg() function allows you to apply a function or a list of function names to be executed along one of the axis of the DataFrame, default 0, which is the index (row) axis.

In [12]:
df2 = pd.read_csv("C:\\Users\\AD\\Desktop\\Introduction to Data Science in Python/house_prices.csv")

In [13]:
df2.head()

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,2008-05-21,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,2008-05-21,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,2008-05-21,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,2008-05-21,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,2008-05-21,81900,38.519470,-121.435768

In [26]:
cols = list(x.capitalize() for x in df2.columns)
df2.columns = cols

In [31]:
for group, frame in df2.groupby(['Type', 'Price']):
    print(group, frame)

('Condo', 40000)               Street        City    Zip State  Beds  Baths  Sq__ft   Type  \
335  5840 WALERGA RD  SACRAMENTO  95842    CA     2      1     840  Condo

      Sale_date  Price   Latitude   Longitude
335  2008-05-19  40000  38.673678 -121.357471
('Condo', 48000)              Street        City    Zip State  Beds  Baths  Sq__ft   Type  \
336  923 FULTON AVE  SACRAMENTO  95825    CA     1      1     484  Condo

      Sale_date  Price   Latitude   Longitude
336  2008-05-19  48000  38.582279 -121.401482
('Condo', 60000)                       Street        City    Zip State  Beds  Baths  Sq__ft  \
868  9127 NEWHALL DR Unit 34  SACRAMENTO  95826    CA     1      1     611

      Type   Sale_date  Price   Latitude   Longitude
868  Condo  2008-05-15  60000  38.542419 -121.359904
('Condo', 62000)                   Street        City    Zip State  Beds  Baths  Sq__ft   Type  \
870  5672 HILLSDALE BLVD  SACRAMENTO  95842    CA     2      1     933  Condo

      Sale_date  Price   Latitude   Longitude
870  2008-05-15  62000  38.670467 -121.359799
('Condo', 69000)                       Street            City    Zip State  Beds  Baths  \
158  6272 LONGFORD DR Unit 1  CITRUS HEIGHTS  95621    CA     2      1

     Sq__ft   Type   Sale_date  Price   Latitude   Longitude
158     795  Condo  2008-05-20  69000  38.680923 -121.313945
('Condo', 71000)                           Street       City    Zip State  Beds  Baths  Sq__ft  \
160  9512 EMERALD PARK DR Unit 3  ELK GROVE  95624    CA     2      1     840

      Type   Sale_date  Price  Latitude   Longitude
160  Condo  2008-05-20  71000  38.40573 -121.369832
('Condo', 77000)                           Street        City    Zip State  Beds  Baths  \
343  5050 RHODE ISLAND DR Unit 4  SACRAMENTO  95841    CA     2      1
613             8248 CENTER PKWY  SACRAMENTO  95823    CA     2      1

     Sq__ft   Type   Sale_date  Price   Latitude   Longitude
343     924  Condo  2008-05-19  77000  38.658739 -121.333561
613     906  Condo  2008-05-16  77000  38.459002 -121.428794
('Condo', 82732)                  Street        City    Zip State  Beds  Baths  Sq__ft   Type  \
344  4513 GREENHOLME DR  SACRAMENTO  95842    CA     2      1     795  Condo

      Sale_date  Price   Latitude   Longitude
344  2008-05-19  82732  38.669104 -121.359008
('Condo', 89921)                Street        City    Zip State  Beds  Baths  Sq__ft   Type  \
5  5828 PEPPERMILL CT  SACRAMENTO  95841    CA     3      1    1122  Condo

    Sale_date  Price   Latitude   Longitude
5  2008-05-21  89921  38.662595 -121.327813
('Condo', 90000)               Street        City    Zip State  Beds  Baths  Sq__ft   Type  \
349  9058 MONTOYA ST  SACRAMENTO  95826    CA     2      1     795  Condo

      Sale_date  Price   Latitude   Longitude
349  2008-05-19  90000  38.559144 -121.368387
('Condo', 92000)                 Street        City    Zip State  Beds  Baths  Sq__ft   Type  \
875  550 DEL VERDE CIR  SACRAMENTO  95833    CA     2      1     956  Condo

      Sale_date  Price   Latitude   Longitude
875  2008-05-15  92000  38.627147 -121.500799
('Condo', 94905)                             Street            City    Zip State  Beds  Baths  \
8  11150 TRINITY RIVER DR Unit 114  RANCHO CORDOVA  95670    CA     2      2

   Sq__ft   Type   Sale_date  Price   Latitude   Longitude
8     941  Condo  2008-05-21  94905  38.621188 -121.270555
('Condo', 98000)                            Street       City    Zip State  Beds  Baths  \
171  5201 LAGUNA OAKS DR Unit 199  ELK GROVE  95758    CA     1      1

     Sq__ft   Type   Sale_date  Price   Latitude   Longitude
171     722  Condo  2008-05-20  98000  38.423251 -121.444489
('Condo', 100000)                            Street        City    Zip State  Beds  Baths  \
173  5201 LAGUNA OAKS DR Unit 172   ELK GROVE  95758    CA     1      1
354   3715 TALLYHO DR Unit 78HIGH  SACRAMENTO  95826    CA     1      1

     Sq__ft   Type   Sale_date   Price   Latitude   Longitude
173     722  Condo  2008-05-20  100000  38.423251 -121.444489
354     625  Condo  2008-05-19  100000  38.544627 -121.357960
('Condo', 104250)                 Street        City    Zip State  Beds  Baths  Sq__ft   Type  \
617  6063 LAND PARK DR  SACRAMENTO  95822    CA     2      1     800  Condo

      Sale_date   Price   Latitude   Longitude
617  2008-05-16  104250  38.517029 -121.513809
('Condo', 107666)                        Street        City    Zip State  Beds  Baths  Sq__ft  \
881  739 E WOODSIDE LN Unit E  SACRAMENTO  95825    CA     1      1     682

      Type   Sale_date   Price   Latitude   Longitude
881  Condo  2008-05-15  107666  38.578675 -121.409951
('Condo', 110700)             Street        City    Zip State  Beds  Baths  Sq__ft   Type  \
15  7340 HAMDEN PL  SACRAMENTO  95842    CA     2      2    1134  Condo

     Sale_date   Price   Latitude   Longitude
15  2008-05-21  110700  38.700051 -121.351278
('Condo', 115000)                           Street        City    Zip State  Beds  Baths  \
362              8020 WALERGA RD    ANTELOPE  95843    CA     2      2
363            167 VALLEY OAK DR   ROSEVILLE  95678    CA     2      2
622  4800 WESTLAKE PKWY Unit 410  SACRAMENTO  95835    CA     1      1

     Sq__ft   Type   Sale_date   Price   Latitude   Longitude
362     836  Condo  2008-05-19  115000  38.716070 -121.364468
363    1100  Condo  2008-05-19  115000  38.732429 -121.288069
622     846  Condo  2008-05-16  115000  38.658812 -121.542345
('Condo', 116250)                      Street            City    Zip State  Beds  Baths  Sq__ft  \
17  6236 LONGFORD DR Unit 1  CITRUS HEIGHTS  95621    CA     2      1     795

     Type   Sale_date   Price   Latitude   Longitude
17  Condo  2008-05-21  116250  38.679776 -121.314089
('Condo', 119000)                      Street          City    Zip State  Beds  Baths  Sq__ft  \
888  3035 ESTEPA DR Unit 5C  CAMERON PARK  95682    CA     0      0       0

      Type   Sale_date   Price   Latitude   Longitude
888  Condo  2008-05-15  119000  38.681393 -120.996713
('Condo', 120000)                          Street        City    Zip State  Beds  Baths  Sq__ft  \
368  4200 COMMERCE WAY Unit 711  SACRAMENTO  95834    CA     2      2     958

      Type   Sale_date   Price   Latitude   Longitude
368  Condo  2008-05-19  120000  38.647523 -121.523217
('Condo', 126960)              Street        City    Zip State  Beds  Baths  Sq__ft   Type  \
377  9013 CASALS ST  SACRAMENTO  95826    CA     2      1     795  Condo

      Sale_date   Price   Latitude  Longitude
377  2008-05-19  126960  38.557045 -121.37167
('Condo', 127000)                   Street       City    Zip State  Beds  Baths  Sq__ft   Type  \
378  227 MAHAN CT Unit 1  ROSEVILLE  95678    CA     2      1     780  Condo

      Sale_date   Price   Latitude  Longitude
378  2008-05-19  127000  38.749723 -121.27008
('Condo', 133000)                           Street       City    Zip State  Beds  Baths  Sq__ft  \
30  5201 LAGUNA OAKS DR Unit 140  ELK GROVE  95758    CA     2      2    1039

     Type   Sale_date   Price   Latitude   Longitude
30  Condo  2008-05-21  133000  38.423251 -121.444489
('Condo', 138000)                        Street     City    Zip State  Beds  Baths  Sq__ft  \
901  1530 TOPANGA LN Unit 204  LINCOLN  95648    CA     0      0       0

      Type   Sale_date   Price  Latitude   Longitude
901  Condo  2008-05-15  138000  38.88415 -121.270277
('Condo', 139500)                   Street        City    Zip State  Beds  Baths  Sq__ft   Type  \
383  7032 FAIR OAKS BLVD  CARMICHAEL  95608    CA     3      2    1245  Condo

      Sale_date   Price   Latitude   Longitude
383  2008-05-19  139500  38.628563 -121.328297
('Condo', 141000)                           Street       City    Zip State  Beds  Baths  Sq__ft  \
34  5201 LAGUNA OAKS DR Unit 162  ELK GROVE  95758    CA     2      2    1039

     Type   Sale_date   Price   Latitude   Longitude
34  Condo  2008-05-21  141000  38.423251 -121.444489
('Condo', 142500)                         Street       City    Zip State  Beds  Baths  Sq__ft  \
190  5333 PRIMROSE DR Unit 19A  FAIR OAKS  95628    CA     2      2     994

      Type   Sale_date   Price   Latitude   Longitude
190  Condo  2008-05-20  142500  38.662785 -121.276272
('Condo', 145000)                            Street       City    Zip State  Beds  Baths  \
192  5201 LAGUNA OAKS DR Unit 126  ELK GROVE  95758    CA     0      0

     Sq__ft   Type   Sale_date   Price   Latitude   Longitude
192       0  Condo  2008-05-20  145000  38.423251 -121.444489
('Condo', 150000)                                   Street        City    Zip State  Beds  \
39                      2442 LARKSPUR LN  SACRAMENTO  95825    CA     1
390  10001 WOODCREEK OAKS BLVD Unit 1415   ROSEVILLE  95747    CA     2

     Baths  Sq__ft   Type   Sale_date   Price   Latitude   Longitude
39       1     760  Condo  2008-05-21  150000  38.585140 -121.403736
390      2       0  Condo  2008-05-19  150000  38.795529 -121.328819
('Condo', 150454)                      Street        City    Zip State  Beds  Baths  Sq__ft  \
908  5754 WALERGA RD Unit 4  SACRAMENTO  95842    CA     2      1     924

      Type   Sale_date   Price   Latitude   Longitude
908  Condo  2008-05-15  150454  38.672567 -121.356754
('Condo', 152000)                           Street        City    Zip State  Beds  Baths  \
40  4800 WESTLAKE PKWY Unit 2109  SACRAMENTO  95835    CA     2      2

    Sq__ft   Type   Sale_date   Price   Latitude   Longitude
40    1304  Condo  2008-05-21  152000  38.658812 -121.542345
('Condo', 170000)                                  Street       City    Zip State  Beds  Baths  \
922  10001 WOODCREEK OAKS BLVD Unit 815  ROSEVILLE  95747    CA     2      2

     Sq__ft   Type   Sale_date   Price   Latitude   Longitude
922       0  Condo  2008-05-15  170000  38.795529 -121.328819
('Condo', 182000)                      Street        City    Zip State  Beds  Baths  Sq__ft  \
414  7110 STELLA LN Unit 15  CARMICHAEL  95608    CA     2      2    1000

      Type   Sale_date   Price   Latitude   Longitude
414  Condo  2008-05-19  182000  38.637396 -121.300055
('Condo', 188000)                        Street     City    Zip State  Beds  Baths  Sq__ft  \
934  1550 TOPANGA LN Unit 207  LINCOLN  95648    CA     0      0       0

      Type   Sale_date   Price  Latitude   Longitude
934  Condo  2008-05-15  188000  38.88417 -121.270222
('Condo', 210944)                Street        City    Zip State  Beds  Baths  Sq__ft   Type  \
703  1900 DANBROOK DR  SACRAMENTO  95835    CA     1      1     984  Condo

      Sale_date   Price   Latitude   Longitude
703  2008-05-16  210944  38.668433 -121.503471
('Condo', 212500)            Street       City    Zip State  Beds  Baths  Sq__ft   Type  \
704  140 VENTO CT  ROSEVILLE  95678    CA     3      2       0  Condo

      Sale_date   Price   Latitude   Longitude
704  2008-05-16  212500  38.793533 -121.289685
('Condo', 220000)                Street       City    Zip State  Beds  Baths  Sq__ft   Type  \
966  9197 CORTINA CIR  ROSEVILLE  95678    CA     3      2       0  Condo

      Sale_date   Price   Latitude   Longitude
966  2008-05-15  220000  38.793152 -121.290025
('Condo', 225000)               Street        City    Zip State  Beds  Baths  Sq__ft   Type  \
236  2340 HURLEY WAY  SACRAMENTO  95825    CA     0      0       0  Condo

      Sale_date   Price   Latitude   Longitude
236  2008-05-20  225000  38.588816 -121.408549
('Condo', 230522)                    Street        City    Zip State  Beds  Baths  Sq__ft  \
443  4709 AMBER LN Unit 1  SACRAMENTO  95841    CA     2      1     756

      Type   Sale_date   Price   Latitude   Longitude
443  Condo  2008-05-19  230522  38.657789 -121.354994
('Condo', 232500)               Street        City    Zip State  Beds  Baths  Sq__ft   Type  \
446  301 OLIVADI WAY  SACRAMENTO  95834    CA     2      2    1250  Condo

      Sale_date   Price   Latitude   Longitude
446  2008-05-19  232500  38.644406 -121.549049
('Condo', 238000)                      Street        City    Zip State  Beds  Baths  Sq__ft  \
453  3301 PARK DR Unit 1914  SACRAMENTO  95835    CA     3      2    1678

      Type   Sale_date   Price   Latitude   Longitude
453  Condo  2008-05-19  238000  38.665296 -121.531993

('Condo', 240000)                   Street    City    Zip State  Beds  Baths  Sq__ft   Type  \
248  611 BLOSSOM ROCK LN  FOLSOM  95630    CA     0      0       0  Condo

      Sale_date   Price  Latitude  Longitude
248  2008-05-20  240000   38.6457  -121.1197
('Condo', 250134)           Street        City    Zip State  Beds  Baths  Sq__ft   Type  \
94  4010 ALEX LN  CARMICHAEL  95608    CA     2      2    1326  Condo

     Sale_date   Price   Latitude   Longitude
94  2008-05-21  250134  38.637028 -121.312963
('Condo', 260000)                     Street    City    Zip State  Beds  Baths  Sq__ft   Type  \
468  2231 COUNTRY VILLA CT  AUBURN  95603    CA     2      2    1255  Condo

      Sale_date   Price   Latitude   Longitude
468  2008-05-19  260000  38.931671 -121.097862
('Condo', 265000)                       Street        City    Zip State  Beds  Baths  Sq__ft  \
101  4236 NATOMAS CENTRAL DR  SACRAMENTO  95834    CA     3      2    1672

      Type   Sale_date   Price   Latitude   Longitude
101  Condo  2008-05-21  265000  38.648879 -121.544023
('Condo', 300000)                                Street        City    Zip State  Beds  Baths  \
279  11281 STANFORD COURT LN Unit 604  GOLD RIVER  95670    CA     0      0

     Sq__ft   Type   Sale_date   Price   Latitude   Longitude
279       0  Condo  2008-05-20  300000  38.625289 -121.260286
('Condo', 350000)               Street       City    Zip State  Beds  Baths  Sq__ft   Type  \
814  281 SPYGLASS HL  ROSEVILLE  95678    CA     3      2    2100  Condo

      Sale_date   Price   Latitude   Longitude
814  2008-05-16  350000  38.762153 -121.283451
('Condo', 360000)                Street        City    Zip State  Beds  Baths  Sq__ft   Type  \
511  1322 SUTTER WALK  SACRAMENTO  95816    CA     0      0       0  Condo

      Sale_date   Price  Latitude  Longitude
511  2008-05-19  360000  38.53805  -121.5047
('Multi-Family', 100000)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
353  2820 DEL PASO BLVD  SACRAMENTO  95815    CA     4      2    1404

             Type   Sale_date   Price   Latitude   Longitude
353  Multi-Family  2008-05-19  100000  38.617718 -121.440089
('Multi-Family', 120000)            Street        City    Zip State  Beds  Baths  Sq__ft          Type  \
366  7342 GIGI PL  SACRAMENTO  95828    CA     4      4    1995  Multi-Family

      Sale_date   Price   Latitude   Longitude
366  2008-05-19  120000  38.490704 -121.410176
('Multi-Family', 159900)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
648  8198 STEVENSON AVE  SACRAMENTO  95828    CA     6      4    2475

             Type   Sale_date   Price   Latitude  Longitude
648  Multi-Family  2008-05-16  159900  38.465271 -121.40426
('Multi-Family', 170000)            Street        City    Zip State  Beds  Baths  Sq__ft          Type  \
923  7351 GIGI PL  SACRAMENTO  95828    CA     4      2    1859  Multi-Family

      Sale_date   Price   Latitude   Longitude
923  2008-05-15  170000  38.490606 -121.410173
('Multi-Family', 179580)              Street        City    Zip State  Beds  Baths  Sq__ft  \
56  4520 BOMARK WAY  SACRAMENTO  95842    CA     4      2    1943

            Type   Sale_date   Price   Latitude   Longitude
56  Multi-Family  2008-05-21  179580  38.665724 -121.358576
('Multi-Family', 195000)            Street        City    Zip State  Beds  Baths  Sq__ft          Type  \
68  7624 BOGEY CT  SACRAMENTO  95828    CA     4      4    2162  Multi-Family

     Sale_date   Price  Latitude   Longitude
68  2008-05-21  195000  38.48009 -121.415102
('Multi-Family', 221250)               Street        City    Zip State  Beds  Baths  Sq__ft  \
716  1139 CLINTON RD  SACRAMENTO  95825    CA     4      2    1776

             Type   Sale_date   Price   Latitude   Longitude
716  Multi-Family  2008-05-16  221250  38.585291 -121.406824
('Multi-Family', 236000)                  Street            City    Zip State  Beds  Baths  Sq__ft  \
451  10949 SCOTSMAN WAY  RANCHO CORDOVA  95670    CA     5      4    2382

             Type   Sale_date   Price   Latitude   Longitude
451  Multi-Family  2008-05-19  236000  38.603686 -121.277844
('Multi-Family', 256054)               Street            City    Zip State  Beds  Baths  Sq__ft  \
258  6344 BONHAM CIR  CITRUS HEIGHTS  95610    CA     5      4    2085

             Type   Sale_date   Price   Latitude   Longitude
258  Multi-Family  2008-05-20  256054  38.682358 -121.272876
('Multi-Family', 282400)                Street        City    Zip State  Beds  Baths  Sq__ft  \
108  2912 NORCADE CIR  SACRAMENTO  95826    CA     8      4    3612

             Type   Sale_date   Price   Latitude   Longitude
108  Multi-Family  2008-05-21  282400  38.559505 -121.364839
('Multi-Family', 285000)                  Street    City    Zip State  Beds  Baths  Sq__ft  \
484  220 OLD AIRPORT RD  AUBURN  95603    CA     2      2     960

             Type   Sale_date   Price   Latitude   Longitude
484  Multi-Family  2008-05-19  285000  38.939802 -121.054575
('Multi-Family', 297000)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
113  10158 CRAWFORD WAY  SACRAMENTO  95827    CA     4      4    2213

             Type   Sale_date   Price  Latitude   Longitude
113  Multi-Family  2008-05-21  297000   38.5703 -121.315735
('Multi-Family', 416767)              Street        City    Zip State  Beds  Baths  Sq__ft  \
527  398 LINDLEY DR  SACRAMENTO  95815    CA     4      2    1744

             Type   Sale_date   Price   Latitude   Longitude
527  Multi-Family  2008-05-19  416767  38.622359 -121.457582
('Residential', 1551)                    Street     City    Zip State  Beds  Baths  Sq__ft  \
865  3720 VISTA DE MADERA  LINCOLN  95648    CA     3      3       0

            Type   Sale_date  Price   Latitude   Longitude
865  Residential  2008-05-16   1551  38.851645 -121.231742
('Residential', 2000)              Street         City    Zip State  Beds  Baths  Sq__ft  \
866  14151 INDIO DR  SLOUGHHOUSE  95683    CA     3      4    5822

            Type   Sale_date  Price   Latitude   Longitude
866  Residential  2008-05-16   2000  38.490447 -121.129337
('Residential', 4897)                   Street     City    Zip State  Beds  Baths  Sq__ft  \
554   20 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
555   24 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
556   28 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
557   32 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
558   36 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
559   40 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
560   44 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
561   48 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
562   52 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
563   68 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
564   72 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
565   76 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
566   80 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
567   84 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
568   88 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
569   92 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
570   96 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
571  100 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
572           434 1ST ST  LINCOLN  95648    CA     0      0       0
573               3 E ST  LINCOLN  95648    CA     0      0       0
574              11 E ST  LINCOLN  95648    CA     0      0       0
575              19 E ST  LINCOLN  95648    CA     0      0       0
576              27 E ST  LINCOLN  95648    CA     0      0       0
577              35 E ST  LINCOLN  95648    CA     0      0       0
578              43 E ST  LINCOLN  95648    CA     0      0       0
579              51 E ST  LINCOLN  95648    CA     4      2       0
580              59 E ST  LINCOLN  95648    CA     3      2       0
581              75 E ST  LINCOLN  95648    CA     3      2       0
582   63 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
583           398 1ST ST  LINCOLN  95648    CA     0      0       0
584           386 1ST ST  LINCOLN  95648    CA     0      0       0
585           374 1ST ST  LINCOLN  95648    CA     0      0       0
586  116 CRYSTALWOOD WAY  LINCOLN  95648    CA     0      0       0
587  108 CRYSTALWOOD WAY  LINCOLN  95648    CA     0      0       0
588  100 CRYSTALWOOD WAY  LINCOLN  95648    CA     0      0       0
589   55 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
590   51 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
591   47 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
592   43 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
593   39 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
594   35 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
595   31 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
596   27 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
597   23 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
598   19 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
599   15 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
600    7 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
601    7 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0
602    3 CRYSTALWOOD CIR  LINCOLN  95648    CA     0      0       0

            Type   Sale_date  Price   Latitude   Longitude
554  Residential  2008-05-19   4897  38.885327 -121.289412
555  Residential  2008-05-19   4897  38.885132 -121.289405
556  Residential  2008-05-19   4897  38.884936 -121.289397
557  Residential  2008-05-19   4897  38.884741 -121.289390
558  Residential  2008-05-19   4897  38.884599 -121.289406
559  Residential  2008-05-19   4897  38.884535 -121.289619
560  Residential  2008-05-19   4897  38.884590 -121.289835
561  Residential  2008-05-19   4897  38.884667 -121.289896
562  Residential  2008-05-19   4897  38.884780 -121.289911
563  Residential  2008-05-19   4897  38.885236 -121.289928
564  Residential  2008-05-19   4897  38.885350 -121.289926
565  Residential  2008-05-19   4897  38.885464 -121.289922
566  Residential  2008-05-19   4897  38.885578 -121.289919
567  Residential  2008-05-19   4897  38.885692 -121.289915
568  Residential  2008-05-19   4897  38.885806 -121.289911
569  Residential  2008-05-19   4897  38.885920 -121.289908
570  Residential  2008-05-19   4897  38.886024 -121.289859
571  Residential  2008-05-19   4897  38.886091 -121.289744
572  Residential  2008-05-19   4897  38.886530 -121.289406
573  Residential  2008-05-19   4897  38.884692 -121.290288
574  Residential  2008-05-19   4897  38.884879 -121.290257
575  Residential  2008-05-19   4897  38.885017 -121.290262
576  Residential  2008-05-19   4897  38.885173 -121.290270
577  Residential  2008-05-19   4897  38.885328 -121.290275
578  Residential  2008-05-19   4897  38.885483 -121.290277
579  Residential  2008-05-19   4897  38.885638 -121.290279
580  Residential  2008-05-19   4897  38.885794 -121.290281
581  Residential  2008-05-19   4897  38.886104 -121.290285
582  Residential  2008-05-19   4897  38.885093 -121.289932
583  Residential  2008-05-19   4897  38.886530 -121.288952
584  Residential  2008-05-19   4897  38.886528 -121.288869
585  Residential  2008-05-19   4897  38.886525 -121.288787
586  Residential  2008-05-19   4897  38.886282 -121.289586
587  Residential  2008-05-19   4897  38.886282 -121.289646
588  Residential  2008-05-19   4897  38.886282 -121.289706
589  Residential  2008-05-19   4897  38.884865 -121.289922
590  Residential  2008-05-19   4897  38.884752 -121.289907
591  Residential  2008-05-19   4897  38.884638 -121.289893
592  Residential  2008-05-19   4897  38.884568 -121.289784
593  Residential  2008-05-19   4897  38.884546 -121.289562
594  Residential  2008-05-19   4897  38.884645 -121.289397
595  Residential  2008-05-19   4897  38.884790 -121.289392
596  Residential  2008-05-19   4897  38.884985 -121.289399
597  Residential  2008-05-19   4897  38.885181 -121.289406
598  Residential  2008-05-19   4897  38.885376 -121.289414
599  Residential  2008-05-19   4897  38.885571 -121.289421
600  Residential  2008-05-19   4897  38.885962 -121.289436
601  Residential  2008-05-19   4897  38.885962 -121.289436
602  Residential  2008-05-19   4897  38.886093 -121.289584
('Residential', 30000)                 Street            City    Zip State  Beds  Baths  Sq__ft  \
603  8208 WOODYARD WAY  CITRUS HEIGHTS  95621    CA     3      2    1166
604    113 RINETTI WAY       RIO LINDA  95673    CA     0      0       0

            Type   Sale_date  Price   Latitude   Longitude
603  Residential  2008-05-16  30000  38.715322 -121.314787
604  Residential  2008-05-16  30000  38.687172 -121.463933
('Residential', 55422)           Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
605  15 LOORZ CT  SACRAMENTO  95823    CA     2      1     838  Residential

      Sale_date  Price   Latitude   Longitude
605  2008-05-16  55422  38.471646 -121.435158
('Residential', 56950)              Street        City    Zip State  Beds  Baths  Sq__ft  \
867  7401 TOULON LN  SACRAMENTO  95828    CA     4      2    1512

            Type   Sale_date  Price   Latitude   Longitude
867  Residential  2008-05-15  56950  38.488628 -121.387759
('Residential', 59222)          Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
0  3526 HIGH ST  SACRAMENTO  95838    CA     2      1     836  Residential

    Sale_date  Price   Latitude   Longitude
0  2008-05-21  59222  38.631913 -121.434879
('Residential', 61000)               Street        City    Zip State  Beds  Baths  Sq__ft  \
869  5937 BAMFORD DR  SACRAMENTO  95823    CA     2      1     876

            Type   Sale_date  Price   Latitude   Longitude
869  Residential  2008-05-15  61000  38.471139 -121.432255
('Residential', 61500)               Street        City    Zip State  Beds  Baths  Sq__ft  \
337  261 REDONDO AVE  SACRAMENTO  95815    CA     3      1     970

            Type   Sale_date  Price   Latitude   Longitude
337  Residential  2008-05-19  61500  38.620685 -121.460539
('Residential', 62050)             Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
338  4030 BROADWAY  SACRAMENTO  95817    CA     2      1     623  Residential

      Sale_date  Price   Latitude   Longitude
338  2008-05-19  62050  38.546798 -121.460038
('Residential', 63000)               Street             City    Zip State  Beds  Baths  Sq__ft  \
606  5805 DOTMAR WAY  NORTH HIGHLANDS  95660    CA     2      1     904

            Type   Sale_date  Price   Latitude   Longitude
606  Residential  2008-05-16  63000  38.672642 -121.380343
('Residential', 65000)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
339      3660 22ND AVE  SACRAMENTO  95820    CA     2      1     932
340       3924 HIGH ST  SACRAMENTO  95838    CA     2      1     796
607  2332 CAMBRIDGE ST  SACRAMENTO  95815    CA     2      1    1032
608     3812 BELDEN ST  SACRAMENTO  95838    CA     2      1     904
609       3348 40TH ST  SACRAMENTO  95817    CA     2      1    1080

            Type   Sale_date  Price   Latitude   Longitude
339  Residential  2008-05-19  65000  38.532718 -121.467470
340  Residential  2008-05-19  65000  38.638797 -121.435049
607  Residential  2008-05-16  65000  38.608085 -121.449651
608  Residential  2008-05-16  65000  38.636833 -121.441640
609  Residential  2008-05-16  65000  38.544162 -121.460652
('Residential', 66500)              Street        City    Zip State  Beds  Baths  Sq__ft  \
610  127 QUASAR CIR  SACRAMENTO  95822    CA     2      2     990

            Type   Sale_date  Price   Latitude   Longitude
610  Residential  2008-05-16  66500  38.493504 -121.475304
('Residential', 68000)             Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
341  4734 14TH AVE  SACRAMENTO  95820    CA     2      1     834  Residential
342  4734 14TH AVE  SACRAMENTO  95820    CA     2      1     834  Residential

      Sale_date  Price   Latitude   Longitude
341  2008-05-19  68000  38.539447 -121.450858
342  2008-05-19  68000  38.539447 -121.450858
('Residential', 68212)         Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
1  51 OMAHA CT  SACRAMENTO  95823    CA     3      1    1167  Residential

    Sale_date  Price   Latitude   Longitude
1  2008-05-21  68212  38.478902 -121.431028
('Residential', 68566)            Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
871  3920 39TH ST  SACRAMENTO  95820    CA     2      1     864  Residential

      Sale_date  Price   Latitude  Longitude
871  2008-05-15  68566  38.539213 -121.46393
('Residential', 68880)            Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
2  2796 BRANCH ST  SACRAMENTO  95815    CA     2      1     796  Residential

    Sale_date  Price   Latitude   Longitude
2  2008-05-21  68880  38.618305 -121.443839
('Residential', 69307)              Street        City    Zip State  Beds  Baths  Sq__ft  \
3  2805 JANETTE WAY  SACRAMENTO  95815    CA     2      1     852

          Type   Sale_date  Price   Latitude   Longitude
3  Residential  2008-05-21  69307  38.616835 -121.439146
('Residential', 70000)              Street        City    Zip State  Beds  Baths  Sq__ft  \
159       3432 Y ST  SACRAMENTO  95817    CA     4      2    1099
872  701 JESSIE AVE  SACRAMENTO  95838    CA     2      1    1011

            Type   Sale_date  Price   Latitude   Longitude
159  Residential  2008-05-20  70000  38.554967 -121.468046
872  Residential  2008-05-15  70000  38.643978 -121.449562
('Residential', 71000)               Street        City    Zip State  Beds  Baths  Sq__ft  \
611  3812 CYPRESS ST  SACRAMENTO  95838    CA     2      1     900

            Type   Sale_date  Price   Latitude   Longitude
611  Residential  2008-05-16  71000  38.636877 -121.444948

('Residential', 75000)            Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
612  5821 64TH ST  SACRAMENTO  95824    CA     2      1     861  Residential

      Sale_date  Price   Latitude   Longitude
612  2008-05-16  75000  38.521202 -121.428146
('Residential', 78000)            Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
161  3132 CLAY ST  SACRAMENTO  95815    CA     2      1     800  Residential

      Sale_date  Price   Latitude   Longitude
161  2008-05-20  78000  38.624678 -121.439203
('Residential', 78400)             Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
162  5221 38TH AVE  SACRAMENTO  95824    CA     2      1     746  Residential

      Sale_date  Price   Latitude   Longitude
162  2008-05-20  78400  38.518044 -121.443555
('Residential', 80000)               Street        City    Zip State  Beds  Baths  Sq__ft  \
163  6112 HERMOSA ST  SACRAMENTO  95822    CA     3      1    1067
873   83 ARCADE BLVD  SACRAMENTO  95815    CA     4      2    1158

            Type   Sale_date  Price   Latitude   Longitude
163  Residential  2008-05-20  80000  38.515125 -121.480416
873  Residential  2008-05-15  80000  38.618716 -121.466327
('Residential', 81900)             Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
4  6001 MCMAHON DR  SACRAMENTO  95824    CA     2      1     797  Residential

    Sale_date  Price  Latitude   Longitude
4  2008-05-21  81900  38.51947 -121.435768
('Residential', 84000)           Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
345  3845 ELM ST  SACRAMENTO  95838    CA     3      1    1250  Residential

      Sale_date  Price   Latitude   Longitude
345  2008-05-19  84000  38.637337 -121.432835
('Residential', 84675)             Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
346  3908 17TH AVE  SACRAMENTO  95820    CA     2      1     984  Residential

      Sale_date  Price  Latitude   Longitude
346  2008-05-19  84675  38.53728 -121.463531
('Residential', 85000)                Street        City    Zip State  Beds  Baths  Sq__ft  \
347  7109 CHANDLER DR  SACRAMENTO  95828    CA     3      1    1013
614   1171 SONOMA AVE  SACRAMENTO  95815    CA     2      1    1011

            Type   Sale_date  Price   Latitude   Longitude
347  Residential  2008-05-19  85000  38.497237 -121.424187
614  Residential  2008-05-16  85000  38.623800 -121.439872
('Residential', 85500)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
874  601 REGGINALD WAY  SACRAMENTO  95838    CA     3      2    1092

            Type   Sale_date  Price  Latitude   Longitude
874  Residential  2008-05-15  85500  38.64472 -121.452228
('Residential', 89000)               Street        City    Zip State  Beds  Baths  Sq__ft  \
164  483 ARCADE BLVD  SACRAMENTO  95815    CA     4      2    1316

            Type   Sale_date  Price   Latitude   Longitude
164  Residential  2008-05-20  89000  38.623571 -121.454884
('Residential', 90000)                Street        City    Zip State  Beds  Baths  Sq__ft  \
165    671 SONOMA AVE  SACRAMENTO  95815    CA     3      1    1337
166      5980 79TH ST  SACRAMENTO  95824    CA     2      1     868
348  7541 SKELTON WAY  SACRAMENTO  95822    CA     3      1    1012

            Type   Sale_date  Price   Latitude   Longitude
165  Residential  2008-05-20  90000  38.622953 -121.450142
166  Residential  2008-05-20  90000  38.518373 -121.411779
348  Residential  2008-05-19  90000  38.484274 -121.488851
('Residential', 90895)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
6  6048 OGDEN NASH WAY  SACRAMENTO  95842    CA     3      2    1104

          Type   Sale_date  Price   Latitude   Longitude
6  Residential  2008-05-21  90895  38.681659 -121.351705
('Residential', 91000)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
350  1016 CONGRESS AVE  SACRAMENTO  95838    CA     2      2     918

            Type   Sale_date  Price   Latitude   Longitude
350  Residential  2008-05-19  91000  38.630151 -121.442789
('Residential', 91002)           Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
7  2561 19TH AVE  SACRAMENTO  95820    CA     3      1    1177  Residential

    Sale_date  Price   Latitude   Longitude
7  2008-05-21  91002  38.535092 -121.481367
('Residential', 92000)                   Street        City    Zip State  Beds  Baths  Sq__ft  \
167  7607 ELDER CREEK RD  SACRAMENTO  95824    CA     3      1     924

            Type   Sale_date  Price  Latitude   Longitude
167  Residential  2008-05-20  92000  38.51055 -121.414768
('Residential', 93600)               Street        City    Zip State  Beds  Baths  Sq__ft  \
876  4113 DAYSTAR CT  SACRAMENTO  95824    CA     2      2    1139

            Type   Sale_date  Price   Latitude   Longitude
876  Residential  2008-05-15  93600  38.520469 -121.458606
('Residential', 93675)             Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
168  5028 14TH AVE  SACRAMENTO  95820    CA     2      1     610  Residential

      Sale_date  Price  Latitude   Longitude
168  2008-05-20  93675  38.53942 -121.446894
('Residential', 95000)                Street        City    Zip State  Beds  Baths  Sq__ft  \
351  540 MORRISON AVE  SACRAMENTO  95838    CA     3      1    1082
877  7374 TISDALE WAY  SACRAMENTO  95822    CA     3      1    1058

            Type   Sale_date  Price   Latitude   Longitude
351  Residential  2008-05-19  95000  38.637704 -121.453946
877  Residential  2008-05-15  95000  38.488238 -121.472561
('Residential', 95625)                Street        City    Zip State  Beds  Baths  Sq__ft  \
615  4250 ARDWELL WAY  SACRAMENTO  95823    CA     3      2    1089

            Type   Sale_date  Price   Latitude   Longitude
615  Residential  2008-05-16  95625  38.466938 -121.455631
('Residential', 96140)            Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
616  3104 CLAY ST  SACRAMENTO  95815    CA     2      1     832  Residential

      Sale_date  Price  Latitude   Longitude
616  2008-05-16  96140  38.62391 -121.439208
('Residential', 97500)                Street        City    Zip State  Beds  Baths  Sq__ft  \
352  5303 JERRETT WAY  SACRAMENTO  95842    CA     2      1     964

            Type   Sale_date  Price   Latitude   Longitude
352  Residential  2008-05-19  97500  38.663282 -121.359631
('Residential', 97750)                   Street            City    Zip State  Beds  Baths  Sq__ft  \
169     14788 NATCHEZ CT  RANCHO MURIETA  95683    CA     0      0       0
878  3348 RIO LINDA BLVD      SACRAMENTO  95838    CA     3      2    1040

            Type   Sale_date  Price   Latitude   Longitude
169  Residential  2008-05-20  97750  38.492287 -121.100032
878  Residential  2008-05-15  97750  38.628842 -121.446127
('Residential', 98000)               Street        City    Zip State  Beds  Baths  Sq__ft  \
170  1069 ACACIA AVE  SACRAMENTO  95815    CA     2      1    1220

            Type   Sale_date  Price   Latitude   Longitude
170  Residential  2008-05-20  98000  38.621998 -121.442238
('Residential', 98937)          Street       City    Zip State  Beds  Baths  Sq__ft         Type  \
9  7325 10TH ST  RIO LINDA  95673    CA     3      2    1146  Residential

    Sale_date  Price   Latitude   Longitude
9  2008-05-21  98937  38.700909 -121.442979
('Residential', 99000)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
172  3847 LAS PASAS WAY  SACRAMENTO  95864    CA     3      1    1643

            Type   Sale_date  Price   Latitude   Longitude
172  Residential  2008-05-20  99000  38.588672 -121.373916
('Residential', 100309)               Street        City    Zip State  Beds  Baths  Sq__ft  \
10  645 MORRISON AVE  SACRAMENTO  95838    CA     3      2     909

           Type   Sale_date   Price   Latitude  Longitude
10  Residential  2008-05-21  100309  38.637663 -121.45152
('Residential', 101000)              Street            City    Zip State  Beds  Baths  Sq__ft  \
355  6013 ROWAN WAY  CITRUS HEIGHTS  95621    CA     2      1     888

            Type   Sale_date   Price   Latitude  Longitude
355  Residential  2008-05-19  101000  38.675893  -121.2963
('Residential', 102750)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
356  2987 PONDEROSA LN  SACRAMENTO  95815    CA     4      2    1120

            Type   Sale_date   Price   Latitude   Longitude
356  Residential  2008-05-19  102750  38.622243 -121.457863
('Residential', 104000)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
879  3935 LIMESTONE WAY  SACRAMENTO  95823    CA     3      2    1354

            Type   Sale_date   Price   Latitude   Longitude
879  Residential  2008-05-15  104000  38.484374 -121.463157
('Residential', 105000)                 Street             City    Zip State  Beds  Baths  Sq__ft  \
618  4738 OAKHOLLOW DR       SACRAMENTO  95842    CA     4      2    1292
880   6208 GRATTAN WAY  NORTH HIGHLANDS  95660    CA     3      1    1051

            Type   Sale_date   Price   Latitude   Longitude
618  Residential  2008-05-16  105000  38.679598 -121.356035
880  Residential  2008-05-15  105000  38.679279 -121.376615
('Residential', 106250)            Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
11  4085 FAWN CIR  SACRAMENTO  95823    CA     3      2    1289  Residential

     Sale_date   Price   Latitude   Longitude
11  2008-05-21  106250  38.470746 -121.458918
('Residential', 106716)                  Street  City    Zip State  Beds  Baths  Sq__ft         Type  \
174  1121 CREEKSIDE WAY  GALT  95632    CA     3      1    1080  Residential

      Sale_date   Price   Latitude   Longitude
174  2008-05-20  106716  38.241514 -121.312199
('Residential', 106852)              Street        City    Zip State  Beds  Baths  Sq__ft  \
12  2930 LA ROSA RD  SACRAMENTO  95815    CA     1      1     871

           Type   Sale_date   Price   Latitude   Longitude
12  Residential  2008-05-21  106852  38.618698 -121.435833
('Residential', 107502)            Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
13  2113 KIRK WAY  SACRAMENTO  95822    CA     3      1    1020  Residential

     Sale_date   Price   Latitude   Longitude
13  2008-05-21  107502  38.482215 -121.492603
('Residential', 108000)                Street        City    Zip State  Beds  Baths  Sq__ft  \
619  1401 STERLING ST  SACRAMENTO  95822    CA     2      1     810

            Type   Sale_date   Price   Latitude   Longitude
619  Residential  2008-05-16  108000  38.520319 -121.504727
('Residential', 108750)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
14  4533 LOCH HAVEN WAY  SACRAMENTO  95842    CA     2      2    1022

           Type   Sale_date   Price   Latitude  Longitude
14  Residential  2008-05-21  108750  38.672914 -121.35934
('Residential', 109000)               Street        City    Zip State  Beds  Baths  Sq__ft  \
620  3715 DIDCOT CIR  SACRAMENTO  95838    CA     4      2    1064
882    4225 46TH AVE  SACRAMENTO  95824    CA     3      1    1161

            Type   Sale_date   Price   Latitude   Longitude
620  Residential  2008-05-16  109000  38.635232 -121.460098
882  Residential  2008-05-15  109000  38.511893 -121.457676
('Residential', 110000)               Street             City    Zip State  Beds  Baths  Sq__ft  \
883    1434 BELL AVE       SACRAMENTO  95838    CA     3      1    1004
884  5628 GEORGIA DR  NORTH HIGHLANDS  95660    CA     3      1    1229

            Type   Sale_date   Price   Latitude   Longitude
883  Residential  2008-05-15  110000  38.647398 -121.432914
884  Residential  2008-05-15  110000  38.669587 -121.379879
('Residential', 111000)                   Street             City    Zip State  Beds  Baths  Sq__ft  \
175    5307 CABRILLO WAY       SACRAMENTO  95820    CA     3      1    1039
176  3725 DON JULIO BLVD  NORTH HIGHLANDS  95660    CA     3      1    1051

            Type   Sale_date   Price  Latitude   Longitude
175  Residential  2008-05-20  111000  38.52712 -121.435348
176  Residential  2008-05-20  111000  38.67895 -121.379406
('Residential', 112500)                   Street             City    Zip State  Beds  Baths  Sq__ft  \
357  3732 LANKERSHIM WAY  NORTH HIGHLANDS  95660    CA     3      1    1331
885         7629 BETH ST       SACRAMENTO  95832    CA     3      2    1249

            Type   Sale_date   Price   Latitude   Longitude
357  Residential  2008-05-19  112500  38.689720 -121.378399
885  Residential  2008-05-15  112500  38.480126 -121.487869
('Residential', 113000)              Street        City    Zip State  Beds  Baths  Sq__ft  \
358  2216 DUNLAP DR  SACRAMENTO  95821    CA     3      1    1014

            Type   Sale_date   Price   Latitude  Longitude
358  Residential  2008-05-19  113000  38.623738 -121.41305
('Residential', 113263)          Street       City    Zip State  Beds  Baths  Sq__ft         Type  \
16  6715 6TH ST  RIO LINDA  95673    CA     2      1     844  Residential

     Sale_date   Price   Latitude   Longitude
16  2008-05-21  113263  38.689591 -121.452239
('Residential', 114000)               Street        City    Zip State  Beds  Baths  Sq__ft  \
359    3503 21ST AVE  SACRAMENTO  95820    CA     4      2    1448
360  523 EXCHANGE ST  SACRAMENTO  95838    CA     3      1     966

            Type   Sale_date   Price   Latitude   Longitude
359  Residential  2008-05-19  114000  38.533610 -121.469308
360  Residential  2008-05-19  114000  38.659414 -121.454080
('Residential', 114750)                    Street        City    Zip State  Beds  Baths  Sq__ft  \
361  8101 PORT ROYALE WAY  SACRAMENTO  95823    CA     2      1     779

            Type   Sale_date   Price   Latitude   Longitude
361  Residential  2008-05-19  114750  38.463929 -121.438667
('Residential', 114800)                Street        City    Zip State  Beds  Baths  Sq__ft  \
177   4803 MCCLOUD DR  SACRAMENTO  95842    CA     2      2     967
886  2277 BABETTE WAY  SACRAMENTO  95832    CA     3      2    1161

            Type   Sale_date   Price   Latitude   Longitude
177  Residential  2008-05-20  114800  38.682279 -121.352817
886  Residential  2008-05-15  114800  38.479593 -121.484340
('Residential', 115000)               Street            City    Zip State  Beds  Baths  Sq__ft  \
621  2426 RASHAWN DR  RANCHO CORDOVA  95670    CA     2      1     911

            Type   Sale_date   Price   Latitude   Longitude
621  Residential  2008-05-16  115000  38.610852 -121.273278
('Residential', 115500)             Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
623  3409 VIRGO ST  SACRAMENTO  95827    CA     3      2    1320  Residential

      Sale_date   Price   Latitude   Longitude
623  2008-05-16  115500  38.563402 -121.327747
('Residential', 115620)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
624  1110 PINEDALE AVE  SACRAMENTO  95838    CA     3      2    1410

            Type   Sale_date   Price   Latitude   Longitude
624  Residential  2008-05-16  115620  38.660173 -121.440216
('Residential', 116000)                    Street            City    Zip State  Beds  Baths  Sq__ft  \
625       2361 LA LOMA DR  RANCHO CORDOVA  95670    CA     3      2    1115
887  6561 WEATHERFORD WAY      SACRAMENTO  95823    CA     3      1    1010

            Type   Sale_date   Price   Latitude   Longitude
625  Residential  2008-05-16  116000  38.593680 -121.316054
887  Residential  2008-05-15  116000  38.465551 -121.426610
('Residential', 116100)                   Street        City    Zip State  Beds  Baths  Sq__ft  \
364  7876 BURLINGTON WAY  SACRAMENTO  95832    CA     3      1    1174

            Type   Sale_date   Price   Latitude   Longitude
364  Residential  2008-05-19  116100  38.470093 -121.468347
('Residential', 119250)              Street             City    Zip State  Beds  Baths  Sq__ft  \
365  3726 JONKO AVE  NORTH HIGHLANDS  95660    CA     3      2    1207

            Type   Sale_date   Price   Latitude   Longitude
365  Residential  2008-05-19  119250  38.656131 -121.377265
('Residential', 120000)                Street        City    Zip State  Beds  Baths  Sq__ft  \
18    250 PERALTA AVE  SACRAMENTO  95833    CA     2      1     588
367  2610 PHYLLIS AVE  SACRAMENTO  95820    CA     2      1     804

            Type   Sale_date   Price   Latitude   Longitude
18   Residential  2008-05-21  120000  38.612099 -121.469095
367  Residential  2008-05-19  120000  38.531050 -121.479574
('Residential', 120108)                      Street            City    Zip State  Beds  Baths  Sq__ft  \
178    10542 SILVERWOOD WAY  RANCHO CORDOVA  95670    CA     3      1    1098
369  4621 COUNTRY SCENE WAY      SACRAMENTO  95823    CA     3      2    1366

            Type   Sale_date   Price   Latitude   Longitude
178  Residential  2008-05-20  120108  38.587156 -121.295778
369  Residential  2008-05-19  120108  38.470187 -121.448149
('Residential', 121500)                    Street        City    Zip State  Beds  Baths  Sq__ft  \
370  5380 VILLAGE WOOD DR  SACRAMENTO  95823    CA     2      2     901
889        5136 CABOT CIR  SACRAMENTO  95820    CA     4      2    1462

            Type   Sale_date   Price   Latitude   Longitude
370  Residential  2008-05-19  121500  38.454949 -121.440578
889  Residential  2008-05-15  121500  38.528479 -121.411806
('Residential', 121630)              Street       City    Zip State  Beds  Baths  Sq__ft         Type  \
19  113 LEEWILL AVE  RIO LINDA  95673    CA     3      2    1356  Residential

     Sale_date   Price   Latitude  Longitude
19  2008-05-21  121630  38.689999 -121.46322
('Residential', 121725)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
371  2621 EVERGREEN ST  SACRAMENTO  95815    CA     3      1     696

            Type   Sale_date   Price   Latitude   Longitude
371  Residential  2008-05-19  121725  38.613103 -121.444085
('Residential', 122000)                  Street            City    Zip State  Beds  Baths  Sq__ft  \
20   6118 STONEHAND AVE  CITRUS HEIGHTS  95621    CA     3      2    1118
372        201 CARLO CT            GALT  95632    CA     3      2    1080
626       1455 64TH AVE      SACRAMENTO  95822    CA     3      2    1169
890   7730 ROBINETTE RD      SACRAMENTO  95828    CA     3      2    1269

            Type   Sale_date   Price   Latitude   Longitude
20   Residential  2008-05-21  122000  38.707851 -121.320707
372  Residential  2008-05-19  122000  38.242270 -121.310320
626  Residential  2008-05-16  122000  38.492177 -121.503392
890  Residential  2008-05-15  122000  38.477090 -121.410569
('Residential', 122500)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
627  7328 SPRINGMAN ST  SACRAMENTO  95822    CA     3      2    1164

            Type   Sale_date   Price   Latitude   Longitude
627  Residential  2008-05-16  122500  38.491991 -121.477636
('Residential', 122682)                Street        City    Zip State  Beds  Baths  Sq__ft  \
21  4882 BANDALIN WAY  SACRAMENTO  95823    CA     4      2    1329

           Type   Sale_date   Price   Latitude   Longitude
21  Residential  2008-05-21  122682  38.468173 -121.444071
('Residential', 123000)                   Street             City    Zip State  Beds  Baths  Sq__ft  \
22       7511 OAKVALE CT  NORTH HIGHLANDS  95660    CA     4      2    1240
373         6743 21ST ST       SACRAMENTO  95822    CA     3      2    1104
628  119 SAINT MARIE CIR       SACRAMENTO  95823    CA     4      2    1341

            Type   Sale_date   Price   Latitude   Longitude
22   Residential  2008-05-21  123000  38.702792 -121.382210
373  Residential  2008-05-19  123000  38.503720 -121.490657
628  Residential  2008-05-16  123000  38.481454 -121.446644
('Residential', 123225)             Street        City    Zip State  Beds  Baths  Sq__ft         Type  \

('Residential', 140000)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
188  3174 NORTHVIEW DR  SACRAMENTO  95833    CA     3      1    1080
189    840 TRANQUIL LN        GALT  95632    CA     3      2    1266
384   2421 SANTINA WAY     ELVERTA  95626    CA     3      2    1416
638      2931 HOWE AVE  SACRAMENTO  95821    CA     3      1    1264

            Type   Sale_date   Price   Latitude   Longitude
188  Residential  2008-05-20  140000  38.623817 -121.477827
189  Residential  2008-05-20  140000  38.270617 -121.299205
384  Residential  2008-05-19  140000  38.718650 -121.407763
638  Residential  2008-05-16  140000  38.619012 -121.415329
('Residential', 140800)              Street        City    Zip State  Beds  Baths  Sq__ft  \
385  2368 CRAIG AVE  SACRAMENTO  95832    CA     3      2    1300

            Type   Sale_date   Price  Latitude  Longitude
385  Residential  2008-05-19  140800  38.47807 -121.48114
('Residential', 142000)               Street      City    Zip State  Beds  Baths  Sq__ft         Type  \
902  3604 KODIAK WAY  ANTELOPE  95843    CA     3      2    1206  Residential

      Sale_date   Price   Latitude   Longitude
902  2008-05-15  142000  38.706175 -121.379776
('Residential', 143012)                Street        City    Zip State  Beds  Baths  Sq__ft  \
903  2149 COTTAGE WAY  SACRAMENTO  95825    CA     3      1    1285

            Type   Sale_date   Price   Latitude   Longitude
903  Residential  2008-05-15  143012  38.603593 -121.417011
('Residential', 143500)               Street        City    Zip State  Beds  Baths  Sq__ft  \
191  1035 MILLET WAY  SACRAMENTO  95834    CA     3      2    1202

            Type   Sale_date   Price   Latitude  Longitude
191  Residential  2008-05-20  143500  38.631056 -121.48508
('Residential', 145000)                      Street        City    Zip State  Beds  Baths  Sq__ft  \
193           3328 22ND AVE  SACRAMENTO  95820    CA     2      1     722
194       8001 HARTWICK WAY  SACRAMENTO  95828    CA     4      2    1448
195       7812 HARTWICK WAY  SACRAMENTO  95828    CA     3      2    1188
386         2123 AMANDA WAY  SACRAMENTO  95822    CA     3      2    1120
639          5531 JANSEN DR  SACRAMENTO  95824    CA     3      1    1060
640  7836 ORCHARD WOODS CIR  SACRAMENTO  95828    CA     2      2    1132

            Type   Sale_date   Price   Latitude   Longitude
193  Residential  2008-05-20  145000  38.532727 -121.470783
194  Residential  2008-05-20  145000  38.488623 -121.410582
195  Residential  2008-05-20  145000  38.488611 -121.412808
386  Residential  2008-05-19  145000  38.484896 -121.486948
639  Residential  2008-05-16  145000  38.522015 -121.438713
640  Residential  2008-05-16  145000  38.479550 -121.410867
('Residential', 145846)                    Street        City    Zip State  Beds  Baths  Sq__ft  \
904  8632 PRAIRIEWOODS DR  SACRAMENTO  95828    CA     3      2    1543

            Type   Sale_date   Price   Latitude   Longitude
904  Residential  2008-05-15  145846  38.477563 -121.384382
('Residential', 146000)                Street             City    Zip State  Beds  Baths  Sq__ft  \
196  4207 PAINTER WAY  NORTH HIGHLANDS  95660    CA     4      2    1183

            Type   Sale_date   Price   Latitude   Longitude
196  Residential  2008-05-20  146000  38.692915 -121.367497
('Residential', 146250)                   Street        City    Zip State  Beds  Baths  Sq__ft  \
35  3920 SHINING STAR DR  SACRAMENTO  95823    CA     3      2    1418

           Type   Sale_date   Price  Latitude   Longitude
35  Residential  2008-05-21  146250  38.48742 -121.462459
('Residential', 147000)              Street             City    Zip State  Beds  Baths  Sq__ft  \
387  7620 DARLA WAY       SACRAMENTO  95828    CA     4      2    1590
905  612 STONE BLVD  WEST SACRAMENTO  95691    CA     2      1     884

            Type   Sale_date   Price   Latitude   Longitude
387  Residential  2008-05-19  147000  38.478502 -121.403517
905  Residential  2008-05-15  147000  38.563084 -121.535579
('Residential', 147308)              Street             City    Zip State  Beds  Baths  Sq__ft  \
36  5031 CORVAIR ST  NORTH HIGHLANDS  95660    CA     3      2    1082

           Type   Sale_date   Price   Latitude   Longitude
36  Residential  2008-05-21  147308  38.658246 -121.375469
('Residential', 148500)                Street        City    Zip State  Beds  Baths  Sq__ft  \
197  7458 WINKLEY WAY  SACRAMENTO  95822    CA     3      1    1320

            Type   Sale_date   Price   Latitude   Longitude
197  Residential  2008-05-20  148500  38.487444 -121.491366
('Residential', 148750)              Street        City    Zip State  Beds  Baths  Sq__ft  \
37   7661 NIXOS WAY  SACRAMENTO  95823    CA     4      2    1472
906   4180 12TH AVE  SACRAMENTO  95817    CA     3      1    1019

            Type   Sale_date   Price   Latitude   Longitude
37   Residential  2008-05-21  148750  38.479553 -121.463317
906  Residential  2008-05-15  148750  38.541170 -121.458129
('Residential', 149000)                      Street        City    Zip State  Beds  Baths  Sq__ft  \
198  8354 SUNRISE WOODS WAY  SACRAMENTO  95828    CA     3      2    1117

            Type   Sale_date   Price   Latitude  Longitude
198  Residential  2008-05-20  149000  38.473288  -121.3963
('Residential', 149593)              Street        City    Zip State  Beds  Baths  Sq__ft  \
38  7044 CARTHY WAY  SACRAMENTO  95828    CA     4      2    1146

           Type   Sale_date   Price  Latitude   Longitude
38  Residential  2008-05-21  149593  38.49857 -121.420925
('Residential', 149600)                   Street        City    Zip State  Beds  Baths  Sq__ft  \
388  8344 FIELDPOPPY CIR  SACRAMENTO  95828    CA     3      2    1407

            Type   Sale_date   Price   Latitude   Longitude
388  Residential  2008-05-19  149600  38.479083 -121.400702
('Residential', 150000)                    Street        City    Zip State  Beds  Baths  Sq__ft  \
199   8116 COTTONMILL CIR  SACRAMENTO  95828    CA     3      2    1364
200    4660 CEDARWOOD WAY  SACRAMENTO  95823    CA     4      2    1310
389         3624 20TH AVE  SACRAMENTO  95820    CA     5      2    1516
391        2848 PROVO WAY  SACRAMENTO  95822    CA     3      2    1646
641     4055 DEERBROOK DR  SACRAMENTO  95823    CA     3      2    1466
642       9937 BURLINE ST  SACRAMENTO  95827    CA     3      2    1092
907  8025 ARROYO VISTA DR  SACRAMENTO  95823    CA     4      2    1392

            Type   Sale_date   Price   Latitude   Longitude
199  Residential  2008-05-20  150000  38.482876 -121.405912
200  Residential  2008-05-20  150000  38.484834 -121.449316
389  Residential  2008-05-19  150000  38.534508 -121.467907
391  Residential  2008-05-19  150000  38.489759 -121.474754
641  Residential  2008-05-16  150000  38.472117 -121.459589
642  Residential  2008-05-16  150000  38.559641 -121.323160
907  Residential  2008-05-15  150000  38.466540 -121.419029
('Residential', 151000)                Street        City    Zip State  Beds  Baths  Sq__ft  \
643  6948 MIRADOR WAY  SACRAMENTO  95828    CA     4      2    1628

            Type   Sale_date   Price   Latitude  Longitude
643  Residential  2008-05-16  151000  38.493484 -121.42035
('Residential', 151087)             Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
909  8 LA ROCAS CT  SACRAMENTO  95823    CA     3      2    1217  Residential

      Sale_date   Price  Latitude   Longitude
909  2008-05-15  151087  38.46616 -121.448283
('Residential', 152000)                  Street       City    Zip State  Beds  Baths  Sq__ft  \
201  9254 HARROGATE WAY  ELK GROVE  95758    CA     2      2    1006

            Type   Sale_date   Price   Latitude   Longitude
201  Residential  2008-05-20  152000  38.420138 -121.412179
('Residential', 154000)            Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
41  2178 63RD AVE  SACRAMENTO  95822    CA     3      2    1207  Residential

     Sale_date   Price   Latitude  Longitude
41  2008-05-21  154000  38.493955 -121.48966
('Residential', 155000)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
392  6045 EHRHARDT AVE  SACRAMENTO  95823    CA     3      2    1676
644      4909 RUGER CT  SACRAMENTO  95842    CA     3      2     960

            Type   Sale_date   Price   Latitude   Longitude
392  Residential  2008-05-19  155000  38.457157 -121.433065
644  Residential  2008-05-16  155000  38.687470 -121.349234
('Residential', 155435)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
393  1223 LAMBERTON CIR  SACRAMENTO  95838    CA     3      2    1370

            Type   Sale_date   Price   Latitude   Longitude
393  Residential  2008-05-19  155435  38.646677 -121.437573
('Residential', 155500)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
394  1223 LAMBERTON CIR  SACRAMENTO  95838    CA     3      2    1370

            Type   Sale_date   Price   Latitude   Longitude
394  Residential  2008-05-19  155500  38.646677 -121.437573
('Residential', 155800)               Street            City    Zip State  Beds  Baths  Sq__ft  \
645  7204 KERSTEN ST  CITRUS HEIGHTS  95621    CA     3      2    1075

            Type   Sale_date   Price   Latitude   Longitude
645  Residential  2008-05-16  155800  38.695863 -121.300814
('Residential', 156000)                  Street            City    Zip State  Beds  Baths  Sq__ft  \
202   6716 TAREYTON WAY  CITRUS HEIGHTS  95621    CA     3      2    1104
203     2028 ROBERT WAY      SACRAMENTO  95825    CA     2      1     810
204  9346 AIZENBERG CIR       ELK GROVE  95624    CA     2      2    1123

            Type   Sale_date   Price   Latitude   Longitude
202  Residential  2008-05-20  156000  38.693724 -121.307169
203  Residential  2008-05-20  156000  38.609982 -121.419263
204  Residential  2008-05-20  156000  38.418750 -121.370019
('Residential', 156142)                Street        City    Zip State  Beds  Baths  Sq__ft  \
646  3150 ROSEMONT DR  SACRAMENTO  95826    CA     3      2    1428

            Type   Sale_date   Price   Latitude  Longitude
646  Residential  2008-05-16  156142  38.554927 -121.35521
('Residential', 156896)           Street       City    Zip State  Beds  Baths  Sq__ft         Type  \
42  8718 ELK WAY  ELK GROVE  95624    CA     3      2    1056  Residential

     Sale_date   Price  Latitude   Longitude
42  2008-05-21  156896  38.41653 -121.379653
('Residential', 157296)                 Street      City    Zip State  Beds  Baths  Sq__ft  \
910  8636 LONGSPUR WAY  ANTELOPE  95843    CA     3      2    1670

            Type   Sale_date   Price   Latitude  Longitude
910  Residential  2008-05-15  157296  38.725873 -121.35856
('Residential', 157500)                   Street        City    Zip State  Beds  Baths  Sq__ft  \
911  1941 EXPEDITION WAY  SACRAMENTO  95832    CA     3      2    1302

            Type   Sale_date   Price   Latitude   Longitude
911  Residential  2008-05-15  157500  38.473775 -121.493777
('Residential', 157788)                   Street        City    Zip State  Beds  Baths  Sq__ft  \
205  4524 LOCH HAVEN WAY  SACRAMENTO  95842    CA     2      1     904

            Type   Sale_date   Price  Latitude   Longitude
205  Residential  2008-05-20  157788  38.67273 -121.359645
('Residential', 158000)                   Street             City    Zip State  Beds  Baths  Sq__ft  \
395  6000 BIRCHGLADE WAY   CITRUS HEIGHTS  95621    CA     4      2    1351
396       7204 THOMAS DR  NORTH HIGHLANDS  95660    CA     3      2    1152
647   8200 STEINBECK WAY       SACRAMENTO  95828    CA     4      2    1358

            Type   Sale_date   Price   Latitude   Longitude
395  Residential  2008-05-19  158000  38.701660 -121.323249
396  Residential  2008-05-19  158000  38.697898 -121.377687
647  Residential  2008-05-16  158000  38.474854 -121.404726
('Residential', 160000)                     Street             City    Zip State  Beds  Baths  Sq__ft  \
397      8363 LANGTREE WAY       SACRAMENTO  95823    CA     3      2    1452
398  1675 VERNON ST Unit 8        ROSEVILLE  95678    CA     2      1     990
649    6824 OLIVE TREE WAY   CITRUS HEIGHTS  95610    CA     3      2    1410
912     4351 TURNBRIDGE DR       SACRAMENTO  95823    CA     3      2    1488
913       6513 HOLIDAY WAY  NORTH HIGHLANDS  95660    CA     3      2    1373

            Type   Sale_date   Price   Latitude   Longitude
397  Residential  2008-05-19  160000  38.453560 -121.435959
398  Residential  2008-05-19  160000  38.734136 -121.299639
649  Residential  2008-05-16  160000  38.689239 -121.267737
912  Residential  2008-05-15  160000  38.502034 -121.456027
913  Residential  2008-05-15  160000  38.685361 -121.376938
('Residential', 161250)                  Street            City    Zip State  Beds  Baths  Sq__ft  \
43   5708 RIDGEPOINT DR        ANTELOPE  95843    CA     2      2    1043
914  8321 MISTLETOE WAY  CITRUS HEIGHTS  95621    CA     4      2    1381

            Type   Sale_date   Price   Latitude   Longitude
43   Residential  2008-05-21  161250  38.720270 -121.331555
914  Residential  2008-05-15  161250  38.717738 -121.308322
('Residential', 161500)                   Street             City    Zip State  Beds  Baths  Sq__ft  \
44         7315 KOALA CT  NORTH HIGHLANDS  95660    CA     4      2    1587
650  3536 SUN MAIDEN WAY         ANTELOPE  95843    CA     3      2    1711

            Type   Sale_date   Price   Latitude   Longitude
44   Residential  2008-05-21  161500  38.699251 -121.371414
650  Residential  2008-05-16  161500  38.709680 -121.382328
('Residential', 161600)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
651  4517 OLYMPIAD WAY  SACRAMENTO  95826    CA     4      2    1483

            Type   Sale_date   Price   Latitude   Longitude
651  Residential  2008-05-16  161600  38.536751 -121.359154
('Residential', 161653)                     Street            City    Zip State  Beds  Baths  Sq__ft  \
206  7140 BLUE SPRINGS WAY  CITRUS HEIGHTS  95621    CA     3      2    1156

            Type   Sale_date   Price   Latitude   Longitude
206  Residential  2008-05-20  161653  38.720653 -121.302241
('Residential', 161829)             Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
207  4631 11TH AVE  SACRAMENTO  95820    CA     2      1    1321  Residential

      Sale_date   Price   Latitude   Longitude
207  2008-05-20  161829  38.541965 -121.452132

('Residential', 162000)             Street  City    Zip State  Beds  Baths  Sq__ft         Type  \
652  925 COBDEN CT  GALT  95632    CA     3      2    1140  Residential

      Sale_date   Price   Latitude   Longitude
652  2008-05-16  162000  38.282047 -121.295812
('Residential', 164000)                    Street            City    Zip State  Beds  Baths  Sq__ft  \
45           2622 ERIN DR      SACRAMENTO  95833    CA     4      1    1120
399    6632 IBEX WOODS CT  CITRUS HEIGHTS  95621    CA     2      2    1162
400         117 EVCAR WAY       RIO LINDA  95673    CA     3      2    1182
915  5920 VALLEY GLEN WAY      SACRAMENTO  95823    CA     3      2    1265

            Type   Sale_date   Price   Latitude   Longitude
45   Residential  2008-05-21  164000  38.613765 -121.488694
399  Residential  2008-05-19  164000  38.720868 -121.309855
400  Residential  2008-05-19  164000  38.687659 -121.463300
915  Residential  2008-05-15  164000  38.462821 -121.433135
('Residential', 165000)                     Street             City    Zip State  Beds  Baths  Sq__ft  \
46       8421 SUNBLAZE WAY       SACRAMENTO  95823    CA     4      2    1580
208         3228 BAGGAN CT         ANTELOPE  95843    CA     3      2    1392
401  6485 LAGUNA MIRAGE LN        ELK GROVE  95758    CA     2      2    1112
653     8225 SCOTTSDALE DR       SACRAMENTO  95828    CA     4      2    1549
654          8758 LEMAS RD       SACRAMENTO  95828    CA     3      2    1410
916  2601 SAN FERNANDO WAY       SACRAMENTO  95818    CA     2      1     881
917         501 POPLAR AVE  WEST SACRAMENTO  95691    CA     0      0       0

            Type   Sale_date   Price   Latitude   Longitude
46   Residential  2008-05-21  165000  38.450543 -121.432538
208  Residential  2008-05-20  165000  38.715346 -121.388163
401  Residential  2008-05-19  165000  38.424650 -121.430137
653  Residential  2008-05-16  165000  38.487864 -121.402476
654  Residential  2008-05-16  165000  38.467487 -121.377055
916  Residential  2008-05-15  165000  38.556178 -121.476256
917  Residential  2008-05-15  165000  38.584526 -121.534609
('Residential', 165750)                    Street        City    Zip State  Beds  Baths  Sq__ft  \
918  8008 SAINT HELENA CT  SACRAMENTO  95829    CA     4      2    1608

            Type   Sale_date   Price   Latitude   Longitude
918  Residential  2008-05-15  165750  38.467012 -121.359969
('Residential', 166000)               Street            City    Zip State  Beds  Baths  Sq__ft  \
919  6517 DONEGAL DR  CITRUS HEIGHTS  95621    CA     3      1    1344

            Type   Sale_date   Price   Latitude   Longitude
919  Residential  2008-05-15  166000  38.681554 -121.312934
('Residential', 166357)              Street        City    Zip State  Beds  Baths  Sq__ft  \
47   7420 ALIX PKWY  SACRAMENTO  95823    CA     4      1    1955
48  3820 NATOMA WAY  SACRAMENTO  95838    CA     4      2    1656

           Type   Sale_date   Price   Latitude   Longitude
47  Residential  2008-05-21  166357  38.489405 -121.452811
48  Residential  2008-05-21  166357  38.636748 -121.422159
('Residential', 167000)                   Street  City    Zip State  Beds  Baths  Sq__ft         Type  \
402  746 MOOSE CREEK WAY  GALT  95632    CA     3      2    1100  Residential

      Sale_date   Price   Latitude   Longitude
402  2008-05-19  167000  38.283085 -121.302071
('Residential', 167293)                     Street            City    Zip State  Beds  Baths  Sq__ft  \
403         8306 CURLEW CT  CITRUS HEIGHTS  95621    CA     4      2    1280
404         8306 CURLEW CT  CITRUS HEIGHTS  95621    CA     4      2    1280
655  6121 ALPINESPRING WAY       ELK GROVE  95758    CA     3      2    1240

            Type   Sale_date   Price   Latitude   Longitude
403  Residential  2008-05-19  167293  38.715781 -121.298519
404  Residential  2008-05-19  167293  38.715781 -121.298519
655  Residential  2008-05-16  167293  38.434075 -121.432623
('Residential', 168000)                   Street        City    Zip State  Beds  Baths  Sq__ft  \
49    4431 GREEN TREE DR  SACRAMENTO  95823    CA     3      2    1477
209     8515 DARTFORD DR  SACRAMENTO  95823    CA     3      2    1439
405        5217 ARGO WAY  SACRAMENTO  95820    CA     3      1    1039
656   5937 YORK GLEN WAY  SACRAMENTO  95842    CA     5      2    1712
657  6417 SUNNYFIELD WAY  SACRAMENTO  95823    CA     4      2    1580

            Type   Sale_date   Price   Latitude   Longitude
49   Residential  2008-05-21  168000  38.499954 -121.454469
209  Residential  2008-05-20  168000  38.448288 -121.420719
405  Residential  2008-05-19  168000  38.527740 -121.433669
656  Residential  2008-05-16  168000  38.677003 -121.354454
657  Residential  2008-05-16  168000  38.449153 -121.428272
('Residential', 168750)                    Street        City    Zip State  Beds  Baths  Sq__ft  \
658  4008 GREY LIVERY WAY    ANTELOPE  95843    CA     3      2    1669
659      8920 ROSETTA CIR  SACRAMENTO  95826    CA     3      1    1029

            Type   Sale_date   Price   Latitude   Longitude
658  Residential  2008-05-16  168750  38.718460 -121.370862
659  Residential  2008-05-16  168750  38.544374 -121.370874
('Residential', 169000)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
210   4500 TIPPWOOD WAY  SACRAMENTO  95842    CA     3      2    1159
920  1001 RIO NORTE WAY  SACRAMENTO  95834    CA     3      2    1202

            Type   Sale_date   Price   Latitude   Longitude
210  Residential  2008-05-20  169000  38.699510 -121.359989
920  Residential  2008-05-15  169000  38.634292 -121.485106
('Residential', 170000)                        Street            City    Zip State  Beds  Baths  \
50               9417 SARA ST       ELK GROVE  95624    CA     3      2
406      7108 HEATHER TREE DR      SACRAMENTO  95842    CA     3      2
407        2956 DAVENPORT WAY      SACRAMENTO  95833    CA     4      2
408  10062 LINCOLN VILLAGE DR      SACRAMENTO  95827    CA     3      2
660            8300 LICHEN DR  CITRUS HEIGHTS  95621    CA     3      1
921                  604 P ST         LINCOLN  95648    CA     3      2
924         7740 DIXIE LOU ST      SACRAMENTO  95832    CA     3      2

     Sq__ft         Type   Sale_date   Price   Latitude   Longitude
50     1188  Residential  2008-05-21  170000  38.415518 -121.370527
406    1159  Residential  2008-05-19  170000  38.695677 -121.360220
407    1917  Residential  2008-05-19  170000  38.620687 -121.482619
408    1520  Residential  2008-05-19  170000  38.564000 -121.320023
660    1103  Residential  2008-05-16  170000  38.716410 -121.306239
921    1104  Residential  2008-05-15  170000  38.893168 -121.305398
924    1232  Residential  2008-05-15  170000  38.475853 -121.477039
('Residential', 170250)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
661  8884 AMBERJACK WAY  SACRAMENTO  95828    CA     3      2    2161

            Type   Sale_date   Price   Latitude   Longitude
661  Residential  2008-05-16  170250  38.479343 -121.372553
('Residential', 170725)            Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
925  7342 DAVE ST  SACRAMENTO  95828    CA     3      1    1638  Residential

      Sale_date   Price   Latitude   Longitude
925  2008-05-15  170725  38.490822 -121.401643
('Residential', 171750)                Street        City    Zip State  Beds  Baths  Sq__ft  \
926  7687 HOWERTON DR  SACRAMENTO  95831    CA     2      2    1177

            Type   Sale_date   Price   Latitude   Longitude
926  Residential  2008-05-15  171750  38.480859 -121.539745
('Residential', 172000)            Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
927  26 KAMSON CT  SACRAMENTO  95833    CA     3      2    1582  Residential

      Sale_date   Price   Latitude   Longitude
927  2008-05-15  172000  38.622794 -121.499173
('Residential', 173000)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
51   8299 HALBRITE WAY  SACRAMENTO  95828    CA     4      2    1590
662  4480 VALLEY HI DR  SACRAMENTO  95823    CA     3      2    1650

            Type   Sale_date   Price   Latitude   Longitude
51   Residential  2008-05-21  173000  38.473814 -121.400000
662  Residential  2008-05-16  173000  38.466781 -121.450955
('Residential', 173056)              Street        City    Zip State  Beds  Baths  Sq__ft  \
928  7045 PEEVEY CT  SACRAMENTO  95823    CA     2      2     904

            Type   Sale_date   Price   Latitude   Longitude
928  Residential  2008-05-15  173056  38.502254 -121.451444
('Residential', 174000)                   Street       City    Zip State  Beds  Baths  Sq__ft  \
409        332 PALIN AVE       GALT  95632    CA     3      2    1204
929  8916 GABLES MILL PL  ELK GROVE  95758    CA     3      2    1340

            Type   Sale_date   Price   Latitude   Longitude
409  Residential  2008-05-19  174000  38.260467 -121.302636
929  Residential  2008-05-15  174000  38.433919 -121.422347
('Residential', 174250)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
52   7223 KALLIE KAY LN  SACRAMENTO  95823    CA     3      2    1463
930    1140 EDMONTON DR  SACRAMENTO  95833    CA     3      2    1204

            Type   Sale_date   Price   Latitude   Longitude
52   Residential  2008-05-21  174250  38.477553 -121.419463
930  Residential  2008-05-15  174250  38.624570 -121.486913
('Residential', 174313)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
53  8156 STEINBECK WAY  SACRAMENTO  95828    CA     4      2    1714

           Type   Sale_date   Price   Latitude   Longitude
53  Residential  2008-05-21  174313  38.474853 -121.406326
('Residential', 175000)                 Street            City    Zip State  Beds  Baths  Sq__ft  \
211  2460 EL ROCCO WAY  RANCHO CORDOVA  95670    CA     3      2    1671
663    2250 FOREBAY RD   POLLOCK PINES  95726    CA     3      1    1320

            Type   Sale_date   Price   Latitude   Longitude
211  Residential  2008-05-20  175000  38.591477 -121.315340
663  Residential  2008-05-16  175000  38.774910 -120.597599
('Residential', 176095)                Street        City    Zip State  Beds  Baths  Sq__ft  \
664  3529 FABERGE WAY  SACRAMENTO  95826    CA     3      2    1200

            Type   Sale_date   Price   Latitude   Longitude
664  Residential  2008-05-16  176095  38.553275 -121.346218
('Residential', 176250)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
212   8244 SUNBIRD WAY  SACRAMENTO  95823    CA     3      2    1740
665  1792 DAWNELLE WAY  SACRAMENTO  95835    CA     3      2    1170

            Type   Sale_date   Price   Latitude   Longitude
212  Residential  2008-05-20  176250  38.457654 -121.431381
665  Residential  2008-05-16  176250  38.682710 -121.501697
('Residential', 176850)                  Street       City    Zip State  Beds  Baths  Sq__ft  \
931  8879 APPLE PEAR CT  ELK GROVE  95624    CA     4      2    1477

            Type   Sale_date   Price  Latitude  Longitude
931  Residential  2008-05-15  176850  38.44574  -121.3725
('Residential', 178000)                Street            City    Zip State  Beds  Baths  Sq__ft  \
410  4649 FREEWAY CIR      SACRAMENTO  95841    CA     3      2    1120
666    7800 TABARE CT  CITRUS HEIGHTS  95621    CA     3      2    1199

            Type   Sale_date   Price   Latitude   Longitude
410  Residential  2008-05-19  178000  38.658734 -121.357196
666  Residential  2008-05-16  178000  38.707990 -121.302979
('Residential', 178480)                   Street        City    Zip State  Beds  Baths  Sq__ft  \
54  7957 VALLEY GREEN DR  SACRAMENTO  95823    CA     3      2    1185

           Type   Sale_date   Price   Latitude   Longitude
54  Residential  2008-05-21  178480  38.465184 -121.434925
('Residential', 178760)                 Street  City    Zip State  Beds  Baths  Sq__ft         Type  \
55  1122 WILD POPPY CT  GALT  95632    CA     3      2    1406  Residential

     Sale_date   Price   Latitude   Longitude
55  2008-05-21  178760  38.287789 -121.294715
('Residential', 179000)                    Street        City    Zip State  Beds  Baths  Sq__ft  \
213  5841 VALLEY VALE WAY  SACRAMENTO  95823    CA     3      2    1265
667    8531 HERMITAGE WAY  SACRAMENTO  95823    CA     4      2    1695

            Type   Sale_date   Price   Latitude   Longitude
213  Residential  2008-05-20  179000  38.461283 -121.434322
667  Residential  2008-05-16  179000  38.448452 -121.428536
('Residential', 179500)         Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
932  9 WIND CT  SACRAMENTO  95823    CA     4      2    1497  Residential

      Sale_date   Price  Latitude   Longitude
932  2008-05-15  179500  38.45073 -121.427528
('Residential', 180000)                      Street            City    Zip State  Beds  Baths  Sq__ft  \
214      7863 CRESTLEIGH CT        ANTELOPE  95843    CA     2      2    1007
411         8593 DERLIN WAY      SACRAMENTO  95823    CA     3      2    1436
412        9273 PREMIER WAY      SACRAMENTO  95826    CA     3      2    1451
413       8032 DUSENBERG CT      SACRAMENTO  95828    CA     4      2    1638
668       2421 BERRYWOOD DR  RANCHO CORDOVA  95670    CA     3      2    1157
669         1005 MORENO WAY      SACRAMENTO  95838    CA     3      2    1410
670  1675 VERNON ST Unit 24       ROSEVILLE  95678    CA     3      2    1174

            Type   Sale_date   Price   Latitude   Longitude
214  Residential  2008-05-20  180000  38.710889 -121.358876
411  Residential  2008-05-19  180000  38.447585 -121.426627
412  Residential  2008-05-19  180000  38.559920 -121.352539
413  Residential  2008-05-19  180000  38.466499 -121.381119
668  Residential  2008-05-16  180000  38.608680 -121.278490
669  Residential  2008-05-16  180000  38.646206 -121.442767
670  Residential  2008-05-16  180000  38.734136 -121.299639
('Residential', 180400)                  Street       City    Zip State  Beds  Baths  Sq__ft  \
215  7129 SPRINGMONT DR  ELK GROVE  95758    CA     3      2    1716

            Type   Sale_date   Price   Latitude   Longitude
215  Residential  2008-05-20  180400  38.417649 -121.420294
('Residential', 181000)                Street        City    Zip State  Beds  Baths  Sq__ft  \
57   9012 KIEFER BLVD  SACRAMENTO  95826    CA     3      2    1172
671   24 WINDCHIME CT  SACRAMENTO  95823    CA     3      2    1593

            Type   Sale_date   Price   Latitude   Longitude
57   Residential  2008-05-21  181000  38.547011 -121.366217
671  Residential  2008-05-16  181000  38.446170 -121.427824
('Residential', 181872)                Street        City    Zip State  Beds  Baths  Sq__ft  \
58  5332 SANDSTONE ST  CARMICHAEL  95608    CA     3      1    1152

           Type   Sale_date   Price   Latitude   Longitude
58  Residential  2008-05-21  181872  38.662105 -121.313945
('Residential', 182000)                Street       City    Zip State  Beds  Baths  Sq__ft  \
216  8284 RED FOX WAY  ELK GROVE  95758    CA     4      2    1685
672    540 HARLING CT  RIO LINDA  95673    CA     3      2    1093

            Type   Sale_date   Price   Latitude   Longitude
216  Residential  2008-05-20  182000  38.417182 -121.397231
672  Residential  2008-05-16  182000  38.682790 -121.453509
('Residential', 182587)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
59     5993 SAWYER CIR  SACRAMENTO  95823    CA     4      3    1851
673  1207 CRESCENDO DR   ROSEVILLE  95678    CA     3      2    1770

            Type   Sale_date   Price  Latitude   Longitude
59   Residential  2008-05-21  182587  38.44730 -121.435218
673  Residential  2008-05-16  182587  38.72446 -121.292829
('Residential', 182716)                 Street      City    Zip State  Beds  Baths  Sq__ft  \
60  4844 CLYDEBANK WAY  ANTELOPE  95843    CA     3      2    1215

           Type   Sale_date   Price   Latitude   Longitude
60  Residential  2008-05-21  182716  38.714609 -121.347887
('Residential', 182750)               Street  City    Zip State  Beds  Baths  Sq__ft         Type  \
61  306 CAMELLIA WAY  GALT  95632    CA     3      2    1130  Residential

     Sale_date   Price   Latitude   Longitude
61  2008-05-21  182750  38.260443 -121.297864
('Residential', 183200)               Street        City    Zip State  Beds  Baths  Sq__ft  \
62  9021 MADISON AVE  ORANGEVALE  95662    CA     4      2    1603

           Type   Sale_date   Price   Latitude   Longitude
62  Residential  2008-05-21  183200  38.664186 -121.217511
('Residential', 184500)                 Street            City    Zip State  Beds  Baths  Sq__ft  \
217  2219 EL CANTO CIR  RANCHO CORDOVA  95670    CA     4      2    1829

            Type   Sale_date   Price   Latitude   Longitude
217  Residential  2008-05-20  184500  38.592383 -121.318669
('Residential', 185000)                Street       City    Zip State  Beds  Baths  Sq__ft  \
218  8907 GEMWOOD WAY  ELK GROVE  95758    CA     3      2    1555
933  8570 SHERATON DR  FAIR OAKS  95628    CA     3      1     960

            Type   Sale_date   Price   Latitude   Longitude
218  Residential  2008-05-20  185000  38.435471 -121.441173
933  Residential  2008-05-15  185000  38.667254 -121.240708
('Residential', 185074)                Street        City    Zip State  Beds  Baths  Sq__ft  \
674  7577 EDDYLEE WAY  SACRAMENTO  95822    CA     4      2    1436

            Type   Sale_date   Price  Latitude   Longitude
674  Residential  2008-05-16  185074  38.48291 -121.491509
('Residential', 185833)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
675  8369 FOPPIANO WAY  SACRAMENTO  95829    CA     3      2    1124

            Type   Sale_date   Price   Latitude   Longitude
675  Residential  2008-05-16  185833  38.453839 -121.357919
('Residential', 186785)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
676  8817 SAWTELLE WAY  SACRAMENTO  95826    CA     4      2    1139

            Type   Sale_date   Price   Latitude   Longitude
676  Residential  2008-05-16  186785  38.565322 -121.374251
('Residential', 187000)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
677  1910 BONAVISTA WAY  SACRAMENTO  95832    CA     3      2    1638

            Type   Sale_date   Price   Latitude   Longitude
677  Residential  2008-05-16  187000  38.476048 -121.494961
('Residential', 188325)                 Street       City    Zip State  Beds  Baths  Sq__ft  \
415  1786 PIEDMONT WAY  ROSEVILLE  95661    CA     3      1    1152

            Type   Sale_date   Price  Latitude   Longitude
415  Residential  2008-05-19  188325  38.72748 -121.256537
('Residential', 188335)         Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
678  8 TIDE CT  SACRAMENTO  95833    CA     3      2    1328  Residential

      Sale_date   Price   Latitude   Longitude
678  2008-05-16  188335  38.609864 -121.492304
('Residential', 188700)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
935  1080 RIO NORTE WAY  SACRAMENTO  95834    CA     3      2    1428

            Type   Sale_date   Price   Latitude   Longitude
935  Residential  2008-05-15  188700  38.634335 -121.486098
('Residential', 188741)         Street  City    Zip State  Beds  Baths  Sq__ft         Type  \
63  404 6TH ST  GALT  95632    CA     3      1    1479  Residential

     Sale_date   Price   Latitude   Longitude
63  2008-05-21  188741  38.251808 -121.302493
('Residential', 189000)                    Street        City    Zip State  Beds  Baths  Sq__ft  \
64   8317 SUNNY CREEK WAY  SACRAMENTO  95823    CA     3      2    1420
219    5925 MALEVILLE AVE  CARMICHAEL  95608    CA     4      2    1120
936     5501 VALLETTA WAY  SACRAMENTO  95820    CA     3      1    1039
937        5624 MEMORY LN   FAIR OAKS  95628    CA     3      1    1529

            Type   Sale_date   Price   Latitude   Longitude
64   Residential  2008-05-21  189000  38.459041 -121.424644

('Residential', 200100)                     Street             City    Zip State  Beds  Baths  Sq__ft  \
947  1525 PENNSYLVANIA AVE  WEST SACRAMENTO  95691    CA     0      0       0

            Type   Sale_date   Price   Latitude   Longitude
947  Residential  2008-05-15  200100  38.569943 -121.527539
('Residential', 200345)                Street        City    Zip State  Beds  Baths  Sq__ft  \
422  1 KENNELFORD CIR  SACRAMENTO  95823    CA     3      2    1144

            Type   Sale_date   Price  Latitude   Longitude
422  Residential  2008-05-19  200345  38.46452 -121.427606
('Residential', 201000)                 Street          City    Zip State  Beds  Baths  Sq__ft  \
223     2778 KAWEAH CT  CAMERON PARK  95682    CA     3      1       0
694  5733 ANGELINA AVE    CARMICHAEL  95608    CA     3      1     972

            Type   Sale_date   Price   Latitude   Longitude
223  Residential  2008-05-20  201000  38.694052 -120.995589
694  Residential  2008-05-16  201000  38.622634 -121.330846
('Residential', 201528)                   Street        City    Zip State  Beds  Baths  Sq__ft  \
948  5954 BRIDGECROSS DR  SACRAMENTO  95835    CA     3      2    1358

            Type   Sale_date   Price  Latitude   Longitude
948  Residential  2008-05-15  201528  38.68197 -121.500025
('Residential', 202500)                  Street     City    Zip State  Beds  Baths  Sq__ft  \
224  1636 ALLENWOOD CIR  LINCOLN  95648    CA     4      2       0

            Type   Sale_date   Price   Latitude   Longitude
224  Residential  2008-05-20  202500  38.879192 -121.309477
('Residential', 203000)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
423  909 SINGINGWOOD RD  SACRAMENTO  95864    CA     2      1     930

            Type   Sale_date   Price   Latitude  Longitude
423  Residential  2008-05-19  203000  38.581471 -121.38839
('Residential', 204750)                    Street       City    Zip State  Beds  Baths  Sq__ft  \
949  8789 SEQUOIA WOOD CT  ELK GROVE  95624    CA     4      2    1609

            Type   Sale_date   Price   Latitude  Longitude
949  Residential  2008-05-15  204750  38.438818 -121.37443
('Residential', 204918)                    Street       City    Zip State  Beds  Baths  Sq__ft  \
695  7849 BONNY DOWNS WAY  ELK GROVE  95758    CA     4      2    2306

            Type   Sale_date   Price  Latitude   Longitude
695  Residential  2008-05-16  204918  38.42139 -121.411339
('Residential', 205000)                        Street         City    Zip State  Beds  Baths  Sq__ft  \
225       8151 QUAIL RIDGE CT   SACRAMENTO  95828    CA     3      2    1289
226        4899 WIND CREEK DR   SACRAMENTO  95838    CA     4      2    1799
227  2370 BIG CANYON CREEK RD  PLACERVILLE  95667    CA     3      2       0
228          6049 HAMBURG WAY   SACRAMENTO  95823    CA     4      3    1953
696         8716 LONGSPUR WAY     ANTELOPE  95843    CA     3      2    1479
697         6320 EL DORADO ST    EL DORADO  95623    CA     2      1    1040
950     6600 SILVERTHORNE CIR   SACRAMENTO  95842    CA     4      3    1968
951              2221 2ND AVE   SACRAMENTO  95818    CA     2      2    1089

            Type   Sale_date   Price   Latitude   Longitude
225  Residential  2008-05-20  205000  38.461296 -121.390858
226  Residential  2008-05-20  205000  38.655887 -121.446119
227  Residential  2008-05-20  205000  38.744580 -120.794254
228  Residential  2008-05-20  205000  38.443253 -121.431992
696  Residential  2008-05-16  205000  38.724083 -121.358400
697  Residential  2008-05-16  205000  38.678758 -120.844118
950  Residential  2008-05-15  205000  38.686070 -121.342369
951  Residential  2008-05-15  205000  38.555781 -121.485331
('Residential', 205878)                     Street        City    Zip State  Beds  Baths  Sq__ft  \
698  2328 DOROTHY JUNE WAY  SACRAMENTO  95838    CA     3      2    1430

            Type   Sale_date   Price   Latitude   Longitude
698  Residential  2008-05-16  205878  38.641727 -121.412703
('Residential', 205900)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
952  3230 SMATHERS WAY  CARMICHAEL  95608    CA     3      2    1296

            Type   Sale_date   Price   Latitude   Longitude
952  Residential  2008-05-15  205900  38.623372 -121.347665
('Residential', 206000)            Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
73  17 SERASPI CT  SACRAMENTO  95834    CA     0      0       0  Residential

     Sale_date   Price   Latitude  Longitude
73  2008-05-21  206000  38.631481 -121.50188
('Residential', 207000)                     Street        City    Zip State  Beds  Baths  Sq__ft  \
229           4232 71ST ST  SACRAMENTO  95820    CA     2      1     723
424        6671 FOXWOOD CT  SACRAMENTO  95841    CA     4      2    1766
699       1986 DANVERS WAY  SACRAMENTO  95832    CA     4      2    1800
953  5209 LAGUNA CREST WAY   ELK GROVE  95758    CA     2      2    1189

            Type   Sale_date   Price   Latitude   Longitude
229  Residential  2008-05-20  207000  38.536741 -121.421150
424  Residential  2008-05-19  207000  38.687943 -121.328883
699  Residential  2008-05-16  207000  38.477230 -121.492568
953  Residential  2008-05-15  207000  38.424421 -121.443915
('Residential', 207744)                      Street      City    Zip State  Beds  Baths  Sq__ft  \
700  7901 GAZELLE TRAIL WAY  ANTELOPE  95843    CA     4      2    1953

            Type   Sale_date   Price  Latitude   Longitude
700  Residential  2008-05-16  207744  38.71174 -121.342675
('Residential', 207973)              Street        City    Zip State  Beds  Baths  Sq__ft  \
954  416 LEITCH AVE  SACRAMENTO  95815    CA     2      1     795

            Type   Sale_date   Price   Latitude   Longitude
954  Residential  2008-05-15  207973  38.612694 -121.456669
('Residential', 208000)                Street        City    Zip State  Beds  Baths  Sq__ft  \
74     170 PENHOW CIR  SACRAMENTO  95834    CA     3      2    1511
425  8165 AYN RAND CT  SACRAMENTO  95828    CA     4      3    1940

            Type   Sale_date   Price   Latitude   Longitude
74   Residential  2008-05-21  208000  38.653439 -121.535169
425  Residential  2008-05-19  208000  38.468639 -121.403265
('Residential', 208250)               Street       City    Zip State  Beds  Baths  Sq__ft  \
955  2100 BEATTY WAY  ROSEVILLE  95747    CA     3      2    1371

            Type   Sale_date   Price   Latitude   Longitude
955  Residential  2008-05-15  208250  38.737882 -121.308142
('Residential', 208318)                   Street             City    Zip State  Beds  Baths  Sq__ft  \
956  6920 GILLINGHAM WAY  NORTH HIGHLANDS  95660    CA     3      1    1310

            Type   Sale_date   Price   Latitude   Longitude
956  Residential  2008-05-15  208318  38.694279 -121.373395
('Residential', 209000)                   Street        City    Zip State  Beds  Baths  Sq__ft  \
701  6080 BRIDGECROSS DR  SACRAMENTO  95835    CA     3      2    1120

            Type   Sale_date   Price   Latitude   Longitude
701  Residential  2008-05-16  209000  38.681952 -121.505009
('Residential', 209347)                Street  City    Zip State  Beds  Baths  Sq__ft         Type  \
957  82 WILDFLOWER DR  GALT  95632    CA     3      2    1262  Residential

      Sale_date   Price   Latitude   Longitude
957  2008-05-15  209347  38.259708 -121.311616
('Residential', 210000)                    Street          City    Zip State  Beds  Baths  Sq__ft  \
230       3361 BOW MAR CT  CAMERON PARK  95682    CA     2      2       0
426  9474 VILLAGE TREE DR     ELK GROVE  95758    CA     4      2    1776
702          20 GROTH CIR    SACRAMENTO  95834    CA     3      2    1232

            Type   Sale_date   Price   Latitude   Longitude
230  Residential  2008-05-20  210000  38.694370 -120.996602
426  Residential  2008-05-19  210000  38.413947 -121.408276
702  Residential  2008-05-16  210000  38.640807 -121.533522
('Residential', 211500)                    Street         City    Zip State  Beds  Baths  Sq__ft  \
231  1889 COLD SPRINGS RD  PLACERVILLE  95667    CA     2      1     948
958       8652 BANTON CIR    ELK GROVE  95624    CA     4      2    1740

            Type   Sale_date   Price   Latitude   Longitude
231  Residential  2008-05-20  211500  38.739774 -120.860243
958  Residential  2008-05-15  211500  38.444000 -121.370993
('Residential', 212000)                   Street            City    Zip State  Beds  Baths  Sq__ft  \
427       7213 CALVIN DR  CITRUS HEIGHTS  95621    CA     3      1    1258
959  8428 MISTY PASS WAY        ANTELOPE  95843    CA     3      2    1517

            Type   Sale_date   Price   Latitude   Longitude
427  Residential  2008-05-19  212000  38.698154 -121.298375
959  Residential  2008-05-15  212000  38.722959 -121.347115
('Residential', 212864)                    Street        City    Zip State  Beds  Baths  Sq__ft  \
75  8345 STAR THISTLE WAY  SACRAMENTO  95823    CA     4      2    1590

           Type   Sale_date   Price   Latitude   Longitude
75  Residential  2008-05-21  212864  38.454349 -121.439239
('Residential', 213000)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
960  7958 ROSEVIEW WAY  SACRAMENTO  95828    CA     3      2    1450

            Type   Sale_date   Price   Latitude   Longitude
960  Residential  2008-05-15  213000  38.467836 -121.410366
('Residential', 213675)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
428  8167 DERBY PARK CT  SACRAMENTO  95828    CA     4      2    1872

            Type   Sale_date   Price   Latitude   Longitude
428  Residential  2008-05-19  213675  38.460492 -121.373379
('Residential', 213697)                     Street       City    Zip State  Beds  Baths  Sq__ft  \
429  6344 LAGUNA MIRAGE LN  ELK GROVE  95758    CA     2      2    1112

            Type   Sale_date   Price   Latitude   Longitude
429  Residential  2008-05-19  213697  38.423963 -121.428875
('Residential', 213750)               Street       City    Zip State  Beds  Baths  Sq__ft  \
705  8442 KEUSMAN ST  ELK GROVE  95758    CA     4      2    2329

            Type   Sale_date   Price   Latitude   Longitude
705  Residential  2008-05-16  213750  38.449651 -121.414704
('Residential', 215000)                   Street            City    Zip State  Beds  Baths  Sq__ft  \
232    5805 HIMALAYA WAY  CITRUS HEIGHTS  95621    CA     4      2    1578
233  7944 SYLVAN OAK WAY  CITRUS HEIGHTS  95610    CA     3      2    1317
430    2945 RED HAWK WAY      SACRAMENTO  95833    CA     4      2    1856
431            3228 I ST      SACRAMENTO  95816    CA     4      3    1939
706     9552 SUNLIGHT LN       ELK GROVE  95758    CA     3      2    1351
707         2733 YUMA CT    CAMERON PARK  95682    CA     2      2       0
708     1407 TIFFANY CIR       ROSEVILLE  95661    CA     4      1    1376

            Type   Sale_date   Price   Latitude   Longitude
232  Residential  2008-05-20  215000  38.696489 -121.328555
233  Residential  2008-05-20  215000  38.710388 -121.261096
430  Residential  2008-05-19  215000  38.619675 -121.496903
431  Residential  2008-05-19  215000  38.573844 -121.462839
706  Residential  2008-05-16  215000  38.410561 -121.404327
707  Residential  2008-05-16  215000  38.691215 -120.994949
708  Residential  2008-05-16  215000  38.736392 -121.266400
('Residential', 215100)               Street       City    Zip State  Beds  Baths  Sq__ft  \
432  308 ATKINSON ST  ROSEVILLE  95678    CA     3      1     998

            Type   Sale_date   Price   Latitude  Longitude
432  Residential  2008-05-19  215100  38.746794 -121.29971
('Residential', 215500)                         Street        City    Zip State  Beds  Baths  Sq__ft  \
234  3139 SPOONWOOD WAY Unit 1  SACRAMENTO  95833    CA     0      0       0

            Type   Sale_date   Price   Latitude  Longitude
234  Residential  2008-05-20  215500  38.626582 -121.52151
('Residential', 216000)             Street       City    Zip State  Beds  Baths  Sq__ft         Type  \
961  9020 LUKEN CT  ELK GROVE  95624    CA     3      2    1416  Residential

      Sale_date   Price   Latitude   Longitude
961  2008-05-15  216000  38.451398 -121.366614
('Residential', 216021)                   Street        City    Zip State  Beds  Baths  Sq__ft  \
962  7809 VALLECITOS WAY  SACRAMENTO  95828    CA     3      1     888

            Type   Sale_date   Price   Latitude   Longitude
962  Residential  2008-05-15  216021  38.508217 -121.411207
('Residential', 216033)                Street             City    Zip State  Beds  Baths  Sq__ft  \
709  636 CRESTVIEW DR  DIAMOND SPRINGS  95619    CA     3      2    1300

            Type   Sale_date   Price   Latitude   Longitude
709  Residential  2008-05-16  216033  38.688255 -120.810235
('Residential', 217500)             Street       City    Zip State  Beds  Baths  Sq__ft         Type  \
433  624 HOVEY WAY  ROSEVILLE  95678    CA     3      2    1758  Residential

      Sale_date   Price   Latitude   Longitude
433  2008-05-19  217500  38.756149 -121.306479
('Residential', 218000)                   Street        City    Zip State  Beds  Baths  Sq__ft  \
434  110 COPPER LEAF WAY  SACRAMENTO  95838    CA     3      2    2142

            Type   Sale_date   Price   Latitude   Longitude
434  Residential  2008-05-19  218000  38.658466 -121.460661
('Residential', 219000)                  Street            City    Zip State  Beds  Baths  Sq__ft  \
963  8445 OLD AUBURN RD  CITRUS HEIGHTS  95610    CA     3      2    1882

            Type   Sale_date   Price   Latitude   Longitude
963  Residential  2008-05-15  219000  38.715423 -121.246743
('Residential', 219794)               Street       City    Zip State  Beds  Baths  Sq__ft  \
964  10085 ATKINS DR  ELK GROVE  95757    CA     3      2    1302

            Type   Sale_date   Price   Latitude   Longitude
964  Residential  2008-05-15  219794  38.390893 -121.437821
('Residential', 220000)                   Street            City    Zip State  Beds  Baths  Sq__ft  \
435  7535 ALMA VISTA WAY      SACRAMENTO  95831    CA     2      1     950
710      1528 HESKET WAY      SACRAMENTO  95825    CA     4      2    1566
711         2327 32ND ST      SACRAMENTO  95817    CA     2      1    1115
712         1833 2ND AVE      SACRAMENTO  95818    CA     2      1    1032
713     7252 CARRIAGE DR  CITRUS HEIGHTS  95621    CA     4      2    1419
714   9815 PASO FINO WAY       ELK GROVE  95757    CA     3      2    1261
965  9185 CERROLINDA CIR       ELK GROVE  95758    CA     3      2    1418
967      5429 HESPER WAY      CARMICHAEL  95608    CA     4      2    1319
968     1178 WARMWOOD CT            GALT  95632    CA     4      2    1770

            Type   Sale_date   Price   Latitude   Longitude
435  Residential  2008-05-19  220000  38.484030 -121.507641
710  Residential  2008-05-16  220000  38.593598 -121.403637
711  Residential  2008-05-16  220000  38.557433 -121.470340
712  Residential  2008-05-16  220000  38.556818 -121.490669
713  Residential  2008-05-16  220000  38.698058 -121.294893
714  Residential  2008-05-16  220000  38.404888 -121.443998
965  Residential  2008-05-15  220000  38.424497 -121.426595
967  Residential  2008-05-15  220000  38.665104 -121.315901
968  Residential  2008-05-15  220000  38.289544 -121.284607
('Residential', 220702)             Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
715  5532 ENGLE RD  CARMICHAEL  95608    CA     2      2    1637  Residential

      Sale_date   Price  Latitude   Longitude
715  2008-05-16  220702  38.63173 -121.335286
('Residential', 221000)                Street        City    Zip State  Beds  Baths  Sq__ft  \
76    9080 FRESCA WAY   ELK GROVE  95758    CA     4      2    1596
77   391 NATALINO CIR  SACRAMENTO  95835    CA     2      2    1341
436   7423 WILSALL CT   ELK GROVE  95758    CA     4      3    1739

            Type   Sale_date   Price   Latitude   Longitude
76   Residential  2008-05-21  221000  38.427818 -121.424026
77   Residential  2008-05-21  221000  38.673070 -121.506373
436  Residential  2008-05-19  221000  38.417026 -121.416821
('Residential', 222000)                  Street       City    Zip State  Beds  Baths  Sq__ft  \
717  9176 SAGE GLEN WAY  ELK GROVE  95758    CA     3      2    1338

            Type   Sale_date   Price   Latitude   Longitude
717  Residential  2008-05-16  222000  38.423913 -121.439115
('Residential', 222381)              Street        City    Zip State  Beds  Baths  Sq__ft  \
235  6217 LEOLA WAY  SACRAMENTO  95824    CA     3      1    1360

            Type   Sale_date   Price   Latitude   Longitude
235  Residential  2008-05-20  222381  38.513066 -121.451909
('Residential', 222500)                  Street       City    Zip State  Beds  Baths  Sq__ft  \
718  9967 HATHERTON WAY  ELK GROVE  95757    CA     0      0       0

            Type   Sale_date   Price  Latitude  Longitude
718  Residential  2008-05-16  222500   38.3052  -121.4033
('Residential', 222750)                      Street       City    Zip State  Beds  Baths  Sq__ft  \
719  9264 BOULDER RIVER WAY  ELK GROVE  95624    CA     5      2    2254

            Type   Sale_date   Price   Latitude   Longitude
719  Residential  2008-05-16  222750  38.421713 -121.345191
('Residential', 222900)                 Street       City    Zip State  Beds  Baths  Sq__ft  \
437  8629 VIA ALTA WAY  ELK GROVE  95624    CA     3      2    1516

            Type   Sale_date   Price   Latitude   Longitude
437  Residential  2008-05-19  222900  38.398245 -121.380615
('Residential', 223000)             Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
969  4900 ELUDE CT  SACRAMENTO  95842    CA     4      2    1627  Residential

      Sale_date   Price  Latitude   Longitude
969  2008-05-15  223000  38.69674 -121.350519
('Residential', 223058)                Street       City    Zip State  Beds  Baths  Sq__ft  \
78  8373 BLACKMAN WAY  ELK GROVE  95624    CA     5      3    2136

           Type   Sale_date   Price   Latitude   Longitude
78  Residential  2008-05-21  223058  38.435436 -121.394536

('Residential', 223139)                Street      City    Zip State  Beds  Baths  Sq__ft  \
438  3318 DAVIDSON DR  ANTELOPE  95843    CA     3      1     988

            Type   Sale_date   Price   Latitude   Longitude
438  Residential  2008-05-19  223139  38.705753 -121.388917
('Residential', 224000)                    Street        City    Zip State  Beds  Baths  Sq__ft  \
970         3557 SODA WAY  SACRAMENTO  95834    CA     0      0       0
971  3528 SAINT GEORGE DR  SACRAMENTO  95821    CA     3      1    1040

            Type   Sale_date   Price   Latitude   Longitude
970  Residential  2008-05-15  224000  38.631026 -121.501879
971  Residential  2008-05-15  224000  38.629468 -121.376445
('Residential', 224252)                 Street             City    Zip State  Beds  Baths  Sq__ft  \
972  7381 WASHBURN WAY  NORTH HIGHLANDS  95660    CA     3      1     960

            Type   Sale_date   Price  Latitude   Longitude
972  Residential  2008-05-15  224252  38.70355 -121.375103
('Residential', 224500)                    Street          City    Zip State  Beds  Baths  Sq__ft  \
973  2181 WINTERHAVEN CIR  CAMERON PARK  95682    CA     3      2       0

            Type   Sale_date   Price  Latitude   Longitude
973  Residential  2008-05-15  224500  38.69757 -120.995739
('Residential', 225000)                     Street        City    Zip State  Beds  Baths  Sq__ft  \
237        3035 BRUNNET LN  SACRAMENTO  95833    CA     3      2    1522
238      3025 EL PRADO WAY  SACRAMENTO  95825    CA     4      2    1751
239  9387 GRANITE FALLS CT   ELK GROVE  95624    CA     3      2    1465
720          320 GROTH CIR  SACRAMENTO  95834    CA     3      2    1441
721       137 GUNNISON AVE  SACRAMENTO  95838    CA     4      2    1991
974       7540 HICKORY AVE  ORANGEVALE  95662    CA     3      1    1456

            Type   Sale_date   Price   Latitude   Longitude
237  Residential  2008-05-20  225000  38.624762 -121.522775
238  Residential  2008-05-20  225000  38.606603 -121.394147
239  Residential  2008-05-20  225000  38.419214 -121.348533
720  Residential  2008-05-16  225000  38.638882 -121.531883
721  Residential  2008-05-16  225000  38.650729 -121.466483
974  Residential  2008-05-15  225000  38.703056 -121.235221
('Residential', 225500)             Street  City    Zip State  Beds  Baths  Sq__ft         Type  \
439  913 COBDEN CT  GALT  95632    CA     4      2    1555  Residential

      Sale_date   Price   Latitude   Longitude
439  2008-05-19  225500  38.282001 -121.295902
('Residential', 227887)                   Street       City    Zip State  Beds  Baths  Sq__ft  \
79  9837 CORTE DORADO CT  ELK GROVE  95624    CA     4      2    1616

           Type   Sale_date   Price   Latitude  Longitude
79  Residential  2008-05-21  227887  38.400676 -121.38101
('Residential', 228000)                   Street        City    Zip State  Beds  Baths  Sq__ft  \
240     9257 CALDERA WAY  SACRAMENTO  95826    CA     4      2    1605
975  5024 CHAMBERLIN CIR   ELK GROVE  95757    CA     3      2    1450

            Type   Sale_date   Price   Latitude   Longitude
240  Residential  2008-05-20  228000  38.558210 -121.355022
975  Residential  2008-05-15  228000  38.389756 -121.446246
('Residential', 228327)            Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
440  4419 79TH ST  SACRAMENTO  95820    CA     3      2    1212  Residential

      Sale_date   Price   Latitude   Longitude
440  2008-05-19  228327  38.534827 -121.412545
('Residential', 228750)                Street        City    Zip State  Beds  Baths  Sq__ft  \
722  8209 RIVALLO WAY  SACRAMENTO  95829    CA     4      3    2126

            Type   Sale_date   Price   Latitude  Longitude
722  Residential  2008-05-16  228750  38.459524  -121.3501
('Residential', 229000)                   Street       City    Zip State  Beds  Baths  Sq__ft  \
723  8637 PERIWINKLE CIR  ELK GROVE  95624    CA     3      2    1094

            Type   Sale_date   Price   Latitude   Longitude
723  Residential  2008-05-16  229000  38.443184 -121.364388
('Residential', 229027)                 Street     City    Zip State  Beds  Baths  Sq__ft  \
976  2400 INVERNESS DR  LINCOLN  95648    CA     3      2    1358

            Type   Sale_date   Price   Latitude   Longitude
976  Residential  2008-05-15  229027  38.897814 -121.324691
('Residential', 229500)               Street        City    Zip State  Beds  Baths  Sq__ft  \
977  5 BISHOPGATE CT  SACRAMENTO  95823    CA     4      2    1329

            Type   Sale_date   Price   Latitude   Longitude
977  Residential  2008-05-15  229500  38.467936 -121.445477
('Residential', 229665)                  Street       City    Zip State  Beds  Baths  Sq__ft  \
241  441 ARLINGDALE CIR  RIO LINDA  95673    CA     4      2    1475

            Type   Sale_date   Price   Latitude   Longitude
241  Residential  2008-05-20  229665  38.702893 -121.454949
('Residential', 230000)                      Street          City    Zip State  Beds  Baths  Sq__ft  \
242      2284 LOS ROBLES RD  MEADOW VISTA  95722    CA     3      1    1216
243    8164 CHENIN BLANC LN     FAIR OAKS  95628    CA     2      2    1315
244     4620 CHAMBERLIN CIR     ELK GROVE  95757    CA     3      2    1567
441      3012 SPOONWOOD WAY    SACRAMENTO  95833    CA     4      2    1871
442  8728 CRYSTAL RIVER WAY    SACRAMENTO  95828    CA     3      2    1302
978        5601 REXLEIGH DR    SACRAMENTO  95823    CA     4      2    1715
979        1909 YARNELL WAY     ELK GROVE  95758    CA     3      2    1262

            Type   Sale_date   Price   Latitude   Longitude
242  Residential  2008-05-20  230000  39.008159 -121.036230
243  Residential  2008-05-20  230000  38.665644 -121.259969
244  Residential  2008-05-20  230000  38.390557 -121.449805
441  Residential  2008-05-19  230000  38.624780 -121.523474
442  Residential  2008-05-19  230000  38.475470 -121.380055
978  Residential  2008-05-15  230000  38.445342 -121.441504
979  Residential  2008-05-15  230000  38.417382 -121.484325
('Residential', 230095)               Street     City    Zip State  Beds  Baths  Sq__ft         Type  \
724  3425 MEADOW WAY  ROCKLIN  95677    CA     3      2    1462  Residential

      Sale_date   Price   Latitude   Longitude
724  2008-05-16  230095  38.798028 -121.235364
('Residential', 231200)                 Street      City    Zip State  Beds  Baths  Sq__ft  \
444  4508 OLD DAIRY DR  ANTELOPE  95843    CA     4      3    2026

            Type   Sale_date   Price  Latitude   Longitude
444  Residential  2008-05-19  231200  38.72286 -121.358939
('Residential', 231477)          Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
80  5037 J PKWY  SACRAMENTO  95823    CA     3      2    1478  Residential

     Sale_date   Price   Latitude   Longitude
80  2008-05-21  231477  38.491399 -121.443547
('Residential', 232000)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
445  312 RIVER ISLE WAY  SACRAMENTO  95831    CA     3      2    1375

            Type   Sale_date   Price  Latitude   Longitude
445  Residential  2008-05-19  232000  38.49026 -121.550527
('Residential', 232425)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
980  9169 GARLINGTON CT  SACRAMENTO  95829    CA     4      3    2280

            Type   Sale_date   Price   Latitude  Longitude
980  Residential  2008-05-15  232425  38.457679 -121.35962
('Residential', 232500)              Street        City    Zip State  Beds  Baths  Sq__ft  \
725  107 JARVIS CIR  SACRAMENTO  95834    CA     5      3    2258

            Type   Sale_date   Price   Latitude   Longitude
725  Residential  2008-05-16  232500  38.639891 -121.537603
('Residential', 233000)              Street            City    Zip State  Beds  Baths  Sq__ft  \
726  2319 THORES ST  RANCHO CORDOVA  95670    CA     3      2    1074

            Type   Sale_date   Price  Latitude   Longitude
726  Residential  2008-05-16  233000  38.59675 -121.312716
('Residential', 233500)                     Street       City    Zip State  Beds  Baths  Sq__ft  \
727  8935 MOUNTAIN HOME CT  ELK GROVE  95624    CA     4      2    2111

            Type   Sale_date   Price  Latitude   Longitude
727  Residential  2008-05-16  233500  38.38751 -121.370276
('Residential', 233641)            Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
447  5636 25TH ST  SACRAMENTO  95822    CA     3      1    1058  Residential

      Sale_date   Price   Latitude   Longitude
447  2008-05-19  233641  38.523828 -121.481139
('Residential', 234000)                     Street        City    Zip State  Beds  Baths  Sq__ft  \
245          5340 BIRK WAY  SACRAMENTO  95835    CA     3      2    1776
448  8721 SPRUCE RIDGE WAY    ANTELOPE  95843    CA     3      2    1187
981        6932 RUSKUT WAY  SACRAMENTO  95823    CA     3      2    1477

            Type   Sale_date   Price   Latitude   Longitude
245  Residential  2008-05-20  234000  38.672495 -121.515251
448  Residential  2008-05-19  234000  38.727657 -121.391028
981  Residential  2008-05-15  234000  38.499893 -121.458890
('Residential', 234500)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
449  7461 WINDBRIDGE DR  SACRAMENTO  95831    CA     2      2    1324

            Type   Sale_date   Price  Latitude   Longitude
449  Residential  2008-05-19  234500  38.48797 -121.530229
('Residential', 234697)                 Street            City    Zip State  Beds  Baths  Sq__ft  \
81  10245 LOS PALOS DR  RANCHO CORDOVA  95670    CA     3      2    1287

           Type   Sale_date   Price   Latitude  Longitude
81  Residential  2008-05-21  234697  38.593699 -121.31089
('Residential', 235000)                  Street            City    Zip State  Beds  Baths  Sq__ft  \
82       6613 NAVION DR  CITRUS HEIGHTS  95621    CA     4      2    1277
246        51 ANJOU CIR      SACRAMENTO  95835    CA     3      2    2187
450  8101 LEMON COVE CT      SACRAMENTO  95828    CA     4      3    1936
982   7933 DAFFODIL WAY  CITRUS HEIGHTS  95610    CA     3      2    1216

            Type   Sale_date   Price   Latitude   Longitude
82   Residential  2008-05-21  235000  38.702855 -121.313080
246  Residential  2008-05-20  235000  38.661658 -121.540633
450  Residential  2008-05-19  235000  38.462981 -121.408288
982  Residential  2008-05-15  235000  38.708824 -121.256803
('Residential', 235301)                Street       City    Zip State  Beds  Baths  Sq__ft  \
983  8304 RED FOX WAY  ELK GROVE  95758    CA     4      2    1685

            Type   Sale_date   Price  Latitude   Longitude
983  Residential  2008-05-15  235301    38.417 -121.397424
('Residential', 235738)                   Street             City    Zip State  Beds  Baths  Sq__ft  \
984  3882 YELLOWSTONE LN  EL DORADO HILLS  95762    CA     3      2    1362

            Type   Sale_date   Price   Latitude   Longitude
984  Residential  2008-05-15  235738  38.655245 -121.075915
('Residential', 236000)              Street        City    Zip State  Beds  Baths  Sq__ft  \
83  2887 AZEVEDO DR  SACRAMENTO  95833    CA     4      2    1448

           Type   Sale_date   Price   Latitude   Longitude
83  Residential  2008-05-21  236000  38.618457 -121.509439
('Residential', 236073)                   Street    City    Zip State  Beds  Baths  Sq__ft  \
452  617 WILLOW CREEK DR  FOLSOM  95630    CA     3      2    1427

            Type   Sale_date   Price   Latitude   Longitude
452  Residential  2008-05-19  236073  38.679626 -121.142609
('Residential', 236250)             Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
247  2125 22ND AVE  SACRAMENTO  95822    CA     3      1    1291  Residential

      Sale_date   Price   Latitude   Longitude
247  2008-05-20  236250  38.534596 -121.493121
('Residential', 236685)               Street        City    Zip State  Beds  Baths  Sq__ft  \
84  9186 KINBRACE CT  SACRAMENTO  95829    CA     4      3    2235

           Type   Sale_date   Price   Latitude   Longitude
84  Residential  2008-05-21  236685  38.463355 -121.358936
('Residential', 237800)                  Street    City    Zip State  Beds  Baths  Sq__ft  \
85  4243 MIDDLEBURY WAY  MATHER  95655    CA     3      2    2093

           Type   Sale_date   Price   Latitude   Longitude
85  Residential  2008-05-21  237800  38.547991 -121.280483
('Residential', 238861)               Street  City    Zip State  Beds  Baths  Sq__ft         Type  \
454  709 CIMMARON CT  GALT  95632    CA     4      2    1798  Residential

      Sale_date   Price   Latitude   Longitude
454  2008-05-19  238861  38.277177 -121.303747
('Residential', 239000)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
728  2566 SERENATA WAY  SACRAMENTO  95835    CA     3      2    1686

            Type   Sale_date   Price   Latitude   Longitude
728  Residential  2008-05-16  239000  38.671556 -121.520916
('Residential', 239700)                Street      City    Zip State  Beds  Baths  Sq__ft  \
455  3305 RIO ROCA CT  ANTELOPE  95843    CA     4      3    2652

            Type   Sale_date   Price   Latitude   Longitude
455  Residential  2008-05-19  239700  38.725079 -121.387698
('Residential', 240000)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
456     9080 BEDROCK CT  SACRAMENTO  95829    CA     4      2    1816
457  100 TOURMALINE CIR  SACRAMENTO  95834    CA     5      3    3076
729     4085 COUNTRY DR    ANTELOPE  95843    CA     4      3    1915
730      9297 TROUT WAY   ELK GROVE  95624    CA     4      2    2367

            Type   Sale_date   Price   Latitude   Longitude
456  Residential  2008-05-19  240000  38.456939 -121.362965
457  Residential  2008-05-19  240000  38.634370 -121.510779
729  Residential  2008-05-16  240000  38.706209 -121.369509
730  Residential  2008-05-16  240000  38.420637 -121.375798
('Residential', 240122)                   Street       City    Zip State  Beds  Baths  Sq__ft  \
86  1028 FALLON PLACE CT  RIO LINDA  95673    CA     3      2    1193

           Type   Sale_date   Price   Latitude   Longitude
86  Residential  2008-05-21  240122  38.693818 -121.441153
('Residential', 240971)              Street        City    Zip State  Beds  Baths  Sq__ft  \
731  7 ARCHIBALD CT  SACRAMENTO  95823    CA     3      2    1962

            Type   Sale_date   Price   Latitude   Longitude
731  Residential  2008-05-16  240971  38.443305 -121.435296
('Residential', 241000)                  Street       City    Zip State  Beds  Baths  Sq__ft  \
458  6411 RED BIRCH WAY  ELK GROVE  95758    CA     4      2    1844

            Type   Sale_date   Price  Latitude   Longitude
458  Residential  2008-05-19  241000  38.43461 -121.429316
('Residential', 242000)                  Street            City    Zip State  Beds  Baths  Sq__ft  \
249        8830 ADUR RD       ELK GROVE  95624    CA     0      0       0
732  11130 EEL RIVER CT  RANCHO CORDOVA  95670    CA     2      2    1406

            Type   Sale_date   Price   Latitude   Longitude
249  Residential  2008-05-20  242000  38.437420 -121.372876
732  Residential  2008-05-16  242000  38.625932 -121.271517
('Residential', 242638)              Street       City    Zip State  Beds  Baths  Sq__ft         Type  \
87  4804 NORIKER DR  ELK GROVE  95757    CA     3      2    2163  Residential

     Sale_date   Price   Latitude   Longitude
87  2008-05-21  242638  38.400974 -121.448424
('Residential', 243450)                Street        City    Zip State  Beds  Baths  Sq__ft  \
733  8323 REDBANK WAY  SACRAMENTO  95829    CA     3      2    1789

            Type   Sale_date   Price   Latitude   Longitude
733  Residential  2008-05-16  243450  38.455753 -121.349273
('Residential', 243500)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
734  16 BRONCO CREEK CT  SACRAMENTO  95835    CA     4      2    1876

            Type   Sale_date   Price   Latitude   Longitude
734  Residential  2008-05-16  243500  38.674226 -121.525497
('Residential', 244000)                    Street        City    Zip State  Beds  Baths  Sq__ft  \
88  7713 HARVEST WOODS DR  SACRAMENTO  95828    CA     3      2    1269

           Type   Sale_date   Price   Latitude   Longitude
88  Residential  2008-05-21  244000  38.478198 -121.412911
('Residential', 244500)               Street        City    Zip State  Beds  Baths  Sq__ft  \
89  2866 KARITSA AVE  SACRAMENTO  95833    CA     0      0       0

           Type   Sale_date   Price   Latitude  Longitude
89  Residential  2008-05-21  244500  38.626671 -121.52597
('Residential', 244960)               Street        City    Zip State  Beds  Baths  Sq__ft  \
90  6913 RICHEVE WAY  SACRAMENTO  95828    CA     3      1     958

           Type   Sale_date   Price   Latitude   Longitude
90  Residential  2008-05-21  244960  38.502519 -121.420769
('Residential', 245000)                   Street        City    Zip State  Beds  Baths  Sq__ft  \
250  7344 BUTTERBALL WAY  SACRAMENTO  95842    CA     3      2    1503
251   8219 GWINHURST CIR  SACRAMENTO  95828    CA     4      3    2491
252            3240 S ST  SACRAMENTO  95816    CA     2      1    1269
459       4867 LAGUNA DR  SACRAMENTO  95823    CA     3      2    1306

            Type   Sale_date   Price   Latitude   Longitude
250  Residential  2008-05-20  245000  38.699489 -121.361828
251  Residential  2008-05-20  245000  38.459711 -121.384283
252  Residential  2008-05-20  245000  38.562296 -121.467489
459  Residential  2008-05-19  245000  38.461790 -121.445371
('Residential', 245918)             Street       City    Zip State  Beds  Baths  Sq__ft         Type  \
91  8636 TEGEA WAY  ELK GROVE  95624    CA     5      3    2508  Residential

     Sale_date   Price   Latitude   Longitude
91  2008-05-21  245918  38.443832 -121.382087
('Residential', 246000)             Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
460  3662 RIVER DR  SACRAMENTO  95833    CA     4      3    2447  Residential

      Sale_date   Price   Latitude  Longitude
460  2008-05-19  246000  38.604969 -121.54255
('Residential', 246544)               Street      City    Zip State  Beds  Baths  Sq__ft         Type  \
735  8316 NORTHAM DR  ANTELOPE  95843    CA     3      2    1235  Residential

      Sale_date   Price   Latitude   Longitude
735  2008-05-16  246544  38.720767 -121.376678
('Residential', 246750)             Street      City    Zip State  Beds  Baths  Sq__ft         Type  \
736  4240 WINJE DR  ANTELOPE  95843    CA     4      2    2504  Residential

      Sale_date   Price  Latitude   Longitude
736  2008-05-16  246750  38.70884 -121.359559
('Residential', 247000)                Street        City    Zip State  Beds  Baths  Sq__ft  \
737     3569 SODA WAY  SACRAMENTO  95834    CA     0      0       0
738  5118 ROBANDER ST  CARMICHAEL  95608    CA     3      2    1676

            Type   Sale_date   Price   Latitude   Longitude
737  Residential  2008-05-16  247000  38.631139 -121.501879
738  Residential  2008-05-16  247000  38.657267 -121.310352
('Residential', 247234)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
461  6943 WOLFGRAM WAY  SACRAMENTO  95828    CA     4      2    1176

            Type   Sale_date   Price   Latitude   Longitude
461  Residential  2008-05-19  247234  38.489215 -121.419546
('Residential', 247480)              Street       City    Zip State  Beds  Baths  Sq__ft         Type  \
462  77 RINETTI WAY  RIO LINDA  95673    CA     4      2    1182  Residential

      Sale_date   Price   Latitude   Longitude
462  2008-05-19  247480  38.687021 -121.463151
('Residential', 249000)               Street            City    Zip State  Beds  Baths  Sq__ft  \
739  5976 KYLENCH CT  CITRUS HEIGHTS  95621    CA     3      2    1367
740  9247 DELAIR WAY       ELK GROVE  95758    CA     4      3    1899

            Type   Sale_date   Price   Latitude   Longitude
739  Residential  2008-05-16  249000  38.708966 -121.324670

('Residential', 286013)                Street       City    Zip State  Beds  Baths  Sq__ft  \
272  8806 PHOENIX AVE  FAIR OAKS  95628    CA     3      2    1450

            Type   Sale_date   Price   Latitude   Longitude
272  Residential  2008-05-20  286013  38.660322 -121.230101
('Residential', 287417)                   Street       City    Zip State  Beds  Baths  Sq__ft  \
110  8882 AUTUMN GOLD CT  ELK GROVE  95624    CA     4      2    1993

            Type   Sale_date   Price  Latitude  Longitude
110  Residential  2008-05-21  287417   38.4439 -121.37255
('Residential', 288000)              Street       City    Zip State  Beds  Baths  Sq__ft         Type  \
766  2916 BABSON DR  ELK GROVE  95758    CA     3      2    1735  Residential

      Sale_date   Price   Latitude   Longitude
766  2008-05-16  288000  38.417191 -121.473897
('Residential', 289000)                   Street       City    Zip State  Beds  Baths  Sq__ft  \
486  4885 SUMMIT VIEW DR  EL DORADO  95623    CA     3      2    1624
767    10133 NEBBIOLO CT  ELK GROVE  95624    CA     4      3    2096

            Type   Sale_date   Price   Latitude   Longitude
486  Residential  2008-05-19  289000  38.673285 -120.879176
767  Residential  2008-05-16  289000  38.391085 -121.347231
('Residential', 290000)                Street        City    Zip State  Beds  Baths  Sq__ft  \
768   1103 COMMONS DR  SACRAMENTO  95825    CA     3      2    1720
769  4636 TEAL BAY CT    ANTELOPE  95843    CA     4      2    2160

            Type   Sale_date   Price   Latitude   Longitude
768  Residential  2008-05-16  290000  38.567865 -121.410699
769  Residential  2008-05-16  290000  38.704554 -121.354753
('Residential', 291000)                    Street       City    Zip State  Beds  Baths  Sq__ft  \
111  5322 WHITE LOTUS WAY  ELK GROVE  95757    CA     3      2    1857

            Type   Sale_date   Price   Latitude   Longitude
111  Residential  2008-05-21  291000  38.391538 -121.442596
('Residential', 292000)                   Street        City    Zip State  Beds  Baths  Sq__ft  \
273  3578 LOGGERHEAD WAY  SACRAMENTO  95834    CA     4      2    2169
274    1416 LOCKHART WAY   ROSEVILLE  95747    CA     3      2    1440

            Type   Sale_date   Price   Latitude   Longitude
273  Residential  2008-05-20  292000  38.633028 -121.526755
274  Residential  2008-05-20  292000  38.752399 -121.330328
('Residential', 292024)               Street        City    Zip State  Beds  Baths  Sq__ft  \
112  1838 CASTRO WAY  SACRAMENTO  95818    CA     2      1    1126

            Type   Sale_date   Price   Latitude   Longitude
112  Residential  2008-05-21  292024  38.556098 -121.490787
('Residential', 293993)                      Street       City    Zip State  Beds  Baths  Sq__ft  \
275  5413 BUENA VENTURA WAY  FAIR OAKS  95628    CA     3      2    1527

            Type   Sale_date   Price   Latitude   Longitude
275  Residential  2008-05-20  293993  38.664552 -121.255937
('Residential', 293996)               Street        City    Zip State  Beds  Baths  Sq__ft  \
770  1524 YOUNGS AVE  SACRAMENTO  95838    CA     4      2    1382

            Type   Sale_date   Price   Latitude  Longitude
770  Residential  2008-05-16  293996  38.644927 -121.43054
('Residential', 294000)                 Street         City    Zip State  Beds  Baths  Sq__ft  \
276  37 WHITE BIRCH CT    ROSEVILLE  95678    CA     3      2    1401
771      865 CONRAD CT  PLACERVILLE  95667    CA     3      2       0

            Type   Sale_date   Price   Latitude   Longitude
276  Residential  2008-05-20  294000  38.776327 -121.284514
771  Residential  2008-05-16  294000  38.729993 -120.802458
('Residential', 294173)                  Street       City    Zip State  Beds  Baths  Sq__ft  \
772  8463 TERRACOTTA CT  ELK GROVE  95624    CA     4      2    1721

            Type   Sale_date   Price   Latitude   Longitude
772  Residential  2008-05-16  294173  38.450548 -121.363002
('Residential', 295000)              Street        City    Zip State  Beds  Baths  Sq__ft  \
487  26 JEANROSS CT  SACRAMENTO  95832    CA     5      3    2992
773    5747 KING RD      LOOMIS  95650    CA     4      2    1328

            Type   Sale_date   Price   Latitude   Longitude
487  Residential  2008-05-19  295000  38.473162 -121.491085
773  Residential  2008-05-16  295000  38.825096 -121.198432
('Residential', 296000)                   Street       City    Zip State  Beds  Baths  Sq__ft  \
488  4800 MAPLEPLAIN AVE  ELK GROVE  95758    CA     4      2    2109

            Type   Sale_date   Price   Latitude   Longitude
488  Residential  2008-05-19  296000  38.432848 -121.449237
('Residential', 296056)               Street            City    Zip State  Beds  Baths  Sq__ft  \
489  10629 BASIE WAY  RANCHO CORDOVA  95670    CA     4      2    1524

            Type   Sale_date   Price  Latitude   Longitude
489  Residential  2008-05-19  296056    38.579 -121.292627
('Residential', 296769)                    Street        City    Zip State  Beds  Baths  Sq__ft  \
277  405 MARLIN SPIKE WAY  SACRAMENTO  95838    CA     3      2    1411

            Type   Sale_date   Price  Latitude   Longitude
277  Residential  2008-05-20  296769  38.65783 -121.456842
('Residential', 297000)               Street       City    Zip State  Beds  Baths  Sq__ft  \
114  7731 MASTERS ST  ELK GROVE  95758    CA     5      3    2494

            Type   Sale_date   Price   Latitude   Longitude
114  Residential  2008-05-21  297000  38.442031 -121.410873
('Residential', 297359)                     Street        City    Zip State  Beds  Baths  Sq__ft  \
490  8612 WILLOW GROVE WAY  SACRAMENTO  95828    CA     3      2    1248

            Type   Sale_date   Price   Latitude   Longitude
490  Residential  2008-05-19  297359  38.464994 -121.386962
('Residential', 297500)               Street     City    Zip State  Beds  Baths  Sq__ft         Type  \
278  1102 CHESLEY LN  LINCOLN  95648    CA     4      4       0  Residential

      Sale_date   Price   Latitude   Longitude
278  2008-05-20  297500  38.864864 -121.313988
('Residential', 298000)                 Street       City    Zip State  Beds  Baths  Sq__ft  \
115  4925 PERCHERON DR  ELK GROVE  95757    CA     3      2    1843
774    8253 KEEGAN WAY  ELK GROVE  95624    CA     0      0       0
775     9204 TROUT WAY  ELK GROVE  95624    CA     4      2    1982

            Type   Sale_date   Price   Latitude   Longitude
115  Residential  2008-05-21  298000  38.401540 -121.447649
774  Residential  2008-05-16  298000  38.446286 -121.400817
775  Residential  2008-05-16  298000  38.422221 -121.375799
('Residential', 299000)                        Street        City    Zip State  Beds  Baths  Sq__ft  \
116  2010 PROMONTORY POINT LN  GOLD RIVER  95670    CA     2      2    1520
776              1828 2ND AVE  SACRAMENTO  95818    CA     2      1    1144

            Type   Sale_date   Price   Latitude   Longitude
116  Residential  2008-05-21  299000  38.628690 -121.261669
776  Residential  2008-05-16  299000  38.556844 -121.490769
('Residential', 299940)             Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
491  62 DE FER CIR  SACRAMENTO  95823    CA     4      2    1876  Residential

      Sale_date   Price  Latitude   Longitude
491  2008-05-19  299940  38.49254 -121.463316
('Residential', 300000)                   Street         City    Zip State  Beds  Baths  Sq__ft  \
280          7320 6TH ST    RIO LINDA  95673    CA     3      1    1284
281        993 MANTON CT         GALT  95632    CA     4      3    2307
282     4487 PANORAMA DR  PLACERVILLE  95667    CA     3      2    1329
777      1113 COMMONS DR   SACRAMENTO  95825    CA     2      2    1623
778  2341 BIG STRIKE TRL         COOL  95614    CA     3      2    1457
779  9452 RED SPRUCE WAY    ELK GROVE  95624    CA     6      3    2555

            Type   Sale_date   Price   Latitude   Longitude
280  Residential  2008-05-20  300000  38.700553 -121.452223
281  Residential  2008-05-20  300000  38.272942 -121.289148
282  Residential  2008-05-20  300000  38.694559 -120.848157
777  Residential  2008-05-16  300000  38.567795 -121.410703
778  Residential  2008-05-16  300000  38.905927 -120.975169
779  Residential  2008-05-16  300000  38.404505 -121.346938
('Residential', 300500)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
283  5651 OVERLEAF WAY  SACRAMENTO  95835    CA     4      2    1910

            Type   Sale_date   Price   Latitude   Longitude
283  Residential  2008-05-20  300500  38.677454 -121.494791
('Residential', 300567)               Street     City    Zip State  Beds  Baths  Sq__ft         Type  \
780  5776 TERRACE DR  ROCKLIN  95765    CA     3      2    1577  Residential

      Sale_date   Price   Latitude   Longitude
780  2008-05-16  300567  38.800539 -121.260979
('Residential', 303000)              Street       City    Zip State  Beds  Baths  Sq__ft         Type  \
781  5908 MCLEAN DR  ELK GROVE  95757    CA     5      3    2592  Residential

      Sale_date   Price  Latitude   Longitude
781  2008-05-16  303000  38.38912 -121.434389
('Residential', 304000)                   Street     City    Zip State  Beds  Baths  Sq__ft  \
492  2513 OLD KENMARE RD  LINCOLN  95648    CA     5      3       0

            Type   Sale_date   Price   Latitude   Longitude
492  Residential  2008-05-19  304000  38.847396 -121.259586
('Residential', 304037)               Street        City    Zip State  Beds  Baths  Sq__ft  \
117  4727 SAVOIE WAY  SACRAMENTO  95835    CA     5      3    2800

            Type   Sale_date   Price   Latitude   Longitude
117  Residential  2008-05-21  304037  38.658182 -121.549521
('Residential', 305000)                        Street            City    Zip State  Beds  Baths  \
284  2015 PROMONTORY POINT LN      GOLD RIVER  95670    CA     3      2
493            3253 ABOTO WAY  RANCHO CORDOVA  95670    CA     4      3
782        8215 PEREGRINE WAY  CITRUS HEIGHTS  95610    CA     3      2

     Sq__ft         Type   Sale_date   Price   Latitude   Longitude
284    1981  Residential  2008-05-20  305000  38.628732 -121.261149
493    1851  Residential  2008-05-19  305000  38.577270 -121.285591
782    1401  Residential  2008-05-16  305000  38.715493 -121.262930
('Residential', 306000)                 Street     City    Zip State  Beds  Baths  Sq__ft  \
783  1104 HILLSDALE LN  LINCOLN  95648    CA     4      2       0

            Type   Sale_date   Price   Latitude  Longitude
783  Residential  2008-05-16  306000  38.865017 -121.32302
('Residential', 306500)               Street       City    Zip State  Beds  Baths  Sq__ft  \
285  3224 PARKHAM DR  ROSEVILLE  95747    CA     0      0       0

            Type   Sale_date   Price   Latitude   Longitude
285  Residential  2008-05-20  306500  38.772771 -121.364877
('Residential', 307000)                     Street       City    Zip State  Beds  Baths  Sq__ft  \
494  3072 VILLAGE PLAZA DR  ROSEVILLE  95747    CA     0      0       0

            Type   Sale_date   Price   Latitude   Longitude
494  Residential  2008-05-19  307000  38.773094 -121.365905
('Residential', 310000)                Street        City    Zip State  Beds  Baths  Sq__ft  \
784   2949 PANAMA AVE  CARMICHAEL  95608    CA     3      2    1502
785  1356 HARTLEY WAY      FOLSOM  95630    CA     3      2    1327
786    633 HANISCH DR   ROSEVILLE  95678    CA     4      3    1800

            Type   Sale_date   Price   Latitude   Longitude
784  Residential  2008-05-16  310000  38.618369 -121.326187
785  Residential  2008-05-16  310000  38.651617 -121.131674
786  Residential  2008-05-16  310000  38.763490 -121.275881
('Residential', 311000)                      Street       City    Zip State  Beds  Baths  Sq__ft  \
118  8664 MAGNOLIA HILL WAY  ELK GROVE  95624    CA     4      2    2309

            Type   Sale_date   Price   Latitude   Longitude
118  Residential  2008-05-21  311000  38.442352 -121.389675
('Residential', 311328)              Street        City    Zip State  Beds  Baths  Sq__ft  \
495  251 CHANGO CIR  SACRAMENTO  95835    CA     4      2    2218

            Type   Sale_date   Price  Latitude   Longitude
495  Residential  2008-05-19  311328  38.68237 -121.539147
('Residential', 311518)                   Street        City    Zip State  Beds  Baths  Sq__ft  \
787  63 ANGEL ISLAND CIR  SACRAMENTO  95831    CA     4      2    2169

            Type   Sale_date   Price   Latitude   Longitude
787  Residential  2008-05-16  311518  38.490408 -121.547664
('Residential', 312000)                Street     City    Zip State  Beds  Baths  Sq__ft         Type  \
788  1571 WILD OAK LN  LINCOLN  95648    CA     5      3    2457  Residential

      Sale_date   Price   Latitude   Longitude
788  2008-05-16  312000  38.844144 -121.274174
('Residential', 312500)             Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
286  15 VANESSA PL  SACRAMENTO  95835    CA     0      0       0  Residential

      Sale_date   Price   Latitude  Longitude
286  2008-05-20  312500  38.668692 -121.54549
('Residential', 313000)                      Street            City    Zip State  Beds  Baths  Sq__ft  \
789  5222 COPPER SUNSET WAY  RANCHO CORDOVA  95742    CA     0      0       0

            Type   Sale_date   Price   Latitude   Longitude
789  Residential  2008-05-16  313000  38.529181 -121.224755
('Residential', 313138)               Street        City    Zip State  Beds  Baths  Sq__ft  \
496  8205 WEYBURN CT  SACRAMENTO  95828    CA     3      2    1394

            Type   Sale_date   Price  Latitude   Longitude
496  Residential  2008-05-19  313138  38.47316 -121.403893
('Residential', 315000)                   Street        City    Zip State  Beds  Baths  Sq__ft  \
287      1312 RENISON LN     LINCOLN  95648    CA     5      3       0
790    5601 SPINDRIFT LN  ORANGEVALE  95662    CA     4      2    2004
791  652 FIFTEEN MILE DR   ROSEVILLE  95678    CA     4      3    2212
792   7921 DOE TRAIL WAY    ANTELOPE  95843    CA     5      3    3134
793         4204 LUSK DR  SACRAMENTO  95864    CA     3      2    1360
794        5321 DELTA DR     ROCKLIN  95765    CA     4      2       0

            Type   Sale_date   Price   Latitude   Longitude
287  Residential  2008-05-20  315000  38.866409 -121.308485
790  Residential  2008-05-16  315000  38.668289 -121.192316
791  Residential  2008-05-16  315000  38.775872 -121.298864
792  Residential  2008-05-16  315000  38.711927 -121.343608
793  Residential  2008-05-16  315000  38.606569 -121.368424
794  Residential  2008-05-16  315000  38.815493 -121.262908
('Residential', 315537)                     Street        City    Zip State  Beds  Baths  Sq__ft  \
119  9570 HARVEST ROSE WAY  SACRAMENTO  95827    CA     5      3    2367

            Type   Sale_date   Price   Latitude   Longitude
119  Residential  2008-05-21  315537  38.555993 -121.340352
('Residential', 316630)                     Street        City    Zip State  Beds  Baths  Sq__ft  \
497  8788 LA MARGARITA WAY  SACRAMENTO  95828    CA     3      2    1410

            Type   Sale_date   Price   Latitude   Longitude
497  Residential  2008-05-19  316630  38.468185 -121.375694
('Residential', 319789)               Street        City    Zip State  Beds  Baths  Sq__ft  \
288  8 RIVER RAFT CT  SACRAMENTO  95823    CA     4      2    2205

            Type   Sale_date   Price   Latitude   Longitude
288  Residential  2008-05-20  319789  38.447353 -121.434969
('Residential', 320000)                   Street            City    Zip State  Beds  Baths  Sq__ft  \
120       4359 CREGAN CT  RANCHO CORDOVA  95742    CA     5      4    3516
121  5337 DUSTY ROSE WAY  RANCHO CORDOVA  95742    CA     0      0       0
498    5912 DEEPDALE WAY       ELK GROVE  95758    CA     5      3    3468
499  4712 PISMO BEACH DR        ANTELOPE  95843    CA     5      3    2346
795    5608 ROSEDALE WAY      SACRAMENTO  95822    CA     3      2    1276

            Type   Sale_date   Price   Latitude   Longitude
120  Residential  2008-05-21  320000  38.545128 -121.224922
121  Residential  2008-05-21  320000  38.528575 -121.228600
498  Residential  2008-05-19  320000  38.439565 -121.436606
499  Residential  2008-05-19  320000  38.707705 -121.354153
795  Residential  2008-05-16  320000  38.525115 -121.518689
('Residential', 322000)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
796  3372 BERETANIA WAY  SACRAMENTO  95834    CA     4      3    2962

            Type   Sale_date   Price  Latitude  Longitude
796  Residential  2008-05-16  322000  38.64977 -121.53448
('Residential', 325000)                    Street      City    Zip State  Beds  Baths  Sq__ft  \
500  4741 PACIFIC PARK DR  ANTELOPE  95843    CA     5      3    2347
797      2422 STEFANIE DR   ROCKLIN  95765    CA     4      2    1888

            Type   Sale_date   Price   Latitude   Longitude
500  Residential  2008-05-19  325000  38.709299 -121.353056
797  Residential  2008-05-16  325000  38.822730 -121.264240
('Residential', 325500)               Street       City    Zip State  Beds  Baths  Sq__ft  \
798  3232 PARKHAM DR  ROSEVILLE  95747    CA     0      0       0

            Type   Sale_date   Price   Latitude   Longitude
798  Residential  2008-05-16  325500  38.772821 -121.364821
('Residential', 326951)              Street       City    Zip State  Beds  Baths  Sq__ft         Type  \
799  448 ELMWOOD CT  ROSEVILLE  95678    CA     3      2       0  Residential

      Sale_date   Price   Latitude   Longitude
799  2008-05-16  326951  38.771917 -121.304439
('Residential', 328360)                    Street        City    Zip State  Beds  Baths  Sq__ft  \
122  8929 SUTTERS GOLD DR  SACRAMENTO  95826    CA     4      3    1914

            Type   Sale_date   Price   Latitude   Longitude
122  Residential  2008-05-21  328360  38.550848 -121.370224
('Residential', 328370)                Street  City    Zip State  Beds  Baths  Sq__ft         Type  \
800  1214 DAWNWOOD DR  GALT  95632    CA     3      2    1548  Residential

      Sale_date   Price   Latitude   Longitude
800  2008-05-16  328370  38.290119 -121.286023
('Residential', 328578)             Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
501  310 GROTH CIR  SACRAMENTO  95834    CA     4      2    1659  Residential

      Sale_date   Price   Latitude   Longitude
501  2008-05-19  328578  38.638764 -121.531827
('Residential', 330000)                 Street            City    Zip State  Beds  Baths  Sq__ft  \
289  2251 LAMPLIGHT LN         LINCOLN  95648    CA     2      2    1449
290      106 FARHAM DR          FOLSOM  95630    CA     3      2    1258
801    1440 EMERALD LN         LINCOLN  95648    CA     2      2       0
802    3349 CORVINA DR  RANCHO CORDOVA  95670    CA     4      3    2109

            Type   Sale_date   Price   Latitude   Longitude
289  Residential  2008-05-20  330000  38.849924 -121.275729
290  Residential  2008-05-20  330000  38.667834 -121.168578
801  Residential  2008-05-16  330000  38.861864 -121.267478
802  Residential  2008-05-16  330000  38.580545 -121.279016
('Residential', 331000)                Street       City    Zip State  Beds  Baths  Sq__ft  \
291   5405 NECTAR CIR  ELK GROVE  95757    CA     3      2    2575
502  6121 WILD FOX CT  ELK GROVE  95757    CA     3      3    2442

            Type   Sale_date   Price   Latitude   Longitude
291  Residential  2008-05-20  331000  38.387014 -121.440967
502  Residential  2008-05-19  331000  38.406758 -121.431669
('Residential', 331200)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
803  10254 JULIANA WAY  SACRAMENTO  95827    CA     4      2    2484

            Type   Sale_date   Price  Latitude   Longitude
803  Residential  2008-05-16  331200  38.56803 -121.309966
('Residential', 331500)                    Street            City    Zip State  Beds  Baths  Sq__ft  \
503  12241 CANYONLANDS DR  RANCHO CORDOVA  95742    CA     0      0       0


('Residential', 334000)                    Street        City    Zip State  Beds  Baths  Sq__ft  \
292         5411 10TH AVE  SACRAMENTO  95820    CA     2      1     539
805  580 REGENCY PARK CIR  SACRAMENTO  95835    CA     3      3    2212

            Type   Sale_date   Price   Latitude   Longitude
292  Residential  2008-05-20  334000  38.542727 -121.442449
805  Residential  2008-05-16  334000  38.674864 -121.495800
('Residential', 334150)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
123  8025 PEERLESS AVE  ORANGEVALE  95662    CA     2      1    1690

            Type   Sale_date   Price  Latitude   Longitude
123  Residential  2008-05-21  334150  38.71147 -121.216214
('Residential', 335000)             Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
806  5544 CAMAS CT  ORANGEVALE  95662    CA     3      2    1616  Residential

      Sale_date   Price   Latitude   Longitude
806  2008-05-16  335000  38.667703 -121.209456
('Residential', 335750)                Street       City    Zip State  Beds  Baths  Sq__ft  \
124   4620 WELERA WAY  ELK GROVE  95757    CA     3      3    2725
125  9723 TERRAPIN CT  ELK GROVE  95757    CA     4      3    2354

            Type   Sale_date   Price   Latitude   Longitude
124  Residential  2008-05-21  335750  38.398609 -121.450148
125  Residential  2008-05-21  335750  38.403492 -121.430224
('Residential', 336000)                 Street            City    Zip State  Beds  Baths  Sq__ft  \
293  3512 RAINSONG CIR  RANCHO CORDOVA  95670    CA     4      3    2208

            Type   Sale_date   Price   Latitude   Longitude
293  Residential  2008-05-20  336000  38.573488 -121.282809
('Residential', 339000)               Street        City    Zip State  Beds  Baths  Sq__ft  \
294     1106 55TH ST  SACRAMENTO  95819    CA     3      1    1108
295  411 ILLSLEY WAY      FOLSOM  95630    CA     4      2    1595

            Type   Sale_date   Price   Latitude   Longitude
294  Residential  2008-05-20  339000  38.563805 -121.436395
295  Residential  2008-05-20  339000  38.652002 -121.129504
('Residential', 339500)                   Street        City    Zip State  Beds  Baths  Sq__ft  \
126  2115 SMOKESTACK WAY  SACRAMENTO  95833    CA     0      0       0

            Type   Sale_date   Price   Latitude   Longitude
126  Residential  2008-05-21  339500  38.602416 -121.542965
('Residential', 340000)                   Street        City    Zip State  Beds  Baths  Sq__ft  \
504  29 COOL FOUNTAIN CT  SACRAMENTO  95833    CA     4      2    2155

            Type   Sale_date   Price   Latitude  Longitude
504  Residential  2008-05-19  340000  38.606906 -121.54132
('Residential', 341000)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
807  5102 ARCHCREST WAY  SACRAMENTO  95835    CA     4      2    2372

            Type   Sale_date   Price  Latitude   Longitude
807  Residential  2008-05-16  341000  38.66841 -121.494639
('Residential', 344250)               Street    City    Zip State  Beds  Baths  Sq__ft         Type  \
127  100 REBECCA WAY  FOLSOM  95630    CA     3      2    2185  Residential

      Sale_date   Price  Latitude   Longitude
127  2008-05-21  344250  38.68479 -121.149199
('Residential', 344755)                  Street        City    Zip State  Beds  Baths  Sq__ft  \
505  907 RIO ROBLES AVE  SACRAMENTO  95838    CA     0      0       0

            Type   Sale_date   Price   Latitude   Longitude
505  Residential  2008-05-19  344755  38.664765 -121.445006
('Residential', 345000)                 Street  City    Zip State  Beds  Baths  Sq__ft         Type  \
296  796 BUTTERCUP CIR  GALT  95632    CA     4      2    2159  Residential

      Sale_date   Price   Latitude   Longitude
296  2008-05-20  345000  38.279581 -121.300828
('Residential', 345746)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
506  8909 BILLFISH WAY  SACRAMENTO  95828    CA     3      2    1810

            Type   Sale_date   Price   Latitude   Longitude
506  Residential  2008-05-19  345746  38.475433 -121.372584
('Residential', 346210)                    Street       City    Zip State  Beds  Baths  Sq__ft  \
128  9488 OAK VILLAGE WAY  ELK GROVE  95758    CA     4      2    1801

            Type   Sale_date   Price  Latitude   Longitude
128  Residential  2008-05-21  346210  38.41333 -121.404999
('Residential', 346375)              Street     City    Zip State  Beds  Baths  Sq__ft         Type  \
808  5725 BALFOR RD  ROCKLIN  95765    CA     5      3    2606  Residential

      Sale_date   Price   Latitude   Longitude
808  2008-05-16  346375  38.807816 -121.270008
('Residential', 347029)                Street        City    Zip State  Beds  Baths  Sq__ft  \
129  8495 DARTFORD DR  SACRAMENTO  95823    CA     3      3    1961

            Type   Sale_date   Price   Latitude   Longitude
129  Residential  2008-05-21  347029  38.448507 -121.421346
('Residential', 347225)                Street       City    Zip State  Beds  Baths  Sq__ft  \
809  7697 ROSEHALL DR  ROSEVILLE  95678    CA     5      3       0

            Type   Sale_date   Price  Latitude  Longitude
809  Residential  2008-05-16  347225  38.79218 -121.28595
('Residential', 347650)                     Street       City    Zip State  Beds  Baths  Sq__ft  \
130  6708 PONTA DO SOL WAY  ELK GROVE  95757    CA     4      2    3134

            Type   Sale_date   Price   Latitude   Longitude
130  Residential  2008-05-21  347650  38.380635 -121.425538
('Residential', 349000)               Street       City    Zip State  Beds  Baths  Sq__ft  \
810  4821 HUTSON WAY  ELK GROVE  95757    CA     5      3    2877

            Type   Sale_date   Price   Latitude   Longitude
810  Residential  2008-05-16  349000  38.386239 -121.448159
('Residential', 350000)                   Street         City    Zip State  Beds  Baths  Sq__ft  \
297      1230 SANDRA CIR  PLACERVILLE  95667    CA     4      3    2295
811        4509 WINJE DR     ANTELOPE  95843    CA     3      2    2960
812  1965 LAURELHURST LN      LINCOLN  95648    CA     2      2       0
813  6709 ROSE BRIDGE DR    ROSEVILLE  95678    CA     3      2    2172

            Type   Sale_date   Price   Latitude   Longitude
297  Residential  2008-05-20  350000  38.738141 -120.784145
811  Residential  2008-05-16  350000  38.709513 -121.359357
812  Residential  2008-05-16  350000  38.853869 -121.271742
813  Residential  2008-05-16  350000  38.792461 -121.275711
('Residential', 351000)                     Street        City    Zip State  Beds  Baths  Sq__ft  \
507           6232 GUS WAY   ELK GROVE  95757    CA     4      2    2789
815  7709 RIVER VILLAGE DR  SACRAMENTO  95831    CA     3      2    1795

            Type   Sale_date   Price   Latitude  Longitude
507  Residential  2008-05-19  351000  38.388129 -121.43117
815  Residential  2008-05-16  351000  38.483212 -121.54019
('Residential', 351300)                   Street        City    Zip State  Beds  Baths  Sq__ft  \
131  4143 SEA MEADOW WAY  SACRAMENTO  95823    CA     4      3    1915

            Type   Sale_date   Price  Latitude   Longitude
131  Residential  2008-05-21  351300  38.46534 -121.457519
('Residential', 352000)                   Street             City    Zip State  Beds  Baths  Sq__ft  \
132  3020 RICHARDSON CIR  EL DORADO HILLS  95762    CA     3      2       0

            Type   Sale_date   Price   Latitude   Longitude
132  Residential  2008-05-21  352000  38.691299 -121.081752
('Residential', 353767)               Street  City    Zip State  Beds  Baths  Sq__ft         Type  \
508  200 OAKWILDE ST  GALT  95632    CA     4      2    1606  Residential

      Sale_date   Price  Latitude  Longitude
508  2008-05-19  353767   38.2535 -121.31812
('Residential', 355000)                   Street  City    Zip State  Beds  Baths  Sq__ft         Type  \
509  1033 PARK STREAM DR  GALT  95632    CA     0      0       0  Residential

      Sale_date   Price   Latitude   Longitude
509  2008-05-19  355000  38.287785 -121.289903
('Residential', 356000)              Street       City    Zip State  Beds  Baths  Sq__ft         Type  \
298  318 ANACAPA DR  ROSEVILLE  95678    CA     3      2    1838  Residential

      Sale_date   Price   Latitude   Longitude
298  2008-05-20  356000  38.782094 -121.297133
('Residential', 356035)               Street        City    Zip State  Beds  Baths  Sq__ft  \
510  200 ALLAIRE CIR  SACRAMENTO  95835    CA     4      2    2166

            Type   Sale_date   Price  Latitude  Longitude
510  Residential  2008-05-19  356035  38.68318 -121.53484
('Residential', 356200)                 Street             City    Zip State  Beds  Baths  Sq__ft  \
816  4165 BRISBANE CIR  EL DORADO HILLS  95762    CA     3      2       0

            Type   Sale_date   Price   Latitude   Longitude
816  Residential  2008-05-16  356200  38.686067 -121.073413
('Residential', 360000)              Street       City    Zip State  Beds  Baths  Sq__ft         Type  \
817  506 BEDFORD CT  ROSEVILLE  95661    CA     4      2    2295  Residential

      Sale_date   Price   Latitude   Longitude
817  2008-05-16  360000  38.733985 -121.236766
('Residential', 360552)                Street        City    Zip State  Beds  Baths  Sq__ft  \
512  5479 NICKMAN WAY  SACRAMENTO  95835    CA     4      2    1871

            Type   Sale_date   Price   Latitude   Longitude
512  Residential  2008-05-19  360552  38.672966 -121.502748
('Residential', 361745)                    Street        City    Zip State  Beds  Baths  Sq__ft  \
299  3975 SHINING STAR DR  SACRAMENTO  95823    CA     4      2    1900

            Type   Sale_date   Price   Latitude   Longitude
299  Residential  2008-05-20  361745  38.487409 -121.461413
('Residential', 361948)              Street        City    Zip State  Beds  Baths  Sq__ft  \
300  1620 BASLER ST  SACRAMENTO  95811    CA     4      2    1718

            Type   Sale_date   Price   Latitude   Longitude
300  Residential  2008-05-20  361948  38.591822 -121.478644
('Residential', 362305)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
513  2103 BURBERRY WAY  SACRAMENTO  95835    CA     3      2    1800

            Type   Sale_date   Price  Latitude   Longitude
513  Residential  2008-05-19  362305  38.67342 -121.508542
('Residential', 365000)                 Street        City    Zip State  Beds  Baths  Sq__ft  \
514  2450 SAN JOSE WAY  SACRAMENTO  95817    CA     3      1    1683

            Type   Sale_date   Price   Latitude   Longitude
514  Residential  2008-05-19  365000  38.553596 -121.459483
('Residential', 367463)                     Street       City    Zip State  Beds  Baths  Sq__ft  \
818  9048 PINTO CANYON WAY  ROSEVILLE  95747    CA     4      3    2577

            Type   Sale_date   Price   Latitude   Longitude
818  Residential  2008-05-16  367463  38.792493 -121.331899
('Residential', 367554)                Street       City    Zip State  Beds  Baths  Sq__ft  \
515  7641 ROSEHALL DR  ROSEVILLE  95678    CA     3      2       0

            Type   Sale_date   Price   Latitude   Longitude
515  Residential  2008-05-19  367554  38.791617 -121.286147
('Residential', 368500)                   Street       City    Zip State  Beds  Baths  Sq__ft  \
516  1336 LAYSAN TEAL DR  ROSEVILLE  95747    CA     0      0       0

            Type   Sale_date   Price   Latitude   Longitude
516  Residential  2008-05-19  368500  38.796121 -121.319963
('Residential', 370000)                     Street        City    Zip State  Beds  Baths  Sq__ft  \
133     8082 LINDA ISLE LN  SACRAMENTO  95831    CA     0      0       0
301  9688 NATURE TRAIL WAY   ELK GROVE  95757    CA     5      3    3389
517      2802 BLACK OAK DR     ROCKLIN  95765    CA     2      2    1596

            Type   Sale_date   Price   Latitude   Longitude
133  Residential  2008-05-21  370000  38.477200 -121.521500
301  Residential  2008-05-20  370000  38.405224 -121.479275
517  Residential  2008-05-19  370000  38.837006 -121.232024
('Residential', 370500)                        Street            City    Zip State  Beds  Baths  \
134  15300 MURIETA SOUTH PKWY  RANCHO MURIETA  95683    CA     4      3

     Sq__ft         Type   Sale_date   Price  Latitude   Longitude
134    2734  Residential  2008-05-21  370500   38.4874 -121.075129
('Residential', 371086)                  Street         City    Zip State  Beds  Baths  Sq__ft  \
518  2113 FALL TRAIL CT  PLACERVILLE  95667    CA     4      2       0

            Type   Sale_date   Price   Latitude   Longitude
518  Residential  2008-05-19  371086  38.733155 -120.748039
('Residential', 372000)                  Street    City    Zip State  Beds  Baths  Sq__ft  \
135  11215 SHARRMONT CT  WILTON  95693    CA     3      2    2110

            Type   Sale_date   Price  Latitude   Longitude
135  Residential  2008-05-21  372000  38.35062 -121.228349
('Residential', 375000)                  Street       City    Zip State  Beds  Baths  Sq__ft  \
136    7105 DANBERG WAY  ELK GROVE  95757    CA     5      3    3164
819  2274 IVY BRIDGE DR  ROSEVILLE  95747    CA     0      0       0

            Type   Sale_date   Price   Latitude   Longitude
136  Residential  2008-05-21  375000  38.401900 -121.420388
819  Residential  2008-05-16  375000  38.778561 -121.362008
('Residential', 378000)                Street       City    Zip State  Beds  Baths  Sq__ft  \
519  10112 LAMBEAU CT  ELK GROVE  95757    CA     3      2    1179

            Type   Sale_date   Price   Latitude   Longitude
519  Residential  2008-05-19  378000  38.390328 -121.448022
('Residential', 380000)                Street          City    Zip State  Beds  Baths  Sq__ft  \
302    5924 TANUS CIR       ROCKLIN  95677    CA     4      2       0
820  14004 WALNUT AVE  WALNUT GROVE  95690    CA     3      1    1727

            Type   Sale_date   Price   Latitude   Longitude
302  Residential  2008-05-20  380000  38.778691 -121.204292
820  Residential  2008-05-16  380000  38.247659 -121.515129
('Residential', 380578)                 Street       City    Zip State  Beds  Baths  Sq__ft  \
821  6905 FRANKFORT CT  ELK GROVE  95758    CA     3      2    1485

            Type   Sale_date   Price   Latitude   Longitude
821  Residential  2008-05-16  380578  38.429139 -121.423444
('Residential', 381300)                     Street        City    Zip State  Beds  Baths  Sq__ft  \
137  5579 JERRY LITELL WAY  SACRAMENTO  95835    CA     5      3    3599

            Type   Sale_date   Price   Latitude   Longitude
137  Residential  2008-05-21  381300  38.677126 -121.500519
('Residential', 381942)                Street        City    Zip State  Beds  Baths  Sq__ft  \
138  1050 FOXHALL WAY  SACRAMENTO  95831    CA     4      2    2054

            Type   Sale_date   Price   Latitude   Longitude
138  Residential  2008-05-21  381942  38.509819 -121.519661
('Residential', 383000)                     Street       City    Zip State  Beds  Baths  Sq__ft  \
520  6313 CASTRO VERDE WAY  ELK GROVE  95757    CA     0      0       0

            Type   Sale_date   Price   Latitude  Longitude
520  Residential  2008-05-19  383000  38.381102 -121.42901
('Residential', 385000)                  Street       City    Zip State  Beds  Baths  Sq__ft  \
303  9629 CEDAR OAK WAY  ELK GROVE  95757    CA     5      4    3260

            Type   Sale_date   Price   Latitude   Longitude
303  Residential  2008-05-20  385000  38.405527 -121.431746
('Residential', 386222)              Street        City    Zip State  Beds  Baths  Sq__ft  \
822  3621 WINTUN DR  CARMICHAEL  95608    CA     3      2    1655

            Type   Sale_date   Price   Latitude   Longitude
822  Residential  2008-05-16  386222  38.629929 -121.323086
('Residential', 387731)                  Street      City    Zip State  Beds  Baths  Sq__ft  \
139  7837 ABBINGTON WAY  ANTELOPE  95843    CA     4      2    1830

            Type   Sale_date   Price   Latitude   Longitude
139  Residential  2008-05-21  387731  38.709873 -121.339472
('Residential', 388000)              Street        City    Zip State  Beds  Baths  Sq__ft  \
521  3622 CURTIS DR  SACRAMENTO  95818    CA     3      1    1639

            Type   Sale_date   Price   Latitude   Longitude
521  Residential  2008-05-19  388000  38.541735 -121.480098
('Residential', 389000)               Street     City    Zip State  Beds  Baths  Sq__ft         Type  \
823  201 KIRKLAND CT  LINCOLN  95648    CA     0      0       0  Residential

      Sale_date   Price   Latitude   Longitude
823  2008-05-16  389000  38.867125 -121.319085
('Residential', 390000)                   Street            City    Zip State  Beds  Baths  Sq__ft  \
824  12075 APPLESBURY CT  RANCHO CORDOVA  95742    CA     0      0       0

            Type   Sale_date   Price  Latitude  Longitude
824  Residential  2008-05-16  390000   38.5357  -121.2249
('Residential', 391000)         Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
140  1300 F ST  SACRAMENTO  95814    CA     3      3    1627  Residential

      Sale_date   Price  Latitude   Longitude
140  2008-05-21  391000  38.58355 -121.487289
('Residential', 394470)               Street       City    Zip State  Beds  Baths  Sq__ft  \
141  6801 RAWLEY WAY  ELK GROVE  95757    CA     4      3    3440

            Type   Sale_date   Price   Latitude   Longitude
141  Residential  2008-05-21  394470  38.408351 -121.423925
('Residential', 395000)                    Street       City    Zip State  Beds  Baths  Sq__ft  \
142  1693 SHELTER COVE DR  GREENWOOD  95635    CA     3      2    2846

            Type   Sale_date   Price   Latitude   Longitude
142  Residential  2008-05-21  395000  38.945357 -120.908822
('Residential', 395100)                    Street            City    Zip State  Beds  Baths  Sq__ft  \
522  11817 OPAL RIDGE WAY  RANCHO CORDOVA  95742    CA     5      3    3281

            Type   Sale_date   Price   Latitude   Longitude
522  Residential  2008-05-19  395100  38.551083 -121.237476
('Residential', 395500)                   Street       City    Zip State  Beds  Baths  Sq__ft  \
825  1975 SIDESADDLE WAY  ROSEVILLE  95661    CA     3      2    2049

            Type   Sale_date   Price   Latitude   Longitude
825  Residential  2008-05-16  395500  38.737872 -121.249025
('Residential', 396000)                     Street            City    Zip State  Beds  Baths  Sq__ft  \
826  5420 ALMOND FALLS WAY  RANCHO CORDOVA  95742    CA     0      0       0

            Type   Sale_date   Price   Latitude   Longitude
826  Residential  2008-05-16  396000  38.527384 -121.233531
('Residential', 397000)                 Street       City    Zip State  Beds  Baths  Sq__ft  \
827  9677 PILLITERI CT  ELK GROVE  95757    CA     5      3    2875

            Type   Sale_date   Price   Latitude   Longitude
827  Residential  2008-05-16  397000  38.405571 -121.445186
('Residential', 399000)                 Street          City    Zip State  Beds  Baths  Sq__ft  \
304  3429 FERNBROOK CT  CAMERON PARK  95682    CA     3      2    2016

            Type   Sale_date   Price   Latitude   Longitude
304  Residential  2008-05-20  399000  38.664225 -121.007173
('Residential', 400000)                       Street             City    Zip State  Beds  Baths  \
523      170 LAGOMARSINO WAY       SACRAMENTO  95819    CA     3      2
524           2743 DEAKIN PL  EL DORADO HILLS  95762    CA     3      2
828  1515 EL CAMINO VERDE DR          LINCOLN  95648    CA     0      0
829            556 PLATT CIR  EL DORADO HILLS  95762    CA     4      2

     Sq__ft         Type   Sale_date   Price   Latitude   Longitude
523    1697  Residential  2008-05-19  400000  38.574894 -121.435806
524       0  Residential  2008-05-19  400000  38.692880 -121.073551
828       0  Residential  2008-05-16  400000  38.904869 -121.320750
829    2199  Residential  2008-05-16  400000  38.656299 -121.079783
('Residential', 400186)               Street       City    Zip State  Beds  Baths  Sq__ft  \

('Residential', 676200)                  Street         City    Zip State  Beds  Baths  Sq__ft  \
550  4629 DORCHESTER LN  GRANITE BAY  95746    CA     5      3    2896

            Type   Sale_date   Price   Latitude   Longitude
550  Residential  2008-05-19  676200  38.723545 -121.216025
('Residential', 677048)                   Street         City    Zip State  Beds  Baths  Sq__ft  \
551  2400 COUNTRYSIDE DR  PLACERVILLE  95667    CA     3      2    2025

            Type   Sale_date   Price   Latitude   Longitude
551  Residential  2008-05-19  677048  38.737452 -120.910963
('Residential', 680000)                      Street             City    Zip State  Beds  Baths  \
332            4128 HILL ST        FAIR OAKS  95628    CA     5      5
862  2065 IMPRESSIONIST WAY  EL DORADO HILLS  95762    CA     0      0

     Sq__ft         Type   Sale_date   Price   Latitude   Longitude
332    2846  Residential  2008-05-20  680000  38.641670 -121.262099
862       0  Residential  2008-05-16  680000  38.682961 -121.033253
('Residential', 691659)                Street    City    Zip State  Beds  Baths  Sq__ft         Type  \
552  12901 FURLONG DR  WILTON  95693    CA     5      3    3788  Residential

      Sale_date   Price   Latitude   Longitude
552  2008-05-19  691659  38.413535 -121.188211
('Residential', 699000)            Street        City    Zip State  Beds  Baths  Sq__ft         Type  \
333  1409 47TH ST  SACRAMENTO  95819    CA     5      2    2484  Residential

      Sale_date   Price   Latitude   Longitude
333  2008-05-20  699000  38.563244 -121.446876
('Residential', 760000)                       Street         City    Zip State  Beds  Baths  Sq__ft  \
553  6222 CALLE MONTALVO CIR  GRANITE BAY  95746    CA     5      3    3670

            Type   Sale_date   Price   Latitude   Longitude
553  Residential  2008-05-19  760000  38.779435 -121.146676
('Residential', 830000)            Street             City    Zip State  Beds  Baths  Sq__ft  \
157  315 JUMEL CT  EL DORADO HILLS  95762    CA     6      5       0

            Type   Sale_date   Price   Latitude  Longitude
157  Residential  2008-05-21  830000  38.669931 -121.05958
('Residential', 839000)                Street    City    Zip State  Beds  Baths  Sq__ft         Type  \
334  3935 EL MONTE DR  LOOMIS  95650    CA     4      4    1624  Residential

      Sale_date   Price   Latitude   Longitude
334  2008-05-20  839000  38.813337 -121.133348
('Residential', 879000)                Street             City    Zip State  Beds  Baths  Sq__ft  \
863  2982 ABERDEEN LN  EL DORADO HILLS  95762    CA     4      3       0

            Type   Sale_date   Price   Latitude   Longitude
863  Residential  2008-05-16  879000  38.706692 -121.058869
('Residential', 884790)                    Street    City    Zip State  Beds  Baths  Sq__ft  \
864  9401 BARREL RACER CT  WILTON  95693    CA     4      3    4400

            Type   Sale_date   Price   Latitude   Longitude
864  Residential  2008-05-16  884790  38.415298 -121.194858
('Unkown', 275000)                 Street             City    Zip State  Beds  Baths  Sq__ft  \
757  6007 MARYBELLE LN  SHINGLE SPRINGS  95682    CA     0      0       0

       Type   Sale_date   Price  Latitude   Longitude
757  Unkown  2008-05-16  275000  38.64347 -120.888183

In [32]:
# So now lets use the groupby() function and agg() to calculate the average price of different type of house
df2.groupby("Type").agg({"Price":(np.sum, np.average)
                        ,"Sq__ft": (np.average)})

                  Price                      Sq__ft
                    sum        average      average
Type
Condo           8104438  150082.185185   760.425926
Multi-Family    2918951  224534.692308  2046.923077
Residential   219333711  239186.162486  1338.625954
Unkown           275000  275000.000000     0.000000

So we are doing a group by on the dataframe object by the column "type". This creates a new Groupby object. Then we are invoking agg() function on that object. The agg function is going to apply one or more functions we specify to the GroupedBy dataframe and return a single row per dataframe/group

## Transformation

When agg() return a single-value per column, so one row per group, transform() returns an object that is the same size as the group. It broadcasts the function you supply over the grouped dataframe, returning a new dataframe.

In [34]:
# create sub-set of columns
columns = ["Type", "Price"]
# Now transform it and store in a different dataframe
transform_df = df2[columns].groupby("Type").transform(np.average)
transform_df.head()

           Price
0  239186.162486
1  239186.162486
2  239186.162486
3  239186.162486
4  239186.162486

In [35]:
transform_df.rename({"Price": "Average Price"}, axis='columns', inplace=True)
# Now lets merge the 2 df together
df2=df2.merge(transform_df, left_index=True, right_index=True)

In [36]:
df2.head()

,Street,City,Zip,State,Beds,Baths,Sq__ft,Type,Sale_date,Price,Latitude,Longitude,Average Price
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,2008-05-21,59222,38.631913,-121.434879,239186.162486
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,2008-05-21,68212,38.478902,-121.431028,239186.162486
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,2008-05-21,68880,38.618305,-121.443839,239186.162486
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,2008-05-21,69307,38.616835,-121.439146,239186.162486
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,2008-05-21,81900,38.519470,-121.435768,239186.162486

In [38]:
# Take use of the newly added column for analysis
df2["Mean_price_diff"] = df2['Price']-df2['Average Price']

In [39]:
df2.head()

,Street,City,Zip,State,Beds,Baths,Sq__ft,Type,Sale_date,Price,Latitude,Longitude,Average Price,Mean_price_diff
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,2008-05-21,59222,38.631913,-121.434879,239186.162486,-179964.162486
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,2008-05-21,68212,38.478902,-121.431028,239186.162486,-170974.162486
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,2008-05-21,68880,38.618305,-121.443839,239186.162486,-170306.162486
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,2008-05-21,69307,38.616835,-121.439146,239186.162486,-169879.162486
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,2008-05-21,81900,38.519470,-121.435768,239186.162486,-157286.162486

## Filtering

The GroupBy object has build in support for filtering groups as well. It's often that you'll want to group
by some feature, then make some transformation to the groups, then drop certain groups as part of your
cleaning routines. The filter() function takes in a function which it applies to each group dataframe and
returns either a True or a False, depending upon whether that group should be included in the results.

In [41]:
df2.groupby("Type").filter(lambda x: np.average(x["Price"])>200000)

,Street,City,Zip,State,Beds,Baths,Sq__ft,Type,Sale_date,Price,Latitude,Longitude,Average Price,Mean_price_diff
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,2008-05-21,59222,38.631913,-121.434879,239186.162486,-179964.162486
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,2008-05-21,68212,38.478902,-121.431028,239186.162486,-170974.162486
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,2008-05-21,68880,38.618305,-121.443839,239186.162486,-170306.162486
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,2008-05-21,69307,38.616835,-121.439146,239186.162486,-169879.162486
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,2008-05-21,81900,38.519470,-121.435768,239186.162486,-157286.162486
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980,9169 GARLINGTON CT,SACRAMENTO,95829,CA,4,3,2280,Residential,2008-05-15,232425,38.457679,-121.359620,239186.162486,-6761.162486
981,6932 RUSKUT WAY,SACRAMENTO,95823,CA,3,2,1477,Residential,2008-05-15,234000,38.499893,-121.458890,239186.162486,-5186.162486
982,7933 DAFFODIL WAY,CITRUS HEIGHTS,95610,CA,3,2,1216,Residential,2008-05-15,235000,38.708824,-121.256803,239186.162486,-4186.162486
983,8304 RED FOX WAY,ELK GROVE,95758,CA,4,2,1685,Residential,2008-05-15,235301,38.417000,-121.397424,239186.162486,-3885.162486
984,3882 YELLOWSTONE LN,EL DORADO HILLS,95762,CA,3,2,1362,Residential,2008-05-15,235738,38.655245,-121.075915,239186.162486,-3448.162486

## Applying

By far the most common operation I invoke on groupby objects is the apply() function. This allows you to
apply an arbitrary function to each group, and stitch the results back for each apply() into a single
dataframe where the index is preserved.

In [42]:
df3 = df2[["Type", "Price"]]
def cal_mean_review_scores(group):
    avg=np.average(group["Price"])
    group['Type']=np.abs(avg-group['Price'])
    return group
df3.groupby("Type").apply(cal_mean_review_scores).head()

            Type  Price
0  179964.162486  59222
1  170974.162486  68212
2  170306.162486  68880
3  169879.162486  69307
4  157286.162486  81900

## Nominal Data ( or Categorical data)

In [3]:
df=pd.DataFrame(["A+", "A", "A", "B+", "B", "B-", "C+", "C", "C-", "D+", "D"],
               index=['excellent', 'excellent', 'excellent', 'good', 'good', 'good', 'ok', 'ok', 'ok', 'poor', 'poor'],
               columns=["Grades"])
df

          Grades
excellent     A+
excellent      A
excellent      A
good          B+
good           B
good          B-
ok            C+
ok             C
ok            C-
poor          D+
poor           D

In [4]:
df.dtypes

Grades    object
dtype: object

In [5]:
# We can change the grades column of the df to be categorical type
df['Grades'].astype('category').head()

excellent    A+
excellent     A
excellent     A
good         B+
good          B
Name: Grades, dtype: category
Categories (10, object): ['A', 'A+', 'B', 'B+', ..., 'C+', 'C-', 'D', 'D+']

In [9]:
# You are not only able to have categorical data, but it can be ordered as well
my_categories=pd.CategoricalDtype(categories=['D','D+','C-','C','C+','B-','B','B+','A-','A','A+']
                                             ,ordered=True)
grades=df['Grades'].astype(my_categories)
grades.head()

excellent    A+
excellent     A
excellent     A
good         B+
good          B
Name: Grades, dtype: category
Categories (11, object): ['D' < 'D+' < 'C-' < 'C' ... 'B+' < 'A-' < 'A' < 'A+']

In [12]:
# unordered
df[df['Grades']>'C+']

     Grades
ok       C-
poor     D+
poor      D

In [13]:
# ordered
grades[grades>"C+"]

excellent    A+
excellent     A
excellent     A
good         B+
good          B
good         B-
Name: Grades, dtype: category
Categories (11, object): ['D' < 'D+' < 'C-' < 'C' ... 'B+' < 'A-' < 'A' < 'A+']

# Pivot Table

A pivot table is a way of summarizing data for a particular purpose. It makes use of the aggregation function. A pivot table is itself a DataFrame, where the rows represent one variable, the column are other different informational aspects of that variable.

In [16]:
df=pd.read_csv("C:\\Users\\AD\\Desktop\\Introduction to Data Science in Python/cwurData.csv")
df.head()

,world_rank,institution,country,national_rank,quality_of_education,alumni_employment,quality_of_faculty,publications,influence,citations,broad_impact,patents,score,year
0,1,Harvard University,USA,1,7,9,1,1,1,1,NaN,5,100.00,2012
1,2,Massachusetts Institute of Technology,USA,2,9,17,3,12,4,4,NaN,1,91.67,2012
2,3,Stanford University,USA,3,17,11,5,4,2,2,NaN,15,89.50,2012
3,4,University of Cambridge,United Kingdom,1,10,24,4,16,16,11,NaN,50,86.17,2012
4,5,California Institute of Technology,USA,4,2,29,7,37,22,22,NaN,18,85.21,2012

In [36]:
# So the task here is to create a Rank_level column where world_rank
# 1-100: first tier 101-200: second tier and >200 would be other top universities
# first: create the function rank_level
def rank_level(group):
    if group>=1 and group<101:
        return "First Tier Top Universities"
    elif group>=101 and group<201:
        return "Second Tier Top Universities"
    elif group>=201 and group<301:
        return "Third Tier Top Universities"
    else:
        return "Other Top Universities"

# next: use the apply to apply that function to every item in a serie
df['Rank_Level']=df['world_rank'].apply(lambda x: rank_level(x))

In [37]:
df.head()

,world_rank,institution,country,national_rank,quality_of_education,alumni_employment,quality_of_faculty,publications,influence,citations,broad_impact,patents,score,year,Rank_Level
0,1,Harvard University,USA,1,7,9,1,1,1,1,NaN,5,100.00,2012,First Tier Top Universities
1,2,Massachusetts Institute of Technology,USA,2,9,17,3,12,4,4,NaN,1,91.67,2012,First Tier Top Universities
2,3,Stanford University,USA,3,17,11,5,4,2,2,NaN,15,89.50,2012,First Tier Top Universities
3,4,University of Cambridge,United Kingdom,1,10,24,4,16,16,11,NaN,50,86.17,2012,First Tier Top Universities
4,5,California Institute of Technology,USA,4,2,29,7,37,22,22,NaN,18,85.21,2012,First Tier Top Universities

In [43]:
df.pivot_table(values="score", index="country", columns='Rank_Level',aggfunc=[np.mean, np.min]).head()
# So we are pivoting a table where the column country is set as index, rank level is the feature and each row contains value of scores.
# But these values of score will be aggregated by the np.mean function => return the mean

                                  mean                         \
Rank_Level First Tier Top Universities Other Top Universities
country
Argentina                          NaN              44.672857
Australia                      47.9425              44.645750
Austria                            NaN              44.864286
Belgium                        51.8750              45.081000
Brazil                             NaN              44.499706

                                                                     \
Rank_Level Second Tier Top Universities Third Tier Top Universities
country
Argentina                           NaN                         NaN
Australia                       49.2425                   47.285000
Austria                             NaN                   47.066667
Belgium                         49.0840                   46.746667
Brazil                          49.5650                         NaN

                                  amin                         \
Rank_Level First Tier Top Universities Other Top Universities
country
Argentina                          NaN                  44.10
Australia                        44.13                  44.09
Austria                            NaN                  44.19
Belgium                          51.72                  44.31
Brazil                             NaN                  44.03


Rank_Level Second Tier Top Universities Third Tier Top Universities
country
Argentina                           NaN                         NaN
Australia                         47.97                       47.10
Austria                             NaN                       46.39
Belgium                           48.08                       46.21
Brazil                            49.31                         NaN

In [44]:
# in pandas pivot table, we can also include marginal value (eg: max of the max, avg of the avg)
df.pivot_table(values="score", index="country", columns='Rank_Level',aggfunc=[np.mean, np.min]
              ,margins=True).head()

                                  mean                         \
Rank_Level First Tier Top Universities Other Top Universities
country
Argentina                          NaN              44.672857
Australia                      47.9425              44.645750
Austria                            NaN              44.864286
Belgium                        51.8750              45.081000
Brazil                             NaN              44.499706

                                                                     \
Rank_Level Second Tier Top Universities Third Tier Top Universities
country
Argentina                           NaN                         NaN
Australia                       49.2425                   47.285000
Austria                             NaN                   47.066667
Belgium                         49.0840                   46.746667
Brazil                          49.5650                         NaN

                                             amin                         \
Rank_Level        All First Tier Top Universities Other Top Universities
country
Argentina   44.672857                         NaN                  44.10
Australia   45.825517                       44.13                  44.09
Austria     45.139583                         NaN                  44.19
Belgium     47.011000                       51.72                  44.31
Brazil      44.781111                         NaN                  44.03


Rank_Level Second Tier Top Universities Third Tier Top Universities    All
country
Argentina                           NaN                         NaN  44.10
Australia                         47.97                       47.10  44.09
Austria                             NaN                       46.39  44.19
Belgium                           48.08                       46.21  44.31
Brazil                            49.31                         NaN  44.03

In [45]:
# checking details of a pivot table
pivot_tab=df.pivot_table(values="score", index="country", columns='Rank_Level',aggfunc=[np.mean, np.min]
                        ,margins=True)
print(pivot_tab.columns)
print(pivot_tab.index)

MultiIndex([('mean',  'First Tier Top Universities'),
            ('mean',       'Other Top Universities'),
            ('mean', 'Second Tier Top Universities'),
            ('mean',  'Third Tier Top Universities'),
            ('mean',                          'All'),
            ('amin',  'First Tier Top Universities'),
            ('amin',       'Other Top Universities'),
            ('amin', 'Second Tier Top Universities'),
            ('amin',  'Third Tier Top Universities'),
            ('amin',                          'All')],
           names=[None, 'Rank_Level'])
Index(['Argentina', 'Australia', 'Austria', 'Belgium', 'Brazil', 'Bulgaria',
       'Canada', 'Chile', 'China', 'Colombia', 'Croatia', 'Cyprus',
       'Czech Republic', 'Denmark', 'Egypt', 'Estonia', 'Finland', 'France',
       'Germany', 'Greece', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Iran',
       'Ireland', 'Israel', 'Italy', 'Japan', 'Lebanon', 'Lithuania',
       'Malaysia', 'Mexico', 'Netherlands', 'New Zealand', 'Norway', 'Poland',
       'Portugal', 'Puerto Rico', 'Romania', 'Russia', 'Saudi Arabia',
       'Serbia', 'Singapore', 'Slovak Republic', 'Slovenia', 'South Africa',
       'South Korea', 'Spain', 'Sweden', 'Switzerland', 'Taiwan', 'Thailand',
       'Turkey', 'USA', 'Uganda', 'United Arab Emirates', 'United Kingdom',
       'Uruguay', 'All'],
      dtype='object', name='country')

In [46]:
# data extract at pivot table
pivot_tab['mean']['First Tier Top Universities'].head()

country
Argentina        NaN
Australia    47.9425
Austria          NaN
Belgium      51.8750
Brazil           NaN
Name: First Tier Top Universities, dtype: float64

In [48]:
# if you want to achieve different shape of your pivot table => we have the stack and unstack functions
# Stacking is pivoting the lowermost column index to become innermost row index
# Unstacking # stacking inversedly
pivot_tab.stack().head()

                                             mean   amin
country   Rank_Level
Argentina Other Top Universities        44.672857  44.10
          All                           44.672857  44.10
Australia First Tier Top Universities   47.942500  44.13
          Other Top Universities        44.645750  44.09
          Second Tier Top Universities  49.242500  47.97

In [49]:
# Stacking and Unstacking function will change the way that pvt 
# arranges rows and columns. Classifying columns will be converted to rows
pivot_tab.stack().head()

                                             mean   amin
country   Rank_Level
Argentina Other Top Universities        44.672857  44.10
          All                           44.672857  44.10
Australia First Tier Top Universities   47.942500  44.13
          Other Top Universities        44.645750  44.09
          Second Tier Top Universities  49.242500  47.97

In [52]:
pivot_tab.unstack().unstack().unstack().head()

country                      Argentina                         \
Rank_Level First Tier Top Universities Other Top Universities
mean                               NaN              44.672857
amin                               NaN              44.100000

country                                                              \
Rank_Level Second Tier Top Universities Third Tier Top Universities
mean                                NaN                         NaN
amin                                NaN                         NaN

country                                 Australia                         \
Rank_Level        All First Tier Top Universities Other Top Universities
mean        44.672857                     47.9425               44.64575
amin        44.100000                     44.1300               44.09000

country                                                              \
Rank_Level Second Tier Top Universities Third Tier Top Universities
mean                            49.2425                      47.285
amin                            47.9700                      47.100

country                ...                     Uruguay                         \
Rank_Level        All  ... First Tier Top Universities Other Top Universities
mean        45.825517  ...                         NaN                 44.255
amin        44.090000  ...                         NaN                 44.160

country                                                                      \
Rank_Level Second Tier Top Universities Third Tier Top Universities     All
mean                                NaN                         NaN  44.255
amin                                NaN                         NaN  44.160

country                            All                         \
Rank_Level First Tier Top Universities Other Top Universities
mean                         58.350675              44.738871
amin                         43.360000              44.020000

country
Rank_Level Second Tier Top Universities Third Tier Top Universities        All
mean                           49.06545                    46.84345  47.798395
amin                           47.49000                    45.95000  43.360000

[2 rows x 300 columns]

# Date/Time Functionality

In [3]:
# Timestamp => create a timestamp value ( string dtype )
pd.Timestamp('19/06/2023 12:39PM')

Timestamp('2023-06-19 12:39:00')

In [9]:
pd.Timestamp(2023,6,19,12,39,45)

Timestamp('2023-06-19 12:39:45')

In [10]:
# There are some timestamp attributes that could be used to gain information
pd.Timestamp(2023,6,19,12,39,45).isoweekday()

1

In [13]:
# In the Timestamp value type, you can do useful manipulations like
# extracting year, month, day, hour, minute, second
pd.Timestamp(2023,6,19,12,39,45).year

2023

In [22]:
# If we don't want to have a specific time point,
# we can use the Period class to get a time span. Lets create
# a Priod of June 2023
pd.Period('6/2023') + 7

Period('2024-01', 'M')

In [19]:
# a Priod of 19th date in June 2023
pd.Period('19/6/2023') + 12

Period('2023-07-01', 'D')

In [57]:
# Lets see how many days left in 2023
now = pd.Timestamp(2023,6,19)
there = pd.Timestamp(2024,1,1)
len(pd.period_range(now,there))
pd.date_range(now,there)

DatetimeIndex(['2023-06-19', '2023-06-20', '2023-06-21', '2023-06-22',
               '2023-06-23', '2023-06-24', '2023-06-25', '2023-06-26',
               '2023-06-27', '2023-06-28',
               ...
               '2023-12-23', '2023-12-24', '2023-12-25', '2023-12-26',
               '2023-12-27', '2023-12-28', '2023-12-29', '2023-12-30',
               '2023-12-31', '2024-01-01'],
              dtype='datetime64[ns]', length=197, freq='D')

## Datetimeindex and Periodindex

In [34]:
t1 = pd.Series(list('abc'),[pd.Timestamp(2023,6,19),
                            pd.Timestamp(2023,6,19),
                            pd.Timestamp(2023,6,19)])
t1

2023-06-19    a
2023-06-19    b
2023-06-19    c
dtype: object

In [36]:
# Special things is that we can use timestamp as the index of a series
t1.index

DatetimeIndex(['2023-06-19', '2023-06-19', '2023-06-19'], dtype='datetime64[ns]', freq=None)

In [37]:
type(t1.index)

pandas.core.indexes.datetimes.DatetimeIndex

## Converting to Datetime Object

In [42]:
import random
df = ['19 June 2023', '27/3/2024', '19-5-2019', '6-19-2023']
df1 = pd.DataFrame(np.random.randint(1,100,(4,2)),index=df,columns=list('ab'))
df1

               a   b
19 June 2023  72   3
27/3/2024     14  73
19-5-2019      3  36
6-19-2023     53  12

In [43]:
# pandas to_datetime function will convert data to the datatime type for datetime analysis
df1.index = pd.to_datetime(df1.index)
df1

             a   b
2023-06-19  72   3
2024-03-27  14  73
2019-05-19   3  36
2023-06-19  53  12

## Timedelta

In [44]:
# This function in pd resembles the Period class. It's usually used for caculating the period between 2 timestamps
pd.Timestamp('1,1,2024')-pd.Timestamp('19/6/2023')

Timedelta('196 days 00:00:00')

In [47]:
pd.Timestamp('19/6/2023') + pd.Timedelta('196D')

Timestamp('2024-01-01 00:00:00')

In [52]:
# We can also use the .offsets attribute for creating a timedelta from now to a specific point in the future
pd.Timestamp(2023,6,19)+pd.offsets.Week()

Timestamp('2023-06-26 00:00:00')

In [54]:
pd.Timestamp(2023,6,19)+pd.offsets.MonthEnd()

Timestamp('2023-06-30 00:00:00')